### ISSUE TITLE
10 Placements not appear in good layout in Challenge page

### ISSUE THREAD

**Issue by dedywahyudi** [topcoder-platform/work-manager#1000]
### Expected behavior
10 Placements should appear in good layout and structure in Challenge page

### Actual behavior
10 Placements not appear in good layout in Challenge page

### Steps to reproduce the problem
- Create new design challenge 
- Add 10 Prizes under Challenge Prizes
- Save as draft 
- Go to Challenge Details page and see the layout not correct. 5 to 10 winners placement should be placed below the Top 5. 

### Screenshot/screencast
![Screen Shot 2020-12-16 at 14 30 17](https://user-images.githubusercontent.com/4476442/102318180-7f24ae80-3fab-11eb-8a22-fa79313e1ef9.png)

![Screen Shot 2020-12-16 at 14 29 29](https://user-images.githubusercontent.com/4476442/102318194-821f9f00-3fab-11eb-9da1-91b3c30fb224.png)

**Comment by acshields** [comment]
Hi @dedywahyudi - This will be a fix request that needs to go on the community team's backlog (not Work Manager). I will notify them of this observation.

**Comment by dedywahyudi** [comment]
@acshields ah thanks. So, we able to log issues in community page? 
I assume the issues need logged here? 

https://github.com/topcoder-platform/community-app/issues

**Comment by acshields** [comment]
Yep! I also passed this one along to Oanh, the PM for the community app for her to take a look. Thanks for sharing the observation!

**Comment by dedywahyudi** [comment]
@acshields Great, thanks.
