### ISSUE TITLE
Disable selection of Internal Review type for QA challenges

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#1001]
### Expected behavior
WM should not allow editing the review type for QA challenges

### Actual behavior
As of now it allows user to edit the review type for a QA challenge which gets overridden once the legacy challenge is created because of a business rule which does not allow review type to be internal for a QA challenge.

### Steps to reproduce the problem
- Create a QA challenge
- Choose Internal as review type
- Save as Draft and then Activate it
- Wait for 3-5 minutes to sync to settle down
- Now, edit the activated challenge and observe that Review type is set to Community now.

### Screenshot/screencast
https://github.com/topcoder-platform/work-manager/issues/979#issuecomment-746017562

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Copilot/Manager
- Account used: N/A

**Comment by lakshmiathreya** [comment]
Verified disabling of Internal Review selection for QA challenges in Prod.
<img width="1680" alt="Screenshot 2020-12-16 at 6 44 17 PM" src="https://user-images.githubusercontent.com/51733042/102354260-5531b300-3fd0-11eb-9831-f093ee5e152b.png">
