### ISSUE TITLE
Final deliverables, stock arts  and submission visibility are disappearing after activating the challenge.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/work-manager#1005]
Description:

Final deliverables, stock arts  and submission visibility of Design challenges are disappearing after activation.

challenge used: https://challenges.topcoder.com/projects/24943/challenges/9e753a77-a61b-4e42-83e0-228e3c2f1821

<img width="960" alt="design_challenge_issue" src="https://user-images.githubusercontent.com/55895538/102471641-cccb1500-4098-11eb-9113-eb69dd1d96af.png">
<img width="960" alt="design_challenge_issue_2" src="https://user-images.githubusercontent.com/55895538/102471660-d05e9c00-4098-11eb-890b-dd9b458e9ab7.png">

**Comment by sandhiyakavi** [comment]
cc: @lakshmiathreya

**Comment by vikasrohit** [comment]
@rootelement do we need to update any key in WM UI?

**Comment by acshields** [comment]
@rootelement - any updates?

**Comment by vikasrohit** [comment]
@drasticdpk @lakshmiathreya marking ready for qa to have the updated status of the issue. Should be fixed with past few updates in legacy processors.

**Comment by drasticdpk** [comment]
Unable to activate new challenge.
![image](https://user-images.githubusercontent.com/25297859/105023955-a7ed0780-5a73-11eb-8d66-635b55060885.png)

**Comment by vikasrohit** [comment]
@drasticdpk I think you should have BA attached for today

**Comment by maxceem** [comment]
This works good as per my testing on DEV https://monosnap.com/file/Q47TSReHUIwnBxIZheI6TNfRRqfWMs. But yeah, BA should be attached to be able to activate.

**Comment by vikasrohit** [comment]
@drasticdpk are you able to verify it now? BA may got removed soon from the project.

**Comment by vikasrohit** [comment]
I am closing it without QA green signal as we don't yet have the right test conditions for the QA to verify and at least one person(@maxceem ) can see it working in DEV env. @drasticdpk please feel free to reopen the issue if it is still breaking.

**Comment by drasticdpk** [comment]
Verified. 
Working as expected
![image](https://user-images.githubusercontent.com/25297859/105724372-e5f49a80-5f4f-11eb-9d67-b87757c5ec22.png)
