### ISSUE TITLE
Launch/Activate button not enabled if more than one group is added to the challenge.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/work-manager#1006]
Description:

Launch/Activate button is not enabled if more than one group is added to the challenge.

sample challenges:

https://challenges.topcoder.com/projects/24943/challenges/03b4c874-e0c8-4cf3-b886-47768367193b/edit
https://challenges.topcoder.com/projects/24943/challenges/af257db1-3a48-47f9-a200-698cb8e06369/edit

![image](https://user-images.githubusercontent.com/55895538/102474141-9f339b00-409b-11eb-8255-37166f34619d.png)
![image](https://user-images.githubusercontent.com/55895538/102474237-bffbf080-409b-11eb-8bb3-8b7349b5352a.png)
![image](https://user-images.githubusercontent.com/55895538/102474086-8e832500-409b-11eb-8c08-14a8d6f87a21.png)

**Comment by sandhiyakavi** [comment]
cc: @lakshmiathreya

**Comment by vikasrohit** [comment]
@rootelement we might be getting some error in legacy sync when there are multiple groups associated to a challenge.

**Comment by acshields** [comment]
@rootelement @ThomasKranitsas - any updates on this one?

**Comment by drasticdpk** [comment]
@vikasrohit  i verified this issue, it is working as expected. 
Reference Challenge : https://challenges.topcoder-dev.com/projects/16640/challenges/aeb89497-cf09-4234-96e6-11b3f5da79c9/view
