### ISSUE TITLE
Could not find project

### ISSUE THREAD

**Issue by kylewu** [topcoder-platform/work-manager#1018]
### Expected behavior
Go to https://challenges.topcoder.com/ and type project name should show the project in result.

### Actual behavior
The project cannot be found via search.
The project exists in https://challenges.topcoder.com/projects/26478/challenges

### Steps to reproduce the problem
- Go to https://challenges.topcoder.com/
- search for `Arena` and i see no project

### Screenshot/screencast
The project exists
https://challenges.topcoder.com/projects/26478/challenges

--

#### Environment
- OS: MacOs
- Browser (w/version): Firefox 84.0
- User role (client, copilot or manager): copilot
- Account used: wenbin

**Comment by acshields** [comment]
@kylewu - can you confirm that you are joined to the project in Connect? This is a requirement that determines what projects a user sees in Work Manager.

**Comment by kylewu** [comment]
@acshields yes. i could see i'm one copilot in https://www.topcoder.com/direct/projectOverview?formData.projectId=29139

**Comment by vikasrohit** [comment]
The project is not yet active @acshields. @kylewu it needs project to be in Active state to get it listed in Work Manager.

**Comment by kylewu** [comment]
@vikasrohit this state?
<img width="816" alt="Screenshot 2021-01-04 at 13 24 00" src="https://user-images.githubusercontent.com/180198/103534941-218bcf80-4e90-11eb-9958-3bcd38ea7094.png">

**Comment by acshields** [comment]
@kylewu - the project needs to be "Active" in Connect.

**Comment by kylewu** [comment]
@acshields i see. Thanks!
