### ISSUE TITLE
Saving challenge shows error and won't redirect to previous page

### ISSUE THREAD

**Issue by coderReview** [topcoder-platform/work-manager#1066]
### Expected behavior
Should save challenge without error.

### Actual behavior
User pvmagacho already has resource with roleId: <id> in challenge: <id>

### Steps to reproduce the problem
- Try to save

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/5925442/107135821-c7da5300-68dc-11eb-9365-bb97a0b008a1.png)

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): copilot
- Account used: pvmagacho

**Comment by vikasrohit** [comment]
@coderReview Please try refreshing the page and try again, it happens when there is some issue with resource addition/modification. or please get yourself (pvmagacho) removed from from the challenge resources from copilot role and then try again to save the challenge.

**Comment by coderReview** [comment]
Every time I save the challenge I get this error. I can continue using but still an issue.

**Comment by vikasrohit** [comment]
Ok, I guess then you need to ask support to get your self removed from the challenge and then try, if it still does not work for you, please add some details to the issue for reproducing the issue. I would definitely be a bug in that case.

**Comment by coderReview** [comment]
@vikasrohit this happen in all challenges I've created. Every time I tried to update the specfiications and save it again I get the error above. If it was for one challenge or the other ok, but it's always.

**Comment by vikasrohit** [comment]
@coderReview I have got it. And in fact my observation was also the same, every time after one update the specs, and then save the challenge, the error is visible.
We would apply fix for it soon.

**Comment by vikasrohit** [comment]
@drasticdpk @lakshmiathreya I have pushed this change to production with our today's release. I fixed it last night so didn't get enough time to get it QAed in dev.

**Comment by drasticdpk** [comment]
Verified on prod mode.
Tested scenario : At Edit mode , update spec, select/deselect copilot etc.
![image](https://user-images.githubusercontent.com/25297859/107625092-ea28f380-6c83-11eb-802d-5d21c2f5fb5c.png)

Ok noted @vikasrohit .
@coderReview thank you for raising the issue. please let us know if you still get the same issue .
Thank you !

**Comment by coderReview** [comment]
Confirmed it's working now. Thank you @vikasrohit @drasticdpk
