### ISSUE TITLE
Prize sum is calculated wrong way

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/work-manager#1074]
![image](https://user-images.githubusercontent.com/146016/108488353-f414ad00-72a8-11eb-8069-9bf3cba4dbe9.png)

This happens if the prize is defined as a string with a float number like:

```js
"prizeSets": [
    {
        "type": "copilot",
        "prizes": [
            {
                "type": "USD",
                "value": "75.0" // such format causes issue
            }
        ]
    }
],
```

**Comment by maxceem** [comment]
The calculation has been fixed by ac0842103078039f05bf76065a1678093806569f

Example challenge for testing on DEV http://challenges.topcoder-dev.com/projects/16839/challenges/e4775ec3-d6a9-4e1c-8ce6-4a919d273bfe/view (**DON'T** update it, or you would rewrite the test data).

**Comment by drasticdpk** [comment]
It is showing expected result for API data.
![image](https://user-images.githubusercontent.com/25297859/108682412-5aebcd80-7518-11eb-91fe-eed3fcdf8463.png)

@maxceem , However I want to test different scenario. 
What if user copy the prize/copilot fee from somewhere (let's say from google sheet/notepad ), at that time it is only replacing the **.**  which makes wrong calculation, please suggest. 
**Reference** 
![image](https://user-images.githubusercontent.com/25297859/108682942-0e54c200-7519-11eb-9a6e-bf3bd2413085.png)

**Comment by maxceem** [comment]
> @maxceem , However I want to test different scenario.
> What if user copy the prize/copilot fee from somewhere (let's say from google sheet/notepad ), at that time it is only replacing the . which makes wrong calculation, please suggest.

@drasticdpk I'm not sure what would be good behavior in such a case. What should be expected results of pasting such a number?
1. `75`
2. `75.1` (I guess we don't allow such prizes)
3. nothing?

But this is another issue regarding copy/pasting. If we prefer to fix it, I would suggest tracking it in a separate issue, as the sum calculation is correct `100 + 751 = 851`.

**Comment by drasticdpk** [comment]
Agreed @maxceem . Better let's create separate issue so we will discuss over there.

**Comment by lakshmiathreya** [comment]
<img width="1680" alt="Screenshot 2021-02-23 at 4 42 02 PM" src="https://user-images.githubusercontent.com/51733042/108835967-4120b800-75f6-11eb-994f-15ff3c6a438e.png">
