### ISSUE TITLE
I am able to access a challenge that I am not part of connect project team

### ISSUE THREAD

**Issue by coderReview** [topcoder-platform/work-manager#1080]
### Expected behavior
Should not be able to access a challenge that I am not part of connect project team.

### Actual behavior
I am able to access a challenge that I am not part of connect project team.

### Steps to reproduce the problem
- Open a challenge in work manager that you are part  of connect project team, or you are not an Admin
 
### Screenshot/screencast
![image](https://user-images.githubusercontent.com/5925442/108770868-9e0a6880-7539-11eb-8d53-e2c798f4dc9b.png)

![image](https://user-images.githubusercontent.com/5925442/108770937-b67a8300-7539-11eb-9bc0-9aa99a178362.png)

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): copilot
- Account used: pvmagacho

**Comment by vikasrohit** [comment]
@coderReview thanks for the feedback, however, it is as per requirements because challenges are public and any one can see the basic challenge details but can not edit a challenge until he/she is part of the challenge. Do you see any use case where we are showing any information on this page which is not publicly viewable already? If yes, we can think of some solution for it.

**Comment by coderReview** [comment]
Then in this case I have another issue. When you go to one of this challenge and click back it goes to this page

https://challenges.topcoder.com/projects/undefined/challenges

which I think it’s not correct

I can change the issue details if necessary

**Comment by vikasrohit** [comment]
That is something which we saw in past and fixed it. But it can stil happen, it is essentially stale state. @maxceem do you think we can get it fixed in our 2 weeks of quick wins time?

**Comment by vikasrohit** [comment]
In any case, we should close this issue and log a separate issue for better tracking.

**Comment by vikasrohit** [comment]
Closing as I have created separate issue for the concern.
