### ISSUE TITLE
Incorrect URL when user moves back using Back button

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#1081]
Carried from https://github.com/topcoder-platform/work-manager/issues/1080#issuecomment-784140075

When you go to one of this challenge and click back it goes to this page

https://challenges.topcoder.com/projects/undefined/challenges

which I think it’s not correct.

**Comment by maxceem** [comment]
@vikasrohit @coderReview I cannot reproduce this issue, do you have steps to reproduce it?

It works good for me, see video https://monosnap.com/file/gCh5HriTX9s2h4NzBMIQuJQV9RIcSx

**Comment by coderReview** [comment]
Click the back button on the right side of the page.

**Comment by maxceem** [comment]
Thanks for clarification @coderReview, but I still cannot reproduce:

I cannot access this project:

![image](https://user-images.githubusercontent.com/146016/109313122-8809ea00-7850-11eb-9bc0-a1117565241c.png)

I open a challenge inside that project:

![image](https://user-images.githubusercontent.com/146016/109313181-98ba6000-7850-11eb-8fa2-974c8c3a123a.png)

Click "Back" on the right works good to me:

![image](https://user-images.githubusercontent.com/146016/109313250-abcd3000-7850-11eb-852f-95f225cc702d.png)

See demo video https://monosnap.com/file/GKX6YiuRB4NLH5MViMC7Eh8mWyPSr4

**Comment by coderReview** [comment]
@maxceem can't seem to reproduce it anymore.

**Comment by vikasrohit** [comment]
Closing as no one can reproduce it any more. :)
