### ISSUE TITLE
The Continue Setup Button disable: Unable to create the challenge, task, and first2finish  due to this

### ISSUE THREAD

**Issue by coderhacker** [topcoder-platform/work-manager#1097]
### Expected behavior
The Continue Set-up button should be active for all challenges, TASK, FNF 
### Actual behavior

The Continue Setup Button disable: Unable to create the challenge, task, and first and finish  due to this

### Steps to reproduce the problem
1. go to this URL https://challenges.topcoder-dev.com/projects/16573/challenges/new.
2. Create challenge, task, and first2finish  for all Development, Data Science, Design and Quality Assurance 

### Screenshot/screencast
Attach or link a resource.

https://user-images.githubusercontent.com/62358241/110074352-14fbf880-7da7-11eb-9429-d18379b444b2.mp4

![image](https://user-images.githubusercontent.com/62358241/110118023-bd2db380-7ddf-11eb-8d12-a895616b7572.png)
![image](https://user-images.githubusercontent.com/62358241/110118064-ca4aa280-7ddf-11eb-8800-a2b6282924a3.png)

https://user-images.githubusercontent.com/62358241/110118131-e51d1700-7ddf-11eb-829e-3df4f9b456a8.mp4

--

#### Environment
- OS: win 10
- Browser (w/version): All browsers and devices
- User role (client, copilot or manager): copilot
- Account used:  valid copilot accoutn

**Comment by coderhacker** [comment]
@drasticdpk  @lakshmiathreya

**Comment by maxceem** [comment]
@rootelement @drasticdpk we don't have such an issue in the main `develop` branch, so it's likely caused by the timeline selector:

![image](https://user-images.githubusercontent.com/146016/110355186-a090b600-8041-11eb-9669-07b9dfdb1991.png)

**Comment by coderhacker** [comment]
Update: It's blocking further testing on Dev. please see the updated video.

https://user-images.githubusercontent.com/62358241/110587279-7520df00-8199-11eb-903b-9536e772df0e.mp4

**Comment by coderhacker** [comment]
This is passed on production 

https://user-images.githubusercontent.com/62358241/119331321-d9394680-bca4-11eb-99c1-a5fbd5ddc76b.mp4
