### ISSUE TITLE
Sync issue post challenge Activation

### ISSUE THREAD

**Issue by m-yadav** [topcoder-platform/work-manager#1099]
### Expected behavior
Challenge created by Work Manager when activated should be synced to show the correct status on the challenge page

### Actual behavior
Challenge created by Work Manager even when activated keeps on showing as registration button disabled on the challenge page. Only upon force re-indexing the correct status of phase and challenge is shown on the challenge page. 

Activating the challenge successfully

![image](https://user-images.githubusercontent.com/45197181/110405337-70c7c980-80a6-11eb-9af2-671f50736476.png)

Status of Phase in OR is open 

![image](https://user-images.githubusercontent.com/45197181/110406293-fd26bc00-80a7-11eb-94d6-a465a245e762.png)

Status on Challenge page

![image](https://user-images.githubusercontent.com/45197181/110406319-0879e780-80a8-11eb-9dcf-9f7d79cdc054.png)

Post Force Re-index

![image](https://user-images.githubusercontent.com/45197181/110406469-4aa32900-80a8-11eb-929e-727601bde999.png)

Changes done on challenges are not reflecting back on the challenge page. Only Upon force re-indexing the changes are reflecting on the challenge page as seen above

**Comment by acshields** [comment]
Notified Oanh Tran/community app of this issue.
