### ISSUE TITLE
Source code and other files are downloadable from Work Manager

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#1104]
### Expected behavior
One should not be able to download source code files e.g. build.sh, README.md etc from the deployed application

### Actual behavior
As of now it is allowing a user to download any file that is present in the github repo via the application URL

### Steps to reproduce the problem
- Load https://challenges.topcoder.com/build.sh
- It should not download

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used: Any

**Comment by drasticdpk** [comment]
Verified on Dev and prod 
Now it is redirect to https://challenges.topcoder.com from https://challenges.topcoder.com/**** . (other than define Route)
