### ISSUE TITLE
[$50] Design Challenges: Display Pop-Up Message

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#1122]
### **Context**
Due to the present inability to support multi-round (checkpoint) challenges in Work Manager, please display this warning message to users attempting to create a design challenge in Work Manager.

### **Update**
**Pre-Conditions**
- Type = Design
- Format = Challenge

**Warning Workflow**
Once the user enters the pre-conditions above, a pop-up window appears.
The pop-up message reads:
- Header: "Reminder"
- Body 1: "At this time, Work Manager only supports single-round (no checkpoint) challenges for design. If you want to run a multi-round (has checkpoints) design challenge, please use Direct."
- Body 2: "Do you want to proceed with set-up?"
- Button 1: "Continue Set-Up" (If clicked, user proceeds into Work Manager set-up flow)
- Button 2: "Cancel Set-Up" (If clicked, the set-up operation is cancelled)

**Comment by acshields** [comment]
@maxceem @vikasrohit - can we get this one done in light of the API issues with for design challenges?

**Comment by maxceem** [comment]
@yoution would you like to handle it? if so, please comment and you can work on it.
- Please, reuse the design of other popups we have like this one:

   ![image](https://user-images.githubusercontent.com/146016/111542009-d9373a80-8779-11eb-8af8-e9c400832fbc.png)
- Create a new component for this popup and try to keep as much logic inside that component as possible.

@acshields I have just one question, in case user clicks `Button 2: "Cancel Set-Up" (If clicked, the set-up operation is cancelled)`. Should we go to the challenge list, or what does `the set-up operation is cancelled` mean?

**Comment by yoution** [comment]
@maxceem please assign to me

**Comment by yoution** [comment]
@maxceem  
1.left button confirm, and right button cancel?
2.there are already two components existed, `AlertModel` and `ConfirmationModal`, what 's the new name of the component?

**Comment by maxceem** [comment]
@yoution 

> 1.left button confirm, and right button cancel?

let's make left cancel, and right - confirm

> 2.there are already two components existed, AlertModel and ConfirmationModal, what 's the new name of the component?

If we can reuse any of these existent modals, please, reuse them. If no, then name a new component `DesignChallengeWarningModal`.

**Comment by maxceem** [comment]
@acshields this is done, demo video https://monosnap.com/file/1vM7hp16OKpFBOcoAX32G5zUkGExmD. 

hotfix:
- DEV https://github.com/topcoder-platform/work-manager/pull/1125 (merged)
- PROD https://github.com/topcoder-platform/work-manager/pull/1124

**Comment by coderhacker** [comment]
this is passed on dev
https://user-images.githubusercontent.com/62358241/112940656-1244b700-914b-11eb-9cee-75814c812263.mp4

**Comment by coderhacker** [comment]
This is passed on Prod 

https://user-images.githubusercontent.com/62358241/113124475-2b289780-9233-11eb-8db4-99d2c5d0ee10.mp4

**Comment by coderhacker** [comment]
Closing the issue
