### ISSUE TITLE
Actionable affordances are inconsistent and confusing

### ISSUE THREAD

**Issue by aaabbott** [topcoder-platform/work-manager#1129]
### Expected behavior
Work Manager has inconsistent styling of actionable affordances which leads to a confusing user experience as well as a lack of clarity of how to engage.

### Actual behavior
In Work Manager, one of the main actions is to "Activate" a piece of work which has been drafted. The UI enables this via a button-looking element that only has a colored border. This differentiates it from the very similar UI convention we are using to show its type of work (i.e. Task) and status.
![image](https://user-images.githubusercontent.com/6266701/113301104-a5592a80-92cc-11eb-87f2-e0508c7017f4.png)

However, once you create a task and waiting for it to be created by the legacy, the UI provides a button to delete the task that is inconsistent with the styling of Activate. It's not just a colored border but a solid colored element which makes it similar to the non-actionable work and status tags. As a user, this leads me to be unsure which elements I should actually interact with.
![image](https://user-images.githubusercontent.com/6266701/113300698-2fed5a00-92cc-11eb-8d62-2ea51d297bda.png)

A simple fix would be to update the styling of the delete button to match that of the activate. I do think a broader rethinking of tags versus buttons would be helpful to make the application more user-friendly.

### Steps to reproduce the problem
- Create a task
- Return to main project page
- Observe the user interface for newly created work

### Screenshot/screencast
Attach or link a resource.

--

#### Environment
- All

**Comment by vikasrohit** [comment]
@acshields we can take it in this bug fix round. For now, we are going to make `Delete` button consistent with `Activate` button as suggested by @aaabbott, by removing the solid fill of the `Delete` button.

**Comment by vikasrohit** [comment]
@acshields @aaabbott I have made following changes for now to make tags/status and actionable button differentiable.

<img width="1171" alt="Screen Shot 2021-05-06 at 10 53 36 AM" src="https://user-images.githubusercontent.com/2417632/117246067-8f093600-ae59-11eb-8f7e-52983b456793.png">

**Comment by vikasrohit** [comment]
@drasticdpk this one is ready for QA.

**Comment by coderhacker** [comment]
QA Comment: This is pass on dev 

![image](https://user-images.githubusercontent.com/62358241/118443517-9bb74500-b709-11eb-8c98-23d6035328df.png)

Uploading 2021-05-17-11-45-37.mp4…

**Comment by coderhacker** [comment]
https://user-images.githubusercontent.com/62358241/118443703-d9b46900-b709-11eb-8630-5f07a9c8b9d4.mp4

**Comment by coderhacker** [comment]
This is passed on Prod:

![image](https://user-images.githubusercontent.com/62358241/118630704-69cadf00-b7ec-11eb-963e-85be0e841795.png)

https://user-images.githubusercontent.com/62358241/118630727-6f282980-b7ec-11eb-9197-6152efe8088f.mp4

**Comment by vikasrohit** [comment]
@aaabbott fyi

**Comment by vikasrohit** [comment]
**Update:** Unfortunately we have to rollback the release from production @aaabbott for some time because of some other unintended changes propagated to prod.

**Comment by aaabbott** [comment]
No worries
