### ISSUE TITLE
Task startDate should be today's date

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/work-manager#1132]
### Expected behavior
When running a task via the WM, the `startDate` should be today's date and not tomorrow's date. Or, we should at least be able to modify the date.

### Actual behavior
The WM is currently using tomorrow's date as `startDate` which is very annoying.

### Steps to reproduce the problem
- Create a Development Task
- Save as draft
- Activate
- Close
- Observe. The task will close in OR after 1 day

**Comment by rootelement** [comment]
You _can_ modify the date. It's at the bottom of first "box", above the Challenge Description. But it shouldn't default to tomorrow.

I think the fix here is, by default, there's a check box that says "Open Registration On Launch" that is checked, and if you uncheck it, then you can set the start date in the future.

This is a big pain with tasks, as it seems to ignore the start date, or the start date gets set back to tomorrow when editing the task.

**Comment by vikasrohit** [comment]
Closing in favour of https://github.com/topcoder-platform/work-manager/issues/1139 as active work is going on there.
