### ISSUE TITLE
Unable to assign task to a member in Work Manager

### ISSUE THREAD

**Issue by ketzjs09** [topcoder-platform/work-manager#1137]
When creating a task, when I type someone's name in the _Assign To:_ section, no search results appear.

**Comment by vikasrohit** [comment]
It works with handle only as of now.

**Comment by ketzjs09** [comment]
Sorry, I meant handle. Nothing showed up when I entered the handle. It used to work the last time I checked a few days ago.

**Comment by vikasrohit** [comment]
ohk. It might be temporary glitch with member api. As of now it is loading the possible handles matching the typed characters.

**Comment by vikasrohit** [comment]
@ketzjs09 We have found the root cause for your problem. Please log a support ticket to add a copilot role to your handle. You are missing `copilot` role in your profile which is causing this trouble to you.

**Comment by vikasrohit** [comment]
Closing the issue for now @ketzjs09 please feel free to reopen if you are still seeing the issue.
