### ISSUE TITLE
Winner Tab is showing blank when task is completed

### ISSUE THREAD

**Issue by coderhacker** [topcoder-platform/work-manager#1146]
### Expected behavior
The winner should not show blank.

### Actual behavior
The winner Tab is showing blank when the task is completed.

### Steps to reproduce the problem
Please attached video for reproducing the issue

https://user-images.githubusercontent.com/62358241/117283089-14eda700-ae83-11eb-905a-656d1986744e.mp4

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/62358241/117283136-2040d280-ae83-11eb-9eaf-4c5bfbe6c76a.png)

--

#### Environment
- OS: Windows
- Browser (w/version): all browsers
- User role (client, copilot or manager): copilot
- Account used:

**Comment by coderhacker** [comment]
Dev Challange ID : https://www.topcoder-dev.com/challenges/44ba8825-d025-4e40-b3d7-7940ab2c7f6a?tab=winners

![image](https://user-images.githubusercontent.com/62358241/119329332-b9a11e80-bca2-11eb-9459-1ae14513ee77.png)

Production Challenge id: https://www.topcoder.com/challenges/2c88a923-dd93-4a5f-96be-3c52d5e7a604?tab=winners

![image](https://user-images.githubusercontent.com/62358241/119329400-cde51b80-bca2-11eb-88c0-21eb719ae31d.png)

**Comment by rootelement** [comment]
My guess is this is the problem:

https://github.com/topcoder-platform/community-app/blob/develop/src/shared/containers/challenge-detail/index.jsx#L366

You're pulling track from the legacy object, but there is no legacy track. You should be using the base challenge object track and types. Remember, each challenge has:
```
challenge.track (string name - like Design)
challenge.type (string name - like Challenge)
challenge.trackId (uuid)
challenge.typeId (uuid)
```

This is true for all parts of community app. You shouldn't be referring to track or type in the legacy object. As of now, the only things that should refer to the legacy object are _maybe_ `reviewType` and possibly `pureV5Task`.

**Comment by lakshmiathreya** [comment]
Fixed in https://github.com/topcoder-platform/community-app/issues/5529
