### ISSUE TITLE
Forum link is not active for the Active challenges 

### ISSUE THREAD

**Issue by coderhacker** [topcoder-platform/work-manager#1150]
### Expected behavior
Forum link is available for the Active challenges, this should be active.

Please note: This is working on the Production environment. please see attached screenshot
![image](https://user-images.githubusercontent.com/62358241/117426046-1087c380-af41-11eb-962d-2b7715047862.png)

### Actual behavior
The Forum link is not active for the Active challenges for all track

### Steps to reproduce the problem
-Create the challenge in the development track
-Active the challenge
-see forum link

### Screenshot/screencast
Attach or link a resource.
![image](https://user-images.githubusercontent.com/62358241/117426134-2b5a3800-af41-11eb-921e-11ed67a81174.png)

--

#### Environment
- OS: Windows
- Browser (w/version): All browser
- User role (client, copilot or manager): copilot 
- Account used:

**Comment by rootelement** [comment]
Forums aren't created for tasks. This is not an issue. The only issue is maybe that WM shouldn't show the forum link for a task.

**Comment by coderhacker** [comment]
Update: Forum link is not showing on Production 
![image](https://user-images.githubusercontent.com/62358241/119317853-311c8100-bc96-11eb-9899-65a296981555.png)

**Comment by lakshmiathreya** [comment]
cc @rootelement @ThomasKranitsas @vikasrohit

**Comment by coderhacker** [comment]
Updating video for both env.


https://user-images.githubusercontent.com/62358241/119335845-82367000-bcaa-11eb-9852-12a2f064056d.mp4

**Comment by coderhacker** [comment]
This is fixed on production 
![image](https://user-images.githubusercontent.com/62358241/123781150-8715c180-d8f1-11eb-8422-0fac966927ed.png)
