### ISSUE TITLE
Prevent activation of challenge when BA associated to the project is not active

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#1154]
Currently a user can activate a challenge even if the BA associated to its project is inactive, though the API returns error when there is no BA associated to the project but it does not return any error if the BA is inactive.
So to prevent over billing, we have to stop user from activating the challenge from the WM if the BA associated is not active. We already couple of endpoints in projects api which provides support to fetch BA details. They are not yet documented in swagger but they exists [here](https://github.com/topcoder-platform/tc-project-service/tree/develop/src/routes/billingAccounts). We need ot use the `GET` endpoint to facilitate this requirement and the required changes in `GET` endpoint are implemented via https://github.com/topcoder-platform/tc-project-service/issues/651.

**Comment by vikasrohit** [comment]
fyi @ajefts

**Comment by coderhacker** [comment]
@vikasrohit could you please share for project id for this. so that I can verify on Dev

**Comment by vikasrohit** [comment]
https://github.com/appirio-tech/connect-app/issues/4380#issuecomment-851441944

**Comment by coderhacker** [comment]
QA Comments: this is failed on dev. I can active the challenge if BA is expired, please see attached failed

https://user-images.githubusercontent.com/62358241/120269431-760f6b80-c2c5-11eb-8eb5-86eedee3cb0f.mp4

 video.

**Comment by vikasrohit** [comment]
thanks @coderhacker for reporting it, I have also noticed the same. It seems during development the [project](https://challenges.topcoder-dev.com/projects/16496/challenges) used for testing has different set of data which caused this requirement to be missed.
Anyway, I have applied a fix, it should be in dev in 10 minutes.

**Comment by coderhacker** [comment]
@vikasrohit This is failed in this case, created a new defect https://github.com/topcoder-platform/work-manager/issues/1158

**Comment by coderhacker** [comment]
Qa comment: This is failed for design and QA track challenge activation, please see the attached video and this defect 1158

https://user-images.githubusercontent.com/62358241/120299660-d49a1100-c2e8-11eb-8506-35b3c46d809e.mp4

**Comment by vikasrohit** [comment]
@coderhacker this seems to be `always there` issue where somehow legacy challenge is not created for a v5 challenge.
So in those cases, Launch button would be disabled. There is a tooltip for that as well over the button itself and if you consistently see that legacy challenge is not being created for a design challenge in dev, it might be something which product team is working on to have pure v5 design challenges just like pure v5 tasks. It does not have any correlation with Billing Account changes that we are testing here.

**Comment by coderhacker** [comment]
Thanks for the update @vikasrohit.  this is passed with known issue 1158

**Comment by drasticdpk** [comment]
Verified on prod 
**Reference:**

Used Project : https://challenges.topcoder.com/projects/24944/challenges 

![image](https://user-images.githubusercontent.com/25297859/120639595-3e551f00-c491-11eb-9390-01dd29a8bfbf.png)

![image](https://user-images.githubusercontent.com/25297859/120639859-8c6a2280-c491-11eb-8ade-f75442087e1e.png)
