### ISSUE TITLE
Issue with challenge that was created without a billing account

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/work-manager#1160]
### Expected behavior
The Work Manager should let the API decide if it can add the billing account and activate the challenge or not.

### Actual behavior
Currently, if I create a challenge on a project without a billing account or an expired one and then add/activate the BA and try to activate the challenge, the Work Manager simply doesn't let me activate it.

### Steps to reproduce the problem
- Create a challenge on a project without BA
- Add/activate the BA on the project
- Try to activate the challenge

### Screenshot/screencast
<img width="1553" alt="Screenshot 2021-06-07 at 1 06 21 PM" src="https://user-images.githubusercontent.com/4612921/120998938-38ad5100-c791-11eb-8742-709e831f4538.png">

As you can see in the screenshot, there's no call to the backend. The Work Manager simply decided to not let me activate the challenge as it does not contain the BA information.

**Comment by vikasrohit** [comment]
@ThomasKranitsas it is not simply decided to net let you activate the challenge, it is determining based on BA. It makes a call to determine if the BA is active or not. If there is no BA, obviously BA is not active right, and user should not be allowed to activate the challenge.
this was done with the release https://github.com/topcoder-platform/work-manager/releases/tag/v0.9.0
