### ISSUE TITLE
Work Manager: Show registrants/submissions on WM challenge page

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#1167]
As we are showing count of registrants and submissions in Challenge listing page, we should show the same somewhere on the challenge view page.

**Comment by coderhacker** [comment]
@vikasrohit how to verify this issue, could you please provide more information because I am unable to verify these changes due this regression issue https://github.com/topcoder-platform/work-manager/issues/1198

**Comment by vikasrohit** [comment]
@coderhacker we have combined this issue with #1166 and #1169 i.e. you would see the registrants and submissions counts on their respective tabs on Challenge details page. This serves the original purpose of the issue.

**Comment by coderhacker** [comment]
@vikasrohit  both issues fixed now on  production  #1166 and #1169 , so closing this ticket
