### ISSUE TITLE
[$20] WM: overlaping title with button on View challenges page 

### ISSUE THREAD

**Issue by coderhacker** [topcoder-platform/work-manager#1195]
### Expected behavior
The title should be not overlapped with the button

### Actual behavior
Describe.
View any challenges or tasks or F2F page. see the title is overlapping with cancel button

Please see attached screenshot for the issue 
### Screenshot/screencast
Attach or link a resource.
![image](https://user-images.githubusercontent.com/62358241/123271033-0dab5700-d51e-11eb-9682-53646d9b5202.png)
![image](https://user-images.githubusercontent.com/62358241/123274282-0174c900-d521-11eb-881b-2d5c5da8cba8.png)
![image](https://user-images.githubusercontent.com/62358241/123274470-2c5f1d00-d521-11eb-9660-a4fc2b91b0e6.png)

--

#### Environment
- OS: WIndow 10 
- Browser (w/version): Chrome latest
- User role (client, copilot or manager): copilot 
- Account used:

**Comment by vikasrohit** [comment]
This should be fixed with #1203 and #1204

**Comment by phead198708** [comment]
Hi, @yoution  do the same with ticket https://github.com/topcoder-platform/work-manager/issues/1165

Keep the online review link, and remove the connect link.

**Comment by yoution** [comment]
@phead198708 please assign to me

**Comment by yoution** [comment]
@phead198708 please review https://github.com/topcoder-platform/work-manager/pull/1209

**Comment by coderhacker** [comment]
Dev Failed: This is not properly fixed 
![image](https://user-images.githubusercontent.com/62358241/125078306-d45b1580-e0df-11eb-9c70-91900eb433bf.png)

**Comment by yoution** [comment]
@phead198708 please review https://github.com/topcoder-platform/work-manager/pull/1213
![image](https://user-images.githubusercontent.com/3863914/125153213-c6130500-e184-11eb-9167-98b83d76fbe8.png)

**Comment by vikasrohit** [comment]
@coderhacker deployed to dev for reverification.

**Comment by coderhacker** [comment]
This is fixed on dev 
![image](https://user-images.githubusercontent.com/62358241/125247688-d9eb7200-e310-11eb-8198-7f5243b8d650.png)

**Comment by coderhacker** [comment]
This is passed in production 
![image](https://user-images.githubusercontent.com/62358241/125300833-05d61a00-e348-11eb-89df-a72825e5e64c.png)
