### ISSUE TITLE
[$10] WM: Extra space is coming for the confirmation message box

### ISSUE THREAD

**Issue by coderhacker** [topcoder-platform/work-manager#1196]
### Expected behavior
Extra space should not display for the  confirmation message box

### Actual behavior
WM: Extra space is coming for the  confirmation message box

### Steps to reproduce the problem
Please see attached screenshot for the issue

### Screenshot/screencast
Attach or link a resource.
![image](https://user-images.githubusercontent.com/62358241/123276941-47329100-d523-11eb-9858-ecb6a1c0dca7.png)

--

#### Environment
- OS: Windwos 10
- Browser (w/version): Chrome
- User role (client, copilot or manager): copilot 
- Account used:

**Comment by yoution** [comment]
@phead198708 please assign to me

**Comment by yoution** [comment]
@phead198708 
the extra space happens is the rightside word too long，then it wrap to next line
![image width="100"](https://user-images.githubusercontent.com/3863914/124208040-57490280-db19-11eb-939a-27b4df01b70d.png)
![image width="100"](https://user-images.githubusercontent.com/3863914/124208066-63cd5b00-db19-11eb-98ca-856255ae3db0.png)

**Comment by yoution** [comment]
@phead198708 please review https://github.com/topcoder-platform/work-manager/pull/1211

**Comment by coderhacker** [comment]
Dev Passed 
![image](https://user-images.githubusercontent.com/62358241/125077535-d5d80e00-e0de-11eb-9efe-8150d15e0b86.png)
![image](https://user-images.githubusercontent.com/62358241/125077561-dec8df80-e0de-11eb-8f14-2a1259b2352b.png)

**Comment by coderhacker** [comment]
This is fixed on proudction 
![image](https://user-images.githubusercontent.com/62358241/125296996-7713ce00-e344-11eb-8187-b0133b008188.png)
