### ISSUE TITLE
WM: Challenge is moving in draft status after sometime and also register button is not activating

### ISSUE THREAD

**Issue by coderhacker** [topcoder-platform/work-manager#1198]
### Expected behavior
Describe.
The challenge should be in active tab if the challenge is activated, this should not move in draft tab. and register button should be active if challenge is start
### Actual behavior
Challenge is moving in draft status tab after some time and also register button is not activating.

### Steps to reproduce the problem
Please see attached video

https://user-images.githubusercontent.com/62358241/123405252-418e8700-d5c7-11eb-8ad3-74fda851d19d.mp4

https://www.topcoder-dev.com/challenges/28e4690b-9062-4baa-ab6e-9384a5e780a5
--

#### Environment
- OS: Windows 10
- Browser (w/version): all browsers
- User role (client, copilot or manager): copilot 
- Account used:

**Comment by coderhacker** [comment]
QA Comments: I have verified today as well on the dev environment. it's not working as expected

https://user-images.githubusercontent.com/62358241/123583713-b814ca00-d7fd-11eb-8dda-a617b9d42856.mp4

CC @lakshmiathreya

**Comment by vikasrohit** [comment]
Ok @coderhacker. We can ignore this for now. we need to use existing active challenges if we have to test something on active challenges for now because there must be something bad with other components of the application but there is nothing which is changed in this front end release which can impact challenge activation. But still we would double check it on production after prod release and in case we find something actually bad with the release which making this issue, we would immediately revert the release.
fyi @lakshmiathreya

**Comment by coderhacker** [comment]
Production Update: This is not working production as well, please find an attached the video for production

https://user-images.githubusercontent.com/62358241/123625192-22912e80-d82d-11eb-8eb4-ae5706a08401.mp4

 failed
CC @lakshmiathreya

**Comment by vikasrohit** [comment]
Challenge seems to be active https://challenges.topcoder.com/projects/24943/challenges/cdff09fc-bc20-4b25-8e86-7d83ffe214ca/view

**Comment by coderhacker** [comment]
This is passed on production: 

https://user-images.githubusercontent.com/62358241/123632719-e31b1000-d835-11eb-879a-72c759e5141c.mp4

**Comment by coderhacker** [comment]
This is not fixed on Dev Environment

https://user-images.githubusercontent.com/62358241/124598466-46362380-de82-11eb-8d55-2b39ed10e24c.mp4

**Comment by coderhacker** [comment]
Here is the latest finding for this bug.

 WM start  date and status active  is not syncing with the newly created challenge 
please see attached video:

https://user-images.githubusercontent.com/62358241/124758100-e015d300-df4b-11eb-94ad-c5f62e926ca1.mp4

**Comment by coderhacker** [comment]
CC @lakshmiathreya

**Comment by coderhacker** [comment]
This is still not fixed on dev , Here is an updated video for dev 

https://user-images.githubusercontent.com/62358241/126147195-3209b4d0-7a57-47c1-99cf-e5cef228d39b.mp4

**Comment by coderhacker** [comment]
https://challenges.topcoder-dev.com/projects/16804/challenges/f5b63079-5bab-4088-bb1a-6cb81e54ce0b/view
https://challenges.topcoder-dev.com/projects/16804/challenges/4c45cfb6-feb6-461a-8844-0a1422850aac/view

**Comment by lakshmiathreya** [comment]
@rootelement need your help pls ...

**Comment by ThomasKranitsas** [comment]
@lakshmiathreya it seems like the call to the V4 API from the legacy challenge processor is timing out.
We are restarting the service and this should fix the issue.

below is the log from the legacy challenge processor:

```
error: Error: createChallenge - Calling POST v4 API Failed.
      Request URL: https://api.topcoder-dev.com/v4/challenges?filter=skipForum=true
      Params: {"param":{"subTrack":"BUG_HUNT","name":"1198-QAtrack","reviewType":"COMMUNITY","projectId":24283,"status":"Draft","confidentialityType":"public","submissionGuidelines":"Please read above","submissionVisibility":true,"milestoneId":1,"detailedRequirements":"\ttesting","registrationStartsAt":"2021-07-19T09:32:00.000Z","registrationEndsAt":"2021-07-24T09:32:00.000Z","registrationDuration":432000000,"submissionEndsAt":"2021-07-24T09:32:00.000Z","submissionDuration":432000000,"checkpointSubmissionStartsAt":null,"checkpointSubmissionEndsAt":null,"checkpointSubmissionDuration":null,"numberOfCheckpointPrizes":0,"checkpointPrize":0,"prizes":[1],"technologies":[{"id":27603959,"name":"Other","description":"Other","status":{"id":1,"description":"Active"}}],"platforms":[{"name":"Cloud Foundry","id":5}]}}
      Error: {"status":504,"response":{"req":{"method":"POST","url":"https://api.topcoder-dev.com/v4/challenges?filter=skipForum=true","data":{"param":{"subTrack":"BUG_HUNT","name":"1198-QAtrack","reviewType":"COMMUNITY","projectId":24283,"status":"Draft","confidentialityType":"public","submissionGuidelines":"Please read above","submissionVisibility":true,"milestoneId":1,"detailedRequirements":"\ttesting","registrationStartsAt":"2021-07-19T09:32:00.000Z","registrationEndsAt":"2021-07-24T09:32:00.000Z","registrationDuration":432000000,"submissionEndsAt":"2021-07-24T09:32:00.000Z","submissionDuration":432000000,"checkpointSubmissionStartsAt":null,"checkpointSubmissionEndsAt":null,"checkpointSubmissionDuration":null,"numberOfCheckpointPrizes":0,"checkpointPrize":0,"prizes":[1],"technologies":[{"id":27603959,"name":"Other","description":"Other","status":{"id":1,"description":"Active"}}],"platforms":[{"name":"Cloud Foundry","id":5}]}},"headers":{"content-type":"application/json","authorization":"Bearer <token>","accept":"application/json"}},"header":{"server":"awselb/2.0","date":"Mon, 19 Jul 2021 13:48:56 GMT","content-type":"text/html","content-length":"132","connection":"close"},"status":504,"text":"<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n"}}
      Token: "<token>"
    at createChallenge (/app/src/services/ProcessorService.js:570:11)
```

**Comment by rootelement** [comment]
There is a strange issue with Challenge V4 API. We fixed the code but Guna is now fixing the deploy. Once that's done, we'll re-test.

**Comment by lakshmiathreya** [comment]
Status remains Active now - Registration continues to be block due to apparent Registration date Sync issue - Setting QA Pass for Dev here and logged a new Issue to track that https://github.com/topcoder-platform/work-manager/issues/1219
