### ISSUE TITLE
[$10] Better alignment and spacing for project title and view project link

### ISSUE THREAD

**Issue by coderhacker** [topcoder-platform/work-manager#1202]
### Expected behavior
Clean up the top section a bit.

Move the project name to the left.

Remove the “View Project in Direct” button. They can get there from the Connect Project if needed.

Change the big “View in Connect” button to a simple text link after the Project Name. Something like Project Name (view project)
### Actual behavior
![image](https://user-images.githubusercontent.com/62358241/123642761-49596000-d841-11eb-9236-d136a164d3cf.png)
### Steps to reproduce the problem
Go project challenge page see attached screenshot for issue

**Comment by yoution** [comment]
@phead198708 please assign to me

**Comment by phead198708** [comment]
I see some error message overlapped also.

![View Details 2021-07-01 15-16-31](https://user-images.githubusercontent.com/85940583/124082713-9f1b4b80-da7f-11eb-8d09-97bb65f7dee9.png)

**Comment by yoution** [comment]
@phead198708 please review https://github.com/topcoder-platform/work-manager/pull/1210

**Comment by coderhacker** [comment]
This is not fixed properly, please find below the issue

1. 
![image](https://user-images.githubusercontent.com/62358241/125056455-e0d27480-e0c5-11eb-9ee6-3eb984b53071.png)

**Comment by vikasrohit** [comment]
@coderhacker are you suggesting `Online Review` to not break into two lines?

**Comment by coderhacker** [comment]
@vikasrohit  Online Review should not break this should be one line like this 
![image](https://user-images.githubusercontent.com/62358241/125088596-33725780-e0eb-11eb-85d6-35a6b99b0f1c.png)

**Comment by yoution** [comment]
@phead198708 please review https://github.com/topcoder-platform/work-manager/pull/1213
![image](https://user-images.githubusercontent.com/3863914/125153250-fd81b180-e184-11eb-8c25-5bc1ae86b63a.png)

**Comment by vikasrohit** [comment]
@coderhacker deployed to dev for reverification.

**Comment by coderhacker** [comment]
This is not fixed properly online review touching delete button 
![image](https://user-images.githubusercontent.com/62358241/125247334-73feea80-e310-11eb-96dc-05c55ba1fbf9.png)

**Comment by vikasrohit** [comment]
@coderhacker this is okay, lets pass it. We are not going to see this long challenge name practically, and if we do, we don't really care about that slight alignment issue.

**Comment by coderhacker** [comment]
This is passed on dev as per the above suggestion. a raised new defect https://github.com/topcoder-platform/work-manager/issues/1214 for long title handle

**Comment by coderhacker** [comment]
This is passed on production : 
![image](https://user-images.githubusercontent.com/62358241/125290496-ffdb3b80-e33d-11eb-9e31-a397ad09c9f7.png)
