### ISSUE TITLE
[$10] Read View - Move title to the left and convert Direct and Online Review to links instead of Buttons

### ISSUE THREAD

**Issue by coderhacker** [topcoder-platform/work-manager#1203]
### Expected behavior
Clean up the top section a bit.

Move the project name to the left.

Remove the “View Project in Direct” button. They can get there from the Connect Project if needed.

Change the big “View in Connect” button to a simple text link after the Project Name. Something like Project Name (view project)
### Actual behavior
![image](https://user-images.githubusercontent.com/62358241/123643004-92111900-d841-11eb-8387-9f4def913a76.png)
### Steps to reproduce the problem
Go project challenge view page see attached screenshot for issue

**Comment by yoution** [comment]
@phead198708 please assign to me

**Comment by yoution** [comment]
@phead198708 please review https://github.com/topcoder-platform/work-manager/pull/1209

**Comment by coderhacker** [comment]
This is passed on proudction 
![image](https://user-images.githubusercontent.com/62358241/125296614-184e5480-e344-11eb-899d-09f46f1ba1ab.png)
