### ISSUE TITLE
[$20] Edit View - Move title to the left and convert Direct and Online Review to links instead of Buttons

### ISSUE THREAD

**Issue by coderhacker** [topcoder-platform/work-manager#1204]
### Expected behavior
Clean up the top section a bit.

Move the project name to the left.

Remove the “View Project in Direct” button. They can get there from the Connect Project if needed.

Change the big “View in Connect” button to a simple text link after the Project Name. Something like Project Name (view project)
### Actual behavior
![image](https://user-images.githubusercontent.com/62358241/123643385-f0d69280-d841-11eb-8340-7be87cff93d7.png)

### Steps to reproduce the problem
Go project challenge edit page see attached screenshot for issue

**Comment by yoution** [comment]
@phead198708 please assign to me

**Comment by yoution** [comment]
@phead198708 
1. how about this one? also remove it?
![image](https://user-images.githubusercontent.com/3863914/124125700-82e1d380-daac-11eb-90ab-354524503c2c.png)

2.how about this case? if change button to  text link, how to show this disabled style
![image](https://user-images.githubusercontent.com/3863914/124126019-cf2d1380-daac-11eb-8964-7c6faffea685.png)

**Comment by yoution** [comment]
@phead198708 please review https://github.com/topcoder-platform/work-manager/pull/1209

**Comment by vikasrohit** [comment]
@yoution 
1. Lets keep those links for now
2. I guess we would show just the plain text without it being hyperlink. That would make the text grey or black colored instead of blue hyperlink. That should give enough hint to the user, further we can still keep the tooltip.

**Comment by coderhacker** [comment]
This is fixed  on dev
![image](https://user-images.githubusercontent.com/62358241/125076390-7af1e700-e0dd-11eb-892f-59e4a7155689.png)

**Comment by coderhacker** [comment]
This is passed on production 
![image](https://user-images.githubusercontent.com/62358241/125295191-9d386e80-e342-11eb-8df7-7abfc547f077.png)
