### ISSUE TITLE
WM: Copilot is not displaying and Getting console error and UI breaking 

### ISSUE THREAD

**Issue by coderhacker** [topcoder-platform/work-manager#1235]
### Expected behavior
Edit page should be responsive and there should be no console error, It should be working properly. 
### Actual behavior
Copilot is not displaying and Getting console errors and UI breaking, please see attached screenshot

1. UI breaking
2. Console error coming.
3. Copilot is not showing.

### Steps to reproduce the problem
- Go to this page https://challenges.topcoder-dev.com/projects/18796/challenges/7c13d4fc-e06b-467c-8cb5-26af23e8271b/edit
- See attached screenshot

### Screenshot/screencast
Attach or link a resource.
![image](https://user-images.githubusercontent.com/62358241/133797419-bb98c971-324d-474f-903f-8f42a956bc55.png)

--

#### Environment
- OS: Windows
- Browser (w/version): Chrome and all the latest browsers
- User role (client, copilot or manager): copilot 
- Account used:  copilot

**Comment by ThomasKranitsas** [comment]
That's because the API doesn't include the member information. Looks like a bad data issue to me
