### ISSUE TITLE
WM expects review scores to be numbers while the API response includes strings

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/work-manager#1266]
### Expected behavior
The WM should parse the score first before executes `.tofixed()`

### Actual behavior
Currently it just throws an error

### Steps to reproduce the problem
Example challenge: https://challenges.topcoder.com/projects/29962/challenges/74c9ea5d-62f5-4168-8f2e-f05d2694988a/view

### Screenshot/screencast
<img width="1509" alt="Screenshot 2022-01-12 at 1 15 22 PM" src="https://user-images.githubusercontent.com/4612921/149130175-ad1cbcc1-a403-45fd-9365-7793c92c07cb.png">

**Comment by ThomasKranitsas** [comment]
fixed

**Comment by coderhacker** [comment]
This is working fine on production 
![image](https://user-images.githubusercontent.com/62358241/150339108-e0e63830-9669-4e42-ae11-5203399147e0.png)
