### ISSUE TITLE
Challenge timeline for Self Service challenges

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/work-manager#1291]
The challenge timeline for self service challenges must be set based on  the number of pages, devices the suer has selected.
At present the challenge timeline seems to be incorrect

<img width="1244" alt="Screenshot 2022-01-28 at 1 51 28 PM" src="https://user-images.githubusercontent.com/58783823/151512822-191549e8-d4ea-4a24-ab6e-c870a47f3a6c.png">

Challenge timeline updated once registration phase opened
<img width="1244" alt="Screenshot 2022-01-28 at 2 38 28 PM" src="https://user-images.githubusercontent.com/58783823/151518795-0b2b918a-d0c8-4d78-a2eb-be0a7ae392b9.png">

**Comment by sdgun** [comment]
Verified in Dev,  in some challenges it shows 6 days in challenge timeline when WR is 5 days.

Example challenge: https://www.topcoder-dev.com/challenges/716c48e8-c52c-4192-8387-a149ac8deec9?tab=details
SS: https://platform.topcoder-dev.com/self-service/work-items/716c48e8-c52c-4192-8387-a149ac8deec9?tab=details
