### ISSUE TITLE
Unable to access OR for Design / QA challenges

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/work-manager#1295]
Unable to access OR for Design challenges

example:
https://challenges.topcoder-dev.com/projects/17090/challenges/25b825c4-2a38-4e19-ae9e-9ce6a2f34329/view
<img width="1434" alt="Screenshot 2022-01-31 at 10 41 29 AM" src="https://user-images.githubusercontent.com/58783823/151742144-3e9e4c8c-f616-43c4-a682-cf0e52602342.png">

**Comment by codejamtc** [comment]
Today I have created two QA challenges and can experience the same issue above
- https://challenges.topcoder-dev.com/projects/17090/challenges/6670f6d7-70b9-4f32-a9ec-4b3e211daab8/view
- https://challenges.topcoder-dev.com/projects/17090/challenges/b7d4b282-942b-4f23-bfae-a3ce90e501da/view

**Comment by SathyaJayabal** [comment]
@ThomasKranitsas , we tested again, and saw the OR logs with @Gunasekar-K 's help.

Here is the error from the log:
`actualEndDate can not before actualStartDate`

**Comment by SathyaJayabal** [comment]
This works in PROD , except  for https://github.com/topcoder-platform/work-manager/issues/1299
