### ISSUE TITLE
User can't register to a challenge

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#1297]
**Challenge 02: Dev**

- https://www.topcoder-dev.com/challenges/f6750d1d-aaa4-4fe9-ad24-83dcc9e589d7
- https://software.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30060729
- https://challenges.topcoder-dev.com/projects/17090/challenges/f6750d1d-aaa4-4fe9-ad24-83dcc9e589d7/view

I tried with 4 different users and same problem is there
- TopConnCustomer  :x:
- TCConManager  :x:
- TCConnCopilot  :x:
- copilot_codejam :x:
- Jcori  :ok:

https://user-images.githubusercontent.com/42398485/151916843-00bfdbd2-866e-4d52-ad74-3147d9c558e0.mp4

![bandicam 2022-02-01 10-52-27-647](https://user-images.githubusercontent.com/42398485/151916849-79a9cdaa-7f7e-4f10-8504-7e9fe63a98b2.jpg)

**Challenge 02: DS**

- https://challenges.topcoder-dev.com/projects/17090/challenges/9604f642-8bda-43df-96fe-dfc54818b058/view
- https://www.topcoder-dev.com/challenges/9604f642-8bda-43df-96fe-dfc54818b058

https://user-images.githubusercontent.com/42398485/151920151-21331f05-3258-4db1-bb4b-bc2bc2ae9011.mp4

**Comment by SathyaJayabal** [comment]
verified on dev

https://user-images.githubusercontent.com/58783823/152182689-f5970908-e907-4ba9-a271-b541b8b1bd2a.mov

**Comment by SathyaJayabal** [comment]
verified on prod
