### ISSUE TITLE
503 error when trying to approve/reject self service challenges 

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/work-manager#1302]
### Expected behavior
Should be able to reject the SS challenges

### Actual behavior
503 error when trying to reject SS challenges 

### Steps to reproduce the problem
- Go to Work manager
- Try to reject a self service challenge

### Screenshot/screencast

https://user-images.githubusercontent.com/4592712/152726808-6c8a7696-dd7b-45f3-877c-b3271c1ca9eb.mp4

**Comment by ThomasKranitsas** [comment]
503 means service unavailable. Perhaps a service was down at the time you tried. Can you please retest?
![Uploading Screenshot 2022-02-07 at 2.07.06 PM.png…]()

**Comment by sdgun** [comment]
Verified in Dev, this issue cannot be reproduced anymore.
