### ISSUE TITLE
Duration saving in Work Manager

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1370]
### Expected behavior
The user should be able to:

1.  Enter a duration time into any phases that aren't closed yet.  If registration hasn't started, the start time *and* the duration can be set.  For other phases, just the duration can be set
2.  Phases start one right after the other, so the start time of a phase should be the end time of the previous phase
3.  You can compare the work manager functionality with the phase functionality in Online Review - they should work similarly.
4.  When a user updates the hours, they should be saved and available exactly as the user entered them. 

### Actual behavior

Currently, the durations can be edited more or less appropriately, but when saving and reloading, the values aren't being persisted properly.  A video is below

### Steps to reproduce the problem

See the video here: https://www.dropbox.com/s/limn3vkyt4rrth8/Screen%20Recording%202022-04-08%20at%202.03.31%20pm.mov?dl=1

The durations are edited appropriately, but after saving / reloading they aren't being saved correctly.  The frontend Javascript code is sending incorrect values to the `phases` array of the challenge when updating.

The phase durations are in hours in the UI, but the API expects seconds, so make sure to do that conversion before sending

### Screenshot/screencast

https://www.dropbox.com/s/limn3vkyt4rrth8/Screen%20Recording%202022-04-08%20at%202.03.31%20pm.mov?dl=1

#### Environment
- User role (client, copilot or manager): Login to `challenges.topcoder-dev.com` with `jcori`/ `appirio123`

**Comment by sdgun** [comment]
Verified in production.
