### ISSUE TITLE
Error when attempting to change start of registration date on new challenge

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1375]
### Expected behavior
The user should be able to:

1.  Enter a duration time into any phases that aren't closed yet.  If registration hasn't started, the start time *and* the duration can be set.  For other phases, just the duration can be set
2.  Phases start one right after the other, so the start time of a phase should be the end time of the previous phase
3.  You can compare the work manager functionality with the phase functionality in Online Review - they should work similarly.
4.  When a user updates the hours, they should be saved and available exactly as the user entered them. 

### Actual behavior

Currently, when setting up a new challenge, if the user adjusts the start date of the registration phase, the submission phase isn't updating appropriately and the duration is getting messed up and the user can't save the draft

https://www.dropbox.com/s/1q0tk7ssai8txa2/vid.mp4?dl=1

#### Environment
- User role (client, copilot or manager): Login to `challenges.topcoder-dev.com` with `jcori`/ `appirio123`

**Comment by 52cs** [comment]
Two question:
1. Is the start time of submission is the end time of registration?
2. If the registration hasn't started, can I change the start time of submission?

**Comment by jmgasper** [comment]
1.   No, submission and registration start at the same time
2.  No, submission will start at the start of registration

**Comment by sdgun** [comment]
Verified in production.
