### ISSUE TITLE
Add billing account start / end dates and status to project overview

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1403]
### Expected behavior
Currently, copilots don't have visibility into the start and end dates of billing accounts, so they only know when a billing account has expired when they attempt to put through a payment or launch a challenge, which can lead to delays while the billing account is renewed.  This small change will expose some properties of the billing account to the main project screen in Work Manager, ensuring that copilots can plan accordingly.

We will add a `Billing Account: {status}  Start Date {start date}  End Date {end date}` line of text underneath the project title, above the tabs for the challenges.  This text should be in a normal font, **not** a header / bold font like the project title.

### Error state

If the billing account status is not active (`active==false`), we should show the status as `INACTIVE` in bold / red to ensure that the copilot knows there's a billing account problem.

### API call

The data has to be loaded asynchronously because it requires a separate REST call.  Don't wait for the call before showing the rest of the details on the screen.

The call should be something like `GET https://api.topcoder-dev.com/v5/projects/21827/billingAccount`, where `21827` is the ID of the project.

The response will look like this:

```
{
    "tcBillingAccountId": 80000942,
    "active": true,
    "startDate": "2022-07-20",
    "endDate": "2022-08-19"
}
```

### Screenshot/screencast
<img width="1601" alt="Screen_Shot_2022-07-22_at_3_08_43_pm" src="https://user-images.githubusercontent.com/21790/180367460-f98d3ecd-ea01-4ce6-bbb3-ce98017d5c05.png">

**Comment by jplew** [comment]
Hi, I posted a question here: https://discussions.topcoder.com/discussion/20129/cant-login?new=1
