### ISSUE TITLE
Wrong status shown for billing account

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1412]
Seen in production:

### Problem

Today for the Timeline Wall project the billing account was showing `IN_REVIEW`

It looks like the Connect Project was In Review, but the Billing Account was active.

![Screenshot_6](https://user-images.githubusercontent.com/21790/187808939-0c5de846-e4d6-4013-898d-82543199246d.png)

### Solution

The BA should only show two status - "ACTIVE" or "INACTIVE".

**Comment by sdgun** [comment]
Verified in Prod with available projects.
