### ISSUE TITLE
Enable on/off toggle for dashboard creation

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1418]
Recently, we made a change to the community app to show the data dashboard for any challenge in the `Data Science` challenge track:

https://github.com/topcoder-platform/community-app/issues/6632

After discussion with Data Science copilots, we have determined that this dashboard may not always be needed, so we are going to add checkbox to turn this on / off

### UI

1.  When the user selects `Work Type` of `Data Science`, we will show an additional option underneath `Work Name`
2. The prompt (in the same alignment and font as Work Name) should say "Show Data Dashboard".

The value will just be a checkbox, aligned with the text fields.

![SCR-20220923-igt](https://user-images.githubusercontent.com/21790/191886953-53d619f0-d5a0-4852-a175-900b89e72c4c.png)

### Default

By default, this checkbox should be **checked**

### Data

The new flag will be added to the `metadata` array of the challenge object.  The name of the flag will be "show_data_dashboard".  The value will just be `true` (checkbox checked), or `false` (checkbox unchecked)

### Example

```
{
    "metadata":[
        {
            "name":"show_data_dashboard", 
            "value":true
        },
    ]
}
```

**Comment by sdgun** [comment]
Verified in Prod.

![image](https://user-images.githubusercontent.com/4592712/195009582-1c40ba90-731a-43ec-94f4-694872c00440.png)

Challenge: https://www.topcoder.com/challenges/d4baf6b7-651e-4c19-a294-b3b0bbc12151?tab=dashboard
