### ISSUE TITLE
Alphabetise Work Format drop down

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1419]
### Problem

Topcoder has requested that we sort the Work Format drop down on the challenge screen in alpha order, A-Z.

### Screenshot

![SCR-20221004-hbp](https://user-images.githubusercontent.com/21790/193715143-95c161c7-3acb-4612-8da9-da85c04822c4.png)

**Comment by sdgun** [comment]
Verified in Prod.

![image](https://user-images.githubusercontent.com/4592712/195007604-b43965e5-99e5-42fe-aacc-fba824728499.png)
