### ISSUE TITLE
New flow for the Data Dashboard 

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1420]
### Expected behavior
We added a toggle for `Use data dashboard` that adds some metadata to the challenge object that tells the community app to show the data dashboard.

We want to restrict this to three combinations of work type and format:

1.  `Data Science` / `Challenge`
2.  `Development` / `Marathon Match`

### Actual behavior
1. Currently, we do not show the toggle when `Development` / `Marathon Match` is selected
2. Additionally, we show this for *all* work formats if `Data Science` is selected for the Work Type, which is also incorrect

### Screenshots
![SCR-20221004-hk4](https://user-images.githubusercontent.com/21790/193716311-d7348e20-c8e1-4b57-8d61-44b9cead6453.png)

![SCR-20221004-hkc](https://user-images.githubusercontent.com/21790/193716320-199748e8-7c3c-40b6-a9d1-9037505fdc1e.png)

**Comment by sdgun** [comment]
Verified with Data science challenge.

![image](https://user-images.githubusercontent.com/4592712/195009489-14348c1a-acd4-4cf5-a6b7-c16bd5ed77f6.png)
