### ISSUE TITLE
Pagination issues

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1440]
### Issue 1

Can see a pagination issue. When we go to page 3 or 4 and then change the per page values; sometimes we can’t see data  

### Issue 2

Also after we go to the last page and change the per page values and  move forward will reset the per page values to 10  

https://user-images.githubusercontent.com/21790/200418601-1a520dbd-e984-47fd-b11b-9b7064d58a47.mp4

**Comment by jjaijg** [comment]
HI @jmgasper, Can I work in this issue?

**Comment by jmgasper** [comment]
> HI @jmgasper, Can I work in this issue?

Yes, there's an open F2F for this one.

**Comment by jjaijg** [comment]
I tried looking there, but I could see only the "Topcoder Work Manager - Metadata not saving properly" F2F. 

That's why I commented here. If you don't mind, if there is already F2F created for this, could you please share it?

**Comment by jmgasper** [comment]
> I tried looking there, but I could see only the "Topcoder Work Manager - Metadata not saving properly" F2F.
> 
> That's why I commented here. If you don't mind, if there is already F2F created for this, could you please share it?

https://www.topcoder.com/challenges/6d424f33-3339-4cd6-a9f5-4ceb94c62ab1

**Comment by jjaijg** [comment]
I am unable to register to this F2F.
![image](https://user-images.githubusercontent.com/22398917/205220595-7ae93a16-51a0-4e4e-913c-ba82eefad2c6.png)

**Comment by jmgasper** [comment]
I have opened up a Topcoder support ticket to investigate.
