### ISSUE TITLE
Read-only rights

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1466]
REF: https://topcoder.atlassian.net/browse/PROD-3805

User is able to edit a challenge with read only access on the project.

Steps to reproduce the issue

* Go to https://challenges.topcoder-dev.com/ 
* Choose a project and add a member with read only access
<img width="1342" alt="Screenshot 2023-01-20 at 1 56 19 PM" src="https://user-images.githubusercontent.com/21790/214730236-f5127833-9245-48cd-b048-e75b8450bbc4.png">

* Log in with this member 
* Choose a challenge from the project 
* Edit the challenge 

User should not be able to edit the challenge as he doesn’t have access

**Comment by suppermancool** [comment]
@jmgasper done in 
[issue-1466.patch](https://github.com/topcoder-platform/work-manager/files/10506617/issue-1466.patch)

This patch against commit: 064bf79eb5daae8bbfcac13d10d5b416a697d23d
