### ISSUE TITLE
CheckpointSubmission scheduledStartDate not being set

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1475]
### Bug

We're seeing problems with the phases not syncing properly when a two round design challenge is launched.  I tracked this down to the `Checkpoint Submission` phase not being updated with a `scheduledStartDate` properly:

<img width="2420" alt="SCR-20230203-ksl" src="https://user-images.githubusercontent.com/21790/216509735-23193ebf-d412-43bc-aaca-d48faa1d3123.png">

**Comment by suppermancool** [comment]
@jmgasper this is a backend problem. When calling `POST https://api.topcoder-dev.com/v5/challenges` to create a new challenge, the backend does not return `scheduledStartDate` in response

<img width="1425" alt="Screenshot 2023-02-03 at 12 34 32" src="https://user-images.githubusercontent.com/5815182/216520819-630034c6-eed0-4a26-af15-33a9ec25d8cb.png">

**Comment by jmgasper** [comment]
@suppermancool - I'll log this to be fixed in the challenge API.  

In the meantime, can we just make sure the `scheduledStartDate` is sent when we update the challenge via PUT to create the draft please?  That value can just be the value from the form field:

<img width="1388" alt="SCR-20230204-d2w" src="https://user-images.githubusercontent.com/21790/216722645-a0265d3b-ce17-4522-a5da-cc3e48eddeaf.png">
