### ISSUE TITLE
Markdown - Numbered list with content under it doesn't work

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1479]
REF: https://topcoder.atlassian.net/browse/PROD-4048

Adding content under a numbered list, messes up the numbering.

Notice how in the image below, right side Dashboard still has “1.“ in front of it, although it should be “2.“

Note that the markdown editor in the forums allows this and it works correctly.

![image-20230202-181709](https://user-images.githubusercontent.com/21790/216869602-c4e34dbc-0ce5-4fa7-a034-052e71fdabb7.png)

**Comment by jmgasper** [comment]
@suppermancool - I'm not seeing this one working with the new editor, but I think it does work in the forums.  Can you double check please?

**Comment by suppermancool** [comment]
@jmgasper this is a bug of markdown review (not text editor) of both `work manager` and `community app`.

For this, I have to fix this bug in `the community app` and replace the markdown review in `work manager` with the markdown review of `the community app`. Is that ok?

**Comment by jmgasper** [comment]
@suppermancool - Yes, that's OK.  Let me know via email how much work that is so I can adjust payment accordingly.

**Comment by suppermancool** [comment]
@jmgasper

- Work manager: done in [work-manager-issue-1479.patch](https://github.com/topcoder-platform/work-manager/files/10754860/work-manager-issue-1479.patch) (`develop` branch, against commit 85e099b6901e65ab41e72a6fa7b72bdce520086e)

- Community App: done in [community-app-issue-1479.patch](https://github.com/topcoder-platform/work-manager/files/10754894/community-app-issue-1479.patch) (`develop` branch, against commit a7c3e2207dc8a3ce1bc8da30d0c07e18115e5a9b)
