### ISSUE TITLE
Markdown - Implement drag and drop for images / attachments

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1481]
### Expected behavior
The user should be able to drag and drop images / attachments and have them display in the rendered spec, similar to what they can do in the forums.

**Comment by jmgasper** [comment]
@suppermancool - This is now working with images, but not with other file types, like txt or zip files.  Is that something we can enable?

**Comment by suppermancool** [comment]
@jmgasper there is a list of supported files in `allowedFileMimeTypeWithExts` config. but that config is not in `forums-topcoder-editor-plugin` code. now i will add txt and zip in supported files

**Comment by suppermancool** [comment]
@jmgasper done in 
[issue-1481.patch](https://github.com/topcoder-platform/work-manager/files/10740143/issue-1481.patch)

Commit: 11adadb89ee7728b7f696f49fad6ac8bb2161d1b (develop branch)
