### ISSUE TITLE
Ability to open Checkpoint Submission phase later than Registration phase (Frontend)

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1496]
Reported by QA.  Note that this *only* applies to 2 round design challenges, nothing else.  The standard `Submission` phase editing will apply to all other challenge types.

> One thing I noted while testing WM Markdown is that when we have 2 rounds design challenges, we don’t need Submission start time to be editable as in this case the phases will follow based on autopilot regularly, so only Registration and Checkpoint Submission start time should be editable.

![image-20230209-093335](https://user-images.githubusercontent.com/21790/219221955-89f1dd5a-7514-4e86-9aa9-79539e66ed6c.png)

**Comment by jmgasper** [comment]
@suppermancool - One issue found in QA on this one:

Verified in WM, initially only the Registration and Checkpoint Submission phases' start times are enabled and it allows to set an earlier date in Checkpoint Submission start time than the Registration start time. However after some time, the Submission phase start time gets enabled. Challenge: [Work Manager - Topcoder  (log in from jcori user) ](https://challenges.topcoder-dev.com/projects/23080/challenges/7453d951-caa3-4915-8189-9e86e852dd08/edit)

**Comment by suppermancool** [comment]
@jmgasper backend does not return any parameter for checking 2-round challenges. The only way I know for checking this is this condition:
challengeDetails.timelineTemplateId ===  'd4201ca4-8437-4d63-9957-3f7708184b07'

This only work after creating the challenge. After some time the challengeDetails.timelineTemplateId is changed, this will make the above condition fail

Do you know another way for checking if the challenge is 2-round challenge or not?

**Comment by jmgasper** [comment]
@suppermancool - Can we check for a `Checkpoint Submission` phase?  No other timelines other than a 2 round timeline will have that.

**Comment by suppermancool** [comment]
@jmgasper done in 
[work-manager-issue-1496.patch](https://github.com/topcoder-platform/work-manager/files/10917460/work-manager-issue-1496.patch)
This patch against commit d0b8b94d1f19a5540851aaaf6ce487bf7b2c569c (develop branch)
