### ISSUE TITLE
New lines and embedded images

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1497]
Reported in QA:

when I add a new line between text  and image, it’s showing as it’s no line under challenge details (check the screenshots for “image test“+ photo)

![image-20230216-234327](https://user-images.githubusercontent.com/21790/219531610-ac6f9f27-fde4-4d2b-844e-0cbe5df68134.png)

![image-20230216-234313](https://user-images.githubusercontent.com/21790/219531617-0d291bf6-c16b-4e50-9269-13f09a3792f9.png)

**Comment by suppermancool** [comment]
@jmgasper i already resolved this in https://github.com/topcoder-platform/work-manager/issues/1479#issuecomment-1432862784

**Comment by jmgasper** [comment]
@suppermancool - Verified, thanks.
