### ISSUE TITLE
Double clicking a line of text highlights next line

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1500]
@suppermancool - With the latest code, still seeing issues:

Verified in dev. This issue is not fixed. Double clicking a line of text seems to be highlighting the next line too

**Video**

https://user-images.githubusercontent.com/21790/219814701-45b9adb0-be22-4a16-b8ad-15cef98e176f.mp4

**Comment by suppermancool** [comment]
@jmgasper done in 
[work-manager-issue-1500.patch](https://github.com/topcoder-platform/work-manager/files/10773758/work-manager-issue-1500.patch)

This patch again commits `337ef95abd45158191a924f28c204e1a2283d341` (develop branch)
Actually, that is triple-clicking, double-clicking only select words. Triple clicking will select the line, the editor in forum also have this problem
