### ISSUE TITLE
Merge in SSR changes

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1501]
@suppermancool - There were changes to the uninav setup checked into the `universal_nav` branch.  They conflict with recent changes for the `Profiles` / `My Profiles` header update to the `getSubpageConfiguration` method.

Can you check the `universal_nav` branch and merge the changes into `marathon_match_submission_download` please?

**Comment by suppermancool** [comment]
@jmgasper this task is for the community app project, right?

**Comment by suppermancool** [comment]
@jmgasper done in [community-app-issue-1501.patch](https://github.com/topcoder-platform/work-manager/files/10776611/community-app-issue-1501.patch) . this patch again commit 077e2ce17bfe6e25dd162f83e87a90e550ac16db in marathon_match_submission_download branch

Please follow these steps to apply that patch:
1. run `git apply community-app-issue-1501.patch`
2. Commit the changes with this message:
```
Merge branch 'universal_nav' into marathon_match_submission_download

# Conflicts:
# src/shared/containers/TopcoderHeader/index.jsx
# src/shared/utils/url.js
```
4. merge universal_nav -> marathon_match_submission_download
5. find all commits and apply the current changes

**Comment by suppermancool** [comment]
@jmgasper actually I see some problem with the latest code in `universal_nav` branch, but I can resolve it locally. If you see any problem with the merge you may check the latest code in `universal_nav` 

The code in Patch file is almost the same as the latest code in `universal_nav` i resolve the conflict by only adding the top coder handle check in that code(the code that I use to resolve this issue https://github.com/topcoder-platform/community-app/issues/6827)

**Comment by jmgasper** [comment]
@suppermancool - Yeah, this should have been for community app, sorry for the confusion.  I've merged the code and am deploying now.  I'll let you know if I run into issues, thanks.
