### ISSUE TITLE
Tweak "Download All" and "Manage Submissions" layout

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1505]
Topcoder would like to see something like this:

![image-20230223-003743](https://user-images.githubusercontent.com/21790/220796250-7f751657-d16e-463f-8894-8f37375b9abb.png)

**Comment by jmgasper** [comment]
@suppermancool - This looks better, but I'm not seeing a margin to the right of `Download All` on Safari:
<img width="1619" alt="SCR-20230223-stb" src="https://user-images.githubusercontent.com/21790/220872141-ec42fa21-383c-40de-ba8f-2ab3fd4d7c64.png">

**Comment by suppermancool** [comment]
@jmgasper done in 
[work-manager-issue-1505.patch](https://github.com/topcoder-platform/work-manager/files/10812335/work-manager-issue-1505.patch)

This patch against commit ccdb8a3b816e1d33702823571b869043ad685de1 (develop branch)

**Comment by jmgasper** [comment]
Looks good, thanks!
