### ISSUE TITLE
Work Manager- arrow in the selected tab overlaps with the drop down menu that appears on hovering over the customer and talent

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1506]
REF: https://topcoder.atlassian.net/browse/UN-708

Steps

Go to https://challenges.topcoder-dev.com/ 

Hover over customer or talent and see the arrow shown on the drop down

https://user-images.githubusercontent.com/21790/221288458-352b06a3-45fc-4eaa-9cf1-dbe62f8de7aa.mp4

**Comment by suppermancool** [comment]
@jmgasper done in 
[work-manager-issue-1506.patch](https://github.com/topcoder-platform/work-manager/files/10829651/work-manager-issue-1506.patch)

Against commit: 676ef63d32eed294f43e93f7d7147ba9c8e7b2f8
