### ISSUE TITLE
Next date issue in WM

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1521]
@suppermancool - Reported by QA:

I observed that synching is not happening in WM for auto-copilot (where the phases closes by itself), the time it closes is displayed correctly in OR but it is not changing in WM

Note: The changes we made in WM as well as OR are synching fine

### Sample 1

sample: [View Details (topcoder-dev.com)](https://challenges.topcoder-dev.com/projects/23321/challenges/dee0f039-abcd-4784-835e-6c80f99146a2/view)

![image-20230419-054928](https://user-images.githubusercontent.com/21790/233225716-7e080959-5415-46ae-8198-812d1cc97b91.png)

![image-20230419-054945](https://user-images.githubusercontent.com/21790/233225728-3d5acb2a-0994-4a63-ac88-af338c3a2a30.png)

### Sample 2

sample: [View Details (topcoder-dev.com)](https://challenges.topcoder-dev.com/projects/23321/challenges/e5e28a8f-451b-4318-8279-f0eed672d166/view)

![image-20230419-055123](https://user-images.githubusercontent.com/21790/233225777-4334b4ab-8acb-459c-8d99-405bf5c162d7.png)

![image-20230419-055142](https://user-images.githubusercontent.com/21790/233225791-6c7272df-523a-431a-b4a8-69e8ceb441b4.png)

**Comment by suppermancool** [comment]
@jmgasper the backend returns the inconsistent data
For sample 1: backend response for registration phase
```
...
phases: [
...
{
{
      "duration": 3600,
      "scheduledEndDate": "2023-04-19T05:21:02.000Z",
      "actualEndDate": "2023-04-19T05:21:02.000Z",
      "isOpen": false,
      "name": "Registration",
      "phaseId": "a93544bc-c165-4af4-b55e-18f3593b457a",
      "actualStartDate": "2023-04-19T04:18:35.000Z",
      "description": "Registration Phase",
      "id": "1c35bd31-49d2-422a-8fe6-48807be749e1",
      "constraints": [{ "name": "Number of Registrants", "value": 1 }],
      "scheduledStartDate": "2023-04-19T04:18:35.000Z"
    }
}
...
]
...
```

Duration = 3600 seconds => Hour:1 Minutes: 0
but
scheduledEndDate-scheduledStartDate = 63 minutes =>  Hour:1 Minutes: 3

How to know which Duration need to use?

**Comment by suppermancool** [comment]
@jmgasper for sample 2. I'm not sure what is problem. The response from backend does not match with data in OR
 backend response for Submission phase:

```
...
phases: [
...
{
{
      "duration": 1800,
      "scheduledEndDate": "2023-04-18T08:19:00.000Z",
      "isOpen": true,
      "name": "Submission",
      "phaseId": "6950164f-3c5e-4bdc-abc8-22aaf5a1bd49",
      "actualStartDate": "2023-04-18T07:49:24.000Z",
      "description": "Submission Phase",
      "id": "83dc075e-efbe-4efc-b5fd-34729645432e",
      "constraints": [],
      "scheduledStartDate": "2023-04-18T07:49:24.000Z"
    }
}
...
]
...
```

Duration = 1800 seconds => Hour:0 Minutes: 30
scheduledEndDate-scheduledStartDate = 30 minutes =>  Hour:0 Minutes: 30

Both Duration and scheduledEndDate-scheduledStartDate do not match with data in OR

**Comment by jmgasper** [comment]
@suppermancool - Let's change this to use the same display as OR, as long as we aren't changing the fields that should be fine.

**Comment by suppermancool** [comment]
Done in `work-manager-issue-1521.patch` (develop branch)
Best regards,

Diazz.
