### ISSUE TITLE
Self-service tab issues

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1525]
REF: https://topcoder.atlassian.net/browse/PROD-4222

### Issue 1

When doing a search from any user except the admin users in the self service tab, it throws some console errors and a white page. (Ex user - TCConnCopilot / Appirio123)

https://user-images.githubusercontent.com/21790/236993924-8cf458b4-992b-4bd3-b00a-6640f23eff7e.mp4

### Issue 2

Also clicking Reset filters button on the self service tab from a normal user throws below error and it doesn’t reset the filters

https://user-images.githubusercontent.com/21790/236993934-8e1b9928-37d8-44ec-b1fe-5bc2bd90dfe9.mp4

**Comment by suppermancool** [comment]
@jmgasper done in 
[work-manager-issue-1525.patch](https://github.com/topcoder-platform/work-manager/files/11428668/work-manager-issue-1525.patch)
this patch against commit 53858c39f67051551f488e1b6d0ad9a1f88fc78c
