### ISSUE TITLE
Redirect fix

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1527]
REF: https://topcoder.atlassian.net/browse/PROD-4262

### Expected behavior

Redirects from https://challenges.topcoder.com/challenges/{challengeID}  to http://challenges.topcoder.com/projects/{projectID}/challenges/{challengeID} used to work and now don’t.  This is apparently used by SalesForce integration.

### Actual behavior
Currently, the redirect to add the projects/{projectID} to the URL isn't working

**Comment by suppermancool** [comment]
@jmgasper done in 
[work-manager-issue-1527.patch](https://github.com/topcoder-platform/work-manager/files/11493656/work-manager-issue-1527.patch)
