### ISSUE TITLE
Allow for setting the end date of a phase by duration OR by end date

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1528]
### Expected behavior
In Online Review, copilots and managers can set the end date of a phase by _either_:

* Duration (supported now by WM)
* End date

We would like to add the same ability to WM

<img width="1302" alt="SCR-20230518-mxjs" src="https://github.com/topcoder-platform/work-manager/assets/21790/5f775989-704f-4d24-aa27-42da48856101">

I'm hoping we can design something that makes this easy for manual entry of a datetime, but also a popup if the user clicks the datetime field.

The value saved back to the service will always still be the value it is now, and we'll always just default to editing the duration field.  We don't have to remember if the user wanted to set a datetime or a duration for a particular phase.

**Comment by suppermancool** [comment]
@jmgasper done in 
[work-manager-issue-1528.patch](https://github.com/topcoder-platform/work-manager/files/11505474/work-manager-issue-1528.patch)
