### ISSUE TITLE
Work Manager - OR and WM overwrite each other

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1529]
### Expected behavior

Work Manager shouldn't set or overwrite dates when editing, unless the dates have been changed

### Actual behavior
Reported by a user:

Here you go https://watch.screencastify.com/v/P96K6sYT976pRrsOv9Uo Check how the timeline modifies in Challenge Details, although I changed something in specs in Work Manager and then I have to fix it with Online Review. I have previously set up the dates in OR but then WM change in other place has overwritten the dates too.

**Comment by suppermancool** [comment]
@jmgasper I think the changes in the recent task https://github.com/topcoder-platform/work-manager/issues/1528 fixed this. Can you validate this again? Thanks

**Comment by jmgasper** [comment]
@suppermancool - Yeah, QA just validated it, sorry for the confusion
