### ISSUE TITLE
Show submission IDs and allow submission download in Work Manager

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1531]
REF: https://topcoder.atlassian.net/browse/PROD-4266

**Add submission IDs**

On the Submissions tab in Work Manager, for an active challenge, we need to expand the information shown for each submission to include:

- v5 submission ID (UUID)
- Legacy submission ID

**Download individual submissions**

Additionally, we will add a Download button to each submission shown on the table, allowing a copilot / PM to download the submission.  The Download All button should still work as expected.  

**Remove Manage Submissions button**

We can also remove the Manage Submissions link because the submission review app won’t be necessary after the changes above.

**Comment by suppermancool** [comment]
@jmgasper done in 
[work-manager-issue-1531.patch](https://github.com/topcoder-platform/work-manager/files/11526947/work-manager-issue-1531.patch) (this patch against commit 3789e792b2d666f61f30e131c74b5e96579505b0)
