### ISSUE TITLE
For design challenges, submission downloads are not displayed in WM

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1535]
### Expected behavior
Users with copilot, manager, or admin roles should be able to download submissions for an in-progress challenge

**NOTE** - for regular users, without an enhanced role, the functionality below should remain as it is.

### Actual behavior
As a copilot:

* Go to WM  
* Open a design challenge which has submissions and is in progress

Submissions are not displayed.

![image-20230523-081158](https://github.com/topcoder-platform/work-manager/assets/21790/afb4e6dd-b010-479c-aebc-4688de06b950)

**Comment by jmgasper** [comment]
@suppermancool - For a normal user, we just want the functionality to remain how it was.  It seems like this is broken in the latest update:

Steps

Go to WM challenge https://challenges.topcoder-dev.com/projects/22248/challenges/c54bb893-d672-474e-b4ae-8e74bf16060e/view (log in from Taasintake900/Appirio123)

Go to Submissions tab

It shows the Private challenge image nd under it the submissions list(We shouldn’t show the private challenge image since the submissions are displayed in the bottom?)


https://github.com/topcoder-platform/work-manager/assets/21790/c5cc65ce-19a4-4f66-9481-6393be8eb416

**Comment by suppermancool** [comment]
@jmgasper Actually in the old implement the normal user only see `Private Challenge` done in 
[work-manager-issue-1535-2.patch](https://github.com/topcoder-platform/work-manager/files/11610788/work-manager-issue-1535-2.patch)
