### ISSUE TITLE
Hide submissions for challenges that a given user doesn't have access to

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1538]
The submissions API is blocking submission download of submissions for challenges that a user doesn't have access to (like a copilot opening up another copilot's challenge in WM), but we still show the download button.

Instead, let's block this so it doesn't even attempt to download.  When loading a challenge, we should look at the resources array for the challenge, and if the logged in user is *in* the resources API, then they can see the download buttons, but if they aren't in the resources array, we'll hide the download button.

**Comment by jmgasper** [comment]
@suppermancool - This one failed in QA.  Have a look at:

https://challenges.topcoder-dev.com/projects/16665/challenges/9131c5da-6ed9-4186-9a1b-4de31df5ba17/view

`TCConnCopilot / Appirio123` doesn't have any role on that challenge, but they see the download button.

**Comment by suppermancool** [comment]
@jmgasper the TCConnCopilot have user id = 40158994 . That user id exists in the resources array of challenge `9131c5da-6ed9-4186-9a1b-4de31df5ba17`:

<img width="1347" alt="Screenshot 2023-06-01 at 15 00 45" src="https://github.com/topcoder-platform/work-manager/assets/5815182/b9009769-2bf5-4d51-a4ee-e409f371fb17">

**Comment by jmgasper** [comment]
@suppermancool - Yeah, I see it now, thanks.  If you don't give an `Authorization` header to the resources API, it *only* returns submitters, which is what I was seeing.  Sorry about that.
