### ISSUE TITLE
Reviewers aren't showing

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1550]
### Expected behavior
Sample challenge:  https://challenges.topcoder-dev.com/projects/22262/challenges/5bbc57be-5c7e-4016-ab78-d33a173a49d0/view

Login with `TCConnCopilot`.

The reviewers tab under Resources is empty.

In OR, we show a reviewer - `jcori`

`jcori` actually has a bunch of roles in this challenge but doesn't show at all in the Resources tab.

**Comment by suppermancool** [comment]
@jmgasper the response of resources api (`GET https://api.topcoder-dev.com/v5/resources?challengeId=5bbc57be-5c7e-4016-ab78-d33a173a49d0&page=1&perPage=5000`) does not have `jcori`

**Comment by suppermancool** [comment]
@jmgasper weird but i can see `jcori` in https://challenges.topcoder-dev.com/projects/22262/challenges/5bbc57be-5c7e-4016-ab78-d33a173a49d0/view now without any changes

ANW the results should come from `GET https://api.topcoder-dev.com/v5/resources?challengeId=5bbc57be-5c7e-4016-ab78-d33a173a49d0&page=1&perPage=5000`
