### ISSUE TITLE
Don't allow for deleting reviewers

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1551]
### Reviewers

When displaying the `Delete` button for resources, we will disallow deleting reviewers.  The user can still *add* reviewers, but they can't remove them.  We will block deleting reviewers because there's no easy way in the v5 API to determine if a reviewer has submitted a review against any of the submissions, so we can't do proper validation.

**Comment by suppermancool** [comment]
@jmgasper done in 
[work-manager-issue-1551.patch](https://github.com/topcoder-platform/work-manager/files/12091181/work-manager-issue-1551.patch)
