### ISSUE TITLE
Admin are not able to see all users of the project

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1552]
REF: https://topcoder.atlassian.net/browse/PROD-4313

@suppermancool - This one seems odd.  We shouldn't be showing a list of users until a project is selected, which I don't see being done in this case.

Can you have a look and let me know your thoughts please?

### Reported issue
Admin are not able to see all users of the project. They can see only when they change anyone access . Please find below screenshots for the same:

Before edit access: (Admin can see only copilot and Topcoder Manager)
![5ba15249-1412-41b5-b776-73126f38d11f#media-blob-url=true id=1ccd35fd-afbf-483d-9a65-fc77d26c2a50 contextId=45306 collection=](https://github.com/topcoder-platform/work-manager/assets/21790/7ca7d213-363c-4703-9827-0071333f4a5e)

After click on any of the user’s access which are visible to admin. e.g. Try to change svsathya’s access from full to read.

![6a643c2a-5966-455e-85bb-bd0809f578a6#media-blob-url=true id=172c137e-d8c7-4f41-8572-22d15d6ef467 contextId=45306 collection=](https://github.com/topcoder-platform/work-manager/assets/21790/fef93155-1b9e-46e3-b977-377c33348a38)

### Video

https://github.com/topcoder-platform/work-manager/assets/21790/701663fb-7d9b-432e-adc1-228bcb2d5f44

**Comment by suppermancool** [comment]
@jmgasper I can not log in in `topcoder-dev.com` now
