### ISSUE TITLE
Work Manager - Unable to assign members and copilots to the tasks

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1553]
REF: https://topcoder.atlassian.net/browse/PROD-4315

### Steps

Go to Work manager dev app

Create a dev task and assign a member and a copilot

See if your assignments are there

The assigned member and the copilot are not preserved(member API throws a 500)

### Video

https://github.com/topcoder-platform/work-manager/assets/21790/86fc9d56-4154-427e-ac8d-f3efcc424943

### Investigation

For some reason, we're calling the member API with an `undefined` parameter, which is the cause of the error:

https://api.topcoder-dev.com/v5/members?fields=userId,handle,firstName,lastName,email&userIds[]=undefined&page=1

**Comment by suppermancool** [comment]
@jmgasper done in 
[work-manager-issue-1553.patch](https://github.com/topcoder-platform/work-manager/files/12167828/work-manager-issue-1553.patch)
