### ISSUE TITLE
WM - UI search for project should find exact project name, regardless of status

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1564]
REF: https://topcoder.atlassian.net/browse/PROD-4345

### New functionality

In https://github.com/topcoder-platform/work-manager/issues/1562 we changed the admin dropdown to show all active project.  

To better support Topgear, we need to support searching in the dropdown.  We can search by using the `keyword` URL parameter on the projects endpoint, like:

https://api.topcoder-dev.com/v5/projects/?sort=updatedAt+desc&perPage=20&page=1&keyword=test

We will search across all projects, regardless of status, but only when the user enters text into the search box.

**Comment by suppermancool** [comment]
@jmgasper do we show all active project if text box is empty?

**Comment by jmgasper** [comment]
@suppermancool - Yeah, we'll keep that existing functionality.
