### ISSUE TITLE
Add 'Skills' field below 'Tags and remove v4 technology and skills from tags dropdown

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1566]
When creating / editing a challenge, we are going to split the skills selection out from "tags".

### Remove v4 tech call

Right now, the `tags` dropdown is filled with information from `https://api.topcoder-dev.com/v4/technologies`.  We are going to remove that call completely.  We will be updating the tags functionality in a different ticket.

### Add skills drop down

Currently, "tags" is a mix of user-generated tags and the old v4 skills, which are going to be deprecated.

The new `Skills` field should be an auto-complete field, similar to what we have on `talent-search.topcoder.com`.  The user will start to type a skill and the matches will show up, allowing them to be selected.

The skills selected will eventually be saved to the `skills` array on the challenge, in the same way they are now, but saving to the challenge is *NOT* in scope 

<img width="2175" alt="SCR-20230830-oeim" src="https://github.com/topcoder-platform/work-manager/assets/21790/61200540-7def-4e12-b87f-aa2825f7ce47">

Sample auto-complete call: 

https://api.topcoder-dev.com/v5/emsi-skills/skills/auto-complete?term=java

```
[{
    "name": "Java (Programming Language)",
    "emsiId": "KS120076FGP5WGWYMP0F",
    "category": "Information Technology",
    "subCategory": "Java"
}, {
    "name": "Java 11",
    "emsiId": "ESFA0818E96E402412B4",
    "category": "Information Technology",
    "subCategory": "Java"
}, {
    "name": "Java 7",
    "emsiId": "KS9FICAXCG597A61ZS3A",
    "category": "Information Technology",
    "subCategory": "Java"
}]
```

**Comment by suppermancool** [comment]
@jmgasper In the current code,  the `tags` dropdown is filled with information from 2 APIs:
-  https://api.topcoder-dev.com/v4/technologies 
- https://api.topcoder-dev.com/v4/platforms
Should i remove `https://api.topcoder-dev.com/v4/platforms` too? (the https://api.topcoder-dev.com/v4/platforms api only use for `tags` dropdown)

**Comment by jmgasper** [comment]
@suppermancool - let's remove both calls, thanks.
