### ISSUE TITLE
Replace Tags selector

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1569]
To go along with https://github.com/topcoder-platform/work-manager/issues/1566, we are going to remove and replace the Tags selector:

1.  We will add a "Special challenge" drop down with 3 options:
  * Blank (remove the selected option)
  * Marathon Match
  * Rapid Development Match

If the user select `Marathon Match` or `Rapid Development Match`, we will add either `Marathon Match` or `Rapid Development Match` as a tag to the challenge.  We also need to make sure this field is populated when a challenge loads for viewing / editing in work manager

2.  We will keep the `Tags` section, but we want to replace this with a free-form way to enter tags.  The user will be able to add their own tags, as many as they want.  They should also be able to remove tags that they enter.  I'm open to suggestions on the best / easiest way to implement this.

**Comment by Gauravseta** [comment]
Allowed to take this issue? Then i would like to work on it.

**Comment by jmgasper** [comment]
> Allowed to take this issue? Then i would like to work on it.

No - this one has been assigned, sorry for the confusion.
