### ISSUE TITLE
Outdated moment.js dependency

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1571]
REF: PROD-4375

### Description

It was observed that the application is using vulnerable version of moment js (2.24.0) which is vulnerable to attacks like parsing, validating, manipulating, and formatting dates.
[URL: Work Manager - Topcoder 
](https://challenges.topcoder.com/static/js/2.5269742e.chunk.js)

### Impact:
An attacker could use this vulnerable component to execute further attacks.

**Comment by suppermancool** [comment]
@jmgasper done in 
[work-manager-issue-1571.patch](https://github.com/topcoder-platform/work-manager/files/12657917/work-manager-issue-1571.patch)
