### ISSUE TITLE
Prevent copilots from reassigning activated task to themselves

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1572]
One more case to go with: https://github.com/topcoder-platform/work-manager/issues/1568

We need to ensure that a copilot can't:

1. Create a task assigned to a different member
2. Activate the task
3. Re-assign the task to themselves
4. Close it

After a task has been activated, we should prevent it from being reassigned to the copilot that launched it.

**Comment by suppermancool** [comment]
@jmgasper done in 
[work-manager-issue-1572.patch](https://github.com/topcoder-platform/work-manager/files/12658514/work-manager-issue-1572.patch)
