### ISSUE TITLE
Adding multiple skills not working

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1573]
One bug seen today, which could be related to the auto-complete response changing slightly.  I can add a skill, but then when I start typing for a *second* skill, the dropdown doesn't fill in with the auto-complete results, even though there's items in the API response.

<img width="920" alt="SCR-20230919-gnvp" src="https://github.com/topcoder-platform/work-manager/assets/21790/62d2524e-f2ab-4ea6-a244-d1a4d25de2c9">

**Comment by suppermancool** [comment]
@jmgasper This bug happened because the backend changed the structure of the response of `https://api.topcoder-dev.com/v5/emsi-skills/skills/auto-complete` API

Done in [work-manager-issue-1573.patch](https://github.com/topcoder-platform/work-manager/files/12658088/work-manager-issue-1573.patch)
