### ISSUE TITLE
Allow manager of project to activate / close challenges

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1574]
This error is seen when a manager is attempting to activate a challenge created by a copilot:

![image (1)](https://github.com/topcoder-platform/work-manager/assets/21790/dabc1135-eefb-4d2d-8676-519fffa1e5b6)

Managers on the project should be able to activate / close challenges.

Here's an example `members` array from this project in prod, showing the manager that saw this error:

```
    "members": [
        {
            "role": "manager",
            "updatedBy": 40788310,
            "handle": "lal_g",
            "userId": 40788310,
            "deletedBy": null,
            "createdAt": "2023-08-21T14:31:51.375Z",
            "createdBy": 40788310,
            "isPrimary": true,
            "id": 46389,
            "projectId": 38364,
            "updatedAt": "2023-08-21T14:31:51.380Z"
        },
        {
            "role": "copilot",
            "updatedBy": 22776011,
            "handle": "billsedison",
            "userId": 22776011,
            "deletedBy": null,
            "createdAt": "2023-08-22T01:46:59.496Z",
            "createdBy": 22776011,
            "isPrimary": false,
            "id": 46395,
            "projectId": 38364,
            "updatedAt": "2023-08-22T01:46:59.496Z"
        }
    ],

**Comment by suppermancool** [comment]
@jmgasper The red error in that popup comes from the backend response when frontend calls the API to activate the challenge

**Comment by jmgasper** [comment]
Thanks - tracked this down to a problem between the project API and challenge API.
