### ISSUE TITLE
Save skill data when updating a challenge

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1575]
There are three parts to this task:

### Part 1

We want to change the skill auto-complete endpoint from `/v5/tc-emsi-skills-api` to `/v5/emsi-skills/skills`

Example:

https://api.topcoder-dev.com/v5/emsi-skills/skills/auto-complete?term=jav

### Part 2

We can now save the skills back to the API when editing a challenge.  This will require a *second* API call when saving a challenge, which we'll need to make sure happens in addition to the `PUT` to the challenge endpoint.

To save skills:

POST to `https://api.topcoder-dev.com/v5/emsi-skills-work-skills`

BODY:

```
{
    "workId": "fed687e1-4257-48bb-806c-38712f9bf14f",
    "workTypeId": "413340e8-f56f-4061-8796-c916dfa82770",
    "skillIds": [
        "002015b4-9bcb-4b85-9d46-e648d0375a54",
        "0087514d-5ebc-4720-a635-17f0b5399692"
    ]
}
```

The `workId` is the challenge ID

The `workTypeId` should be configurable, with the default being `413340e8-f56f-4061-8796-c916dfa82770`

### Part 3

When reading the skills to display on the challenge details page, we can continue to use the challenge API response, but we should be looking for the `skills` array, not `emsi-skills`.

**Comment by suppermancool** [comment]
@jmgasper 
1. I get this error when calling update skills in manager app(pls allow https://local.topcoder-dev.com in allow origin cors):
<img width="838" alt="Screenshot 2023-10-16 at 13 35 59" src="https://github.com/topcoder-platform/work-manager/assets/5815182/b1b2141e-841f-44b7-8faa-4b624e306c5e">

2. I get this error when calling update skills in postman:
example body:
```
{
    "workId": "fe775295-1f41-49c8-a946-b9004ced24fe",
    "workTypeId": "413340e8-f56f-4061-8796-c916dfa82770",
    "skillIds": [
        "041573a9-3713-4dbd-ad6d-db5dd2857783"
    ]
}
```
<img width="632" alt="Screenshot 2023-10-16 at 13 38 11" src="https://github.com/topcoder-platform/work-manager/assets/5815182/21da2f71-09b4-4f5e-94d2-ce6c1fc4cdf7">

**Comment by jmgasper** [comment]
@suppermancool - Try `/emsi-skills/work-skills`, instead of `/emsi-skills-work-skills`, thanks.

**Comment by suppermancool** [comment]
@jmgasper I get this error with the new endpoint:
<img width="687" alt="Screenshot 2023-10-16 at 23 20 32" src="https://github.com/topcoder-platform/work-manager/assets/5815182/f9b8431a-0e1a-4acc-88e4-d0c71438e00f">

**Comment by jmgasper** [comment]
@vas3a - Ugh, my bad, thanks for that.  Just wasn't paying attention.

**Comment by suppermancool** [comment]
@jmgasper @vas3a 

1. The API works now but I can not save the skills to challenge https://challenges.topcoder-dev.com/projects/22248/challenges/fe775295-1f41-49c8-a946-b9004ced24fe/edit

- I got the backend error `Job with id: fe775295-1f41-49c8-a946-b9004ced24fe does not exist!` with payload:
```
{
    "workId": "fe775295-1f41-49c8-a946-b9004ced24fe",
    "workTypeId": "413340e8-f56f-4061-8796-c916dfa82770",
    "skillIds": [
        "002015b4-9bcb-4b85-9d46-e648d0375a54"
    ]
}
```

- I got the backend error `Skill(s) to be associated do not exist!` with payload:
```
{
    "workId": "fe775295-1f41-49c8-a946-b9004ced24fe",
    "workTypeId": "413340e8-f56f-4061-8796-c916dfa82770",
    "skillIds": [
        "1780cf93-e193-419e-9f95-6dd05dc86a74"
    ]
}
```

2. Can you provide an example of `skills` in `challenge details` info(response of get {{API_V5}}/challenges/fe775295-1f41-49c8-a946-b9004ced24fe)? Because I can not save the skills now I do not know the template of skills in the backend response.

**Comment by jmgasper** [comment]
@suppermancool - A couple things here:

1.  The work type ID should be `4d2bdbc8-eb3b-4156-8d20-98a46589cc5d`, sorry.  That whole thing is a bit confusing and I had to dig it out of the database.  I'm thinking we may want a lookup API for it.  I've attached the full list below, for reference on later tickets.

3.  I still get an error with that:

```
{
    "message": "Challenge with id: fe775295-1f41-49c8-a946-b9004ced24fe does not exist!"
}
```

I'll have to ask the platform devs on why that's not finding the challenge.


### List of work type IDs

* "2a8c0dcb-830c-4b5f-80e2-6278742dd3af"	"course"	
* "413340e8-f56f-4061-8796-c916dfa82770"	"gig"	
* "4d2bdbc8-eb3b-4156-8d20-98a46589cc5d"	"challenge"
* "51a3b821-f95b-4f56-b508-0f3891f5bc5f"	"certification"
* "71198dc7-dc63-40fd-8502-c005133e7149"	"rapid development match"	
* "90f76653-6859-4122-9a20-c2aa42889a2f"	"single round match"	
* "e50ffd9c-1462-493c-91a7-2b9be510625c"	"marathon match"

**Comment by jmgasper** [comment]
@suppermancool - Ok, the platform team fixed the API.  I was able to create a skill on a challenge with this POST:

```
{
    "workId": "fe775295-1f41-49c8-a946-b9004ced24fe",
    "workTypeId": "4d2bdbc8-eb3b-4156-8d20-98a46589cc5d",
    "skillIds": [
        "002015b4-9bcb-4b85-9d46-e648d0375a54"
    ]
}
```

**Comment by suppermancool** [comment]
@jmgasper there is one problem. I can not save skills with skill ID from https://api.topcoder-dev.com/v5/emsi-skills/skills/auto-complete?term=jav . However, that bug does not block me from finishing this task.

<img width="687" alt="Screenshot 2023-10-17 at 16 31 52" src="https://github.com/topcoder-platform/work-manager/assets/5815182/7798fc4e-7f41-4f82-97d7-3dbc6c50b9b2">

**Comment by suppermancool** [comment]
@jmgasper done in [work-manager-issue-1575.patch](https://github.com/topcoder-platform/work-manager/files/12927553/work-manager-issue-1575.patch) (this patch against commit 073fa1fb984c547d486bdfa8f13e6ab71c4f7ddc in develop branch)

**Comment by suppermancool** [comment]
@jmgasper pls apply this patch after the above patch [work-manager-issue-1575-2.patch](https://github.com/topcoder-platform/work-manager/files/12929813/work-manager-issue-1575-2.patch) (i fix one bug in creating challenge page relate to this)

**Comment by jmgasper** [comment]
@suppermancool - OK, I think we found one bug here.  When saving a challenge, we need to:

1. Save the challenge *first* to the challenge API
2. *Then* save the skills to `/work-skills`, all in one go, instead of every time the user edits a skill in the selector.

What's happening is that the skills are being saved to '/work-skills', but then we save the challenge to the challenge API and because it doesn't contain any skills, they get cleared out.

**Comment by suppermancool** [comment]
@jmgasper i implement your suggestion in [work-manager-issue-1575-3.patch](https://github.com/topcoder-platform/work-manager/files/13049841/work-manager-issue-1575-3.patch) (this patch against commit bd2768e7c50975684e9d9d0d0000bc3102da9421 in develop branch)

- The current app always calls API to save challenge info every time the user updates any field, that is why I call API to update skills every time the user changes skills. I do not see anything wrong with this because I always call the update skills API with the latest skills the user selects.
- Now I try to call `POST /standardized-skills/work-skills` API and the backend returns success, but after fetching challenge info I do not see the skills(no skills field in challenge info response), that used to work before. I think that is the reason the skills keep getting cleared out, there is nothing problem with the frontend code

**Comment by jmgasper** [comment]
@suppermancool - Thanks, we're working on this.

**Comment by jmgasper** [comment]
@suppermancool - Ok, after *a lot* of back and forth, we need to tweak all requests to the challenge API to include a version header like:

`challenge-api-version`: `1.1.0`

Then, the skills will be returned in the `GET` to the challenge API.

Example Postman setup:

<img width="1408" alt="SCR-20231023-shmu" src="https://github.com/topcoder-platform/work-manager/assets/21790/038173b6-60c9-4548-8a71-c56626cb67bf">

**Comment by suppermancool** [comment]
@jmgasper done in [work-manager-issue-1575-4.patch](https://github.com/topcoder-platform/work-manager/files/13069284/work-manager-issue-1575-4.patch) (this patch against commit 88b229efc540138b3b52ae2affad1c9bb0282611 in develop branch)
