### ISSUE TITLE
Don't require tags, but require skills when setting up a challenge

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1576]
REF: https://topcoder.atlassian.net/browse/TSJR-248

When setting up a challenge, we are currently requiring a user enter a tag, but not skills.

We are going to change this to:

1. No tags are required
2. At least one skill is required

<img width="918" alt="SCR-20231101-hmvk" src="https://github.com/topcoder-platform/work-manager/assets/21790/84dd4ae1-2a2a-42f3-89e0-5d14c4199208">

**Comment by suppermancool** [comment]
@jmgasper done in [work-manager-issue-1576.patch](https://github.com/topcoder-platform/work-manager/files/13222883/work-manager-issue-1576.patch) (this patch against commit b10ce0327f05de4b060f3570816fc8fdb6afcf2f in develop branch)

I implemented this in frontend ui but the `PUT /v5/challenges/{...}` api required tags field:
<img width="447" alt="Screenshot 2023-11-01 at 09 45 20" src="https://github.com/topcoder-platform/work-manager/assets/5815182/250be3e7-6d0d-4f86-bad6-464bf5cde1b9">
