### ISSUE TITLE
Copilots can still edit to assign to themselves

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#1578]
REF: https://topcoder.atlassian.net/browse/PROD-4379

We need to ensure that a copilot can't:

* Create a task assigned to a different member
* Activate the task
* Re-assign the task to themselves
* Close it

We're seeing this still possible:

https://github.com/topcoder-platform/work-manager/assets/21790/26dc8f29-53b0-4089-807e-27b92b3bbaf1

**Comment by suppermancool** [comment]
@jmgasper done in 
[work-manager-issue-1578.patch](https://github.com/topcoder-platform/work-manager/files/13225932/work-manager-issue-1578.patch) (this patch against commit 8f0e2ce262e2401f46fd1e4fbedfc95b16d072f6 in develop branch)
