### ISSUE TITLE
Implement Filestack File Upload

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/work-manager#196]
## Tasks
1. Remove the file attachment UI on the challenge editor
2. Replace it with Filestack.
3. Update the challenge object to post an array of file URLs as attachments

**Comment by acshields** [comment]
@rootelement - Is Filestack implemented in the backend? I know that was in progress.

**Comment by vikasrohit** [comment]
@rootelement @acshields we created separate [issue](https://github.com/topcoder-platform/work-manager/issues/917#issuecomment-737390308) as we didn't find this one when starting the work for the filestack implementation at UI.

**Comment by vikasrohit** [comment]
Closing this one in favour of keeping history for the work already done for https://github.com/topcoder-platform/work-manager/issues/917#issuecomment-737390308 in November
