### ISSUE TITLE
Uncaught error 403 in the console loading request status

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/work-manager#338]
**Describe the bug**
An error of API request status from API appears in the console during the loading of the challenge

**To Reproduce / Actual Behavior**
1. Go to 'https://challenges.topcoder-dev.com/'
2. Log in 'Ghostar / appirio123'
3. Click a challenge in the "Active" tab
4. Open the console, while the challenge loads
5. Observe the error
**Expected behavior**
There should be no Uncaught request status error 403 in the console, the API should smoothly give the feedback

**Screenshots**
[Requeststatus.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4599223/Requeststatus.zip)

**Desktop (please complete the following information):**
  - OS: (Official Build) Built on Ubuntu , running on Ubuntu 16.04 
 - Browser: Chrome
 - Version: 81.0.4044.122

**Additional context**
All the 403 error occurs repeatedly to every challenge

**Comment by vikasrohit** [comment]
@drasticdpk @codejamtc we didn't made any changes for this one, however, it should be working fine because the issue was created long back and application has gone multiple refactoring after that and there is no such issue observed in recent days.

**Comment by sandhiyakavi** [comment]
Verified on Prod. No console error shown.

![image](https://user-images.githubusercontent.com/55895538/99774192-cf495600-2b50-11eb-8746-ae15dd1c0668.png)
