### ISSUE TITLE
Duration Placeholder does not fit into the field

### ISSUE THREAD

**Issue by Peppa-2016** [topcoder-platform/work-manager#364]
Describe the bug: Placeholder does not fit into the field

To Reproduce / Actual Behavior Steps to reproduce the behavior:

1.Go to 'https://challenges.topcoder-dev.com' and login using username:jcori password:appirio123
2.Click on any project>edit challenge page will open
3.Scroll down to challenge schedule and click edit option at the right side
4.Delete the no. of hours in one of the field and observe
5.Placeholder does not fit into the field

Expected behavior: Placeholder should fit into the field

Screenshots If applicable, add screenshots to help explain your problem.
![placeholder overlap](https://user-images.githubusercontent.com/60426529/81416020-ca015c80-9166-11ea-8f57-15c83d578d7e.jpg)

Desktop (please complete the following information):

OS: [windows 7]
Browser [firefox]
Version 76.0(64-bit)
![About Firefox](https://user-images.githubusercontent.com/60426529/81416049-d1c10100-9166-11ea-82fb-07e75ad6c16e.jpg)
![OS version](https://user-images.githubusercontent.com/60426529/81416059-d84f7880-9166-11ea-81f2-bf0ac56e8bb6.jpg)

**Comment by vikasrohit** [comment]
@acshields  It does not matter for now as we are not showing the edit timeline component. Please move it to a later release when incorporate the edit timeline feature.

**Comment by acshields** [comment]
@vikasrohit - noted and agreed. I will move this out.

**Comment by acshields** [comment]
- closing this as it will be addressed in the new UI we are implementing.
