### ISSUE TITLE
"Clicking ""x"" icon on first tags removes all the tags.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/work-manager#406]
"Clicking ""x"" icon on first tags removes all the tags.

**Steps To Reproduce:**
1. Go to url ""https://challenges.topcoder-dev.com/"" 
2. Log in as Ghostar with valid credentials.
3. Navigate to drafts and click on the first challenge available.
4. Scroll down to the tags section and click the ""x"" icon.
5. Observe.

**Actual Result:**
App the available tags are removed.

**Expected Result:**
Only the selected tag should be removed successfully.

OS: Windows 10
Browser: Chrome
Version 81.0.4044.138

**Screenshot:**"
[Bug 10.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4599667/Bug.10.zip)

**Comment by jmgasper** [comment]
Most likely due to bad data, but this is a UI bug not a functional bug.

**Comment by vikasrohit** [comment]
@codejamtc @drasticdpk Not able to produce this now, please check at your end as well.

**Comment by codejamtc** [comment]
@vikasrohit Not able to reproduce. (I can see duplicate tags added in the bug video, so that may be the case it removes all tags when user removes only one)

**Comment by sandhiyakavi** [comment]
Verified in Prod.Working as expected.

[issue#406.zip](https://github.com/topcoder-platform/work-manager/files/5564537/issue.406.zip)
