### ISSUE TITLE
Popup displayed when we add a button inside the 'Public specification'

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#477]
![image](https://user-images.githubusercontent.com/42398485/81423303-ea56fa00-9119-11ea-8456-b0e7c244a515.png)

**URL:**
https://challenges.topcoder-dev.com/projects/16531/challenges/3077070a-5532-492c-99b4-e6fa3d882f91/edit

**Reproduction Steps:**

1. Open the application and Login as a valid user (jcori)
2. Create a new draft challenge > Go to Draft tab > Click on it
3. Go to 'Public specification'
4. Add below code

```
<h2>HTML Buttons</h2>
<p>HTML buttons are defined with the button tag:</p>

<button>Click me</button>
```

5. Click preview
6. Click on the button

**Actual Result:** 

- Popup displayed when we add a button inside the 'Public specification'

**Expected Result:** 

- Should not display that particular popup

**Device/OS:** 

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 10 64bit (1909, 18363.815)

**Browser Information:** 

- **Browser(s):** Google Chrome 81.0.4044.138

**Comment by jmgasper** [comment]
Upgrading this to a security problem.  May be an XSS-type issue.

**Comment by vikasrohit** [comment]
Fixed the issue with front end, backend already seems to be sanitizing the content (you can see the button html is converted HTML encoded after server round trip).

@rootelement @ThomasKranitsas @acshields fyi

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/95161961-1ad2bb00-07c2-11eb-945c-953b506f4c8c.png)

Nothing happens when user click on it

**Comment by sandhiyakavi** [comment]
Verified on Prod. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/99625371-7657c000-2a73-11eb-83de-6b426d6a89a9.png)

**Comment by vikasrohit** [comment]
@sandhiyakavi can you please apply label `Pass on Prod` as well after verifying on prod? I am doing it for this one.
