### ISSUE TITLE
Able to create challenge with html tag and SQL queries

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/work-manager#497]
**Describe the bug**
Able to create challenge with html tag and SQL queries

**To Reproduce / Actual Behavior**
1. Go to '
https://challenges.topcoder-dev.com '
2.Login as jcori / appirio123'
3. Click on Create new challenge
4. Add challenge name as "<html><head><body> I am a challenger {select * from challenge table}}</body></head>> <html>"

**Expected behavior**
challenger name should not accept HTML tag and SQL queries

**Screenshots**
![image](https://user-images.githubusercontent.com/61318135/81425818-e8bb1f80-9175-11ea-9f5e-8e180ca9bad3.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [e.g. chrome]
 - Version [78]

**Additional context**

**Comment by ThomasKranitsas** [comment]
Not really sure if this is an actual security risk. As you can see here https://challenges.topcoder-dev.com/projects/9171/challenges/3c13262a-f6f7-4e37-a3de-2ba56908dd03/view the title has some JS code in it but it's rendered as text. Also, the challenge description can accept HTML content.

cc @rootelement

**Comment by vikasrohit** [comment]
I guess, we can close this as we are sanitizing the content before rendering. However, we might need to think about sanitizing the content while storing in database and ES because that still might be possible.

fyi @mtwomey @ThomasKranitsas @rootelement

**Comment by vikasrohit** [comment]
@drasticdpk @codejamtc @lakshmiathreya we just need to verify that entering the javascript and HTML inside the challenge fields (except specs) is not executed. Entering SQL should not be an immediate problem as we are storing data in SQL database, however, I would still like to open a new issue to keep track of properly validate SQL or Query injection in challenge-api, which @rootelement can have final decision on.

**Comment by drasticdpk** [comment]
Verified on Dev env :
Reference 
![image](https://user-images.githubusercontent.com/25297859/94387300-7a4d1d00-0169-11eb-87f4-b5320e52ca59.png)

**Comment by rootelement** [comment]
Thomas has implemented `xss` on title and description.
https://github.com/topcoder-platform/challenge-api/issues/301

**Comment by sandhiyakavi** [comment]
Verified on Prod. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/99634861-83c97600-2a84-11eb-8c7c-a9709544088c.png)
