### ISSUE TITLE
Unauthorize Copilot Can Access Challenges

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/work-manager#558]
## Steps to Reproduce:
- Login as JCori
- Go to **Test taas Project** Tab
- in Active Tab  choose challenge with title **logo**
(https://challenges.topcoder-dev.com/projects/16529/challenges/af04bebb-aad3-4731-9861-f9cd158447ee/edit)
- Copy link and then go to another browser with different user (I used **cori_copilot**)
- Paste link

## Video 
https://www.dropbox.com/s/ou7h2q7nw9metyi/2020-05-08-21-11-12.avi?raw=1

## Actual Result:
User can access specific challenge that assign to another copilot

- challenge belongs to jcori
![](https://www.dropbox.com/s/shza84atqjjzluy/jcori2.png?raw=1)

- cori_copilot can access if we paste the link
![](https://www.dropbox.com/s/ltq0ppzponkoaj4/authorize.png?raw=1)

## Expected Result:
User cannot access specific challenge  that assign to another copilot

## Device/OS/Browser Information:
- Device: Lenovo (laptop)
- Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
- RAM : 8 GB
- System Type: 64 Bit OS, x64-based processor
- Pen or touch: no pen or touch
-  OS: Windows 10 Home Single Language
- Browser: Google Chrome (81.0.4044.138 (Official Build) (64-bit)) and Firefox(76.0.1 (64-bit))

**Comment by acshields** [comment]
@vikasrohit - can you test this out as well? If still valid, then this will need to be addressed soon.

**Comment by ThomasKranitsas** [comment]
This seems very outdated. The security checks have been completely refactored since this issue was created. Please re-test and close this.

**Comment by vikasrohit** [comment]
@drasticdpk @codejamtc marked this issue as ready for QA to retest the logic as per @ThomasKranitsas's suggestion.

**Comment by codejamtc** [comment]
@vikasrohit @ThomasKranitsas I think this one is still there

[1.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5267920/1.zip)

**Comment by ThomasKranitsas** [comment]
Hmm.. So, this is a bit complicated.

You can see the challenge but I guess you can't edit it, right?

I mean, when the challenge is not private (restricted via groups) and you simply make a GET request, there's no reason the API would not let you see it.

So, this is something the frontend should handle. It should fetch the project info, see if the logged in member is on the project and then either let the copilot see the challenge or throw an error.

cc @vikasrohit @rootelement

**Comment by codejamtc** [comment]
@ThomasKranitsas I am getting an error when I try to edit
[1.1.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5267996/1.1.zip)

**Comment by ThomasKranitsas** [comment]
This means the access checks work fine and my previous comment is correct.
cc @vikasrohit

**Comment by rootelement** [comment]
Thomas is right. The challenge is public, so viewable... The UI needs to realize the user can't edit. So it can show as read only if you like.

**Comment by codejamtc** [comment]
@ThomasKranitsas @rootelement Yes, better if we can implement a read-only view 

The below error will give an idea that he can edit but some other issue happens while editing.

`There was an error loading the challenge, Please try again later, and if the issue persists contact us at support@topcoder.com to resolve the issue as soon as possible.`

**Comment by vikasrohit** [comment]
Reducing priority as user can not edit other copilot's or user's challenge, though they can see it which is okay because any one can read a challenge.

**Comment by vikasrohit** [comment]
Implemented explicit access control for challenges where user don't have access to the challenge or its project.

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/96855738-c7779280-147a-11eb-9d92-587493d2727d.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod.Working as expected.

![image](https://user-images.githubusercontent.com/55895538/99636590-f6d3ec00-2a86-11eb-85ef-aa8b14a3c334.png)
