### ISSUE TITLE
Assigned Task Option

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#673]
**Current Version:** There is no workflow for Assigned Task.

**Desired Updates:**
- On Screen 1 of the challenge set-up workflow, a user should be able to select the following challenge types:
1. Challenge
2. First 2 Finish Task
3. Assigned Task
- On Screen 2 of the challenge set-up workflow, if a user has chosen Assigned Task they should see a question above the Copilot question, which functions as follows:
-Question Label: Assigned Member
-Answer Format: [Responsive Text Entry Field]
-Answer responses should return member handle values as the user types.

**Comment by mtwomey** [comment]
This should not block release (as you said @acshields). I suspect  this could consume time.

**Comment by vikasrohit** [comment]
Yes, it would definitely consume time.

**Comment by acshields** [comment]
Thank you for your feedback @mtwomey @vikasrohit - I will move this to V2: MVP milestone (after production-release)

**Comment by vikasrohit** [comment]
@maxceem it seems like once you select a member to be assigned and wanted to edit the user, you can not do it without starting from first character. I mean, lets say you selected `maxceem-dev` first and then you wanted to change it to `maxceem`. I am not able to do that by removing the `-dev` from the auto select box rather it just starts from first character. It is not a P0 or P1 but if it is a quick fix, can you please get that done.

**Comment by vikasrohit** [comment]
Okay, got it. I think better to delay that until we have new designs and requirements.

**Comment by vikasrohit** [comment]
@drasticdpk @codejamtc marked it ready for qa, however, there are some known issues/facts around this feature. @maxceem could you please describe in summary and link what are the issues faced from api endpoint for this feature?

**Comment by codejamtc** [comment]
1. On Screen 1 of the challenge set-up workflow, a user should be able to select the following challenge types:  🆗 

- Challenge
- First 2 Finish Task
- Assigned Task

2. On Screen 2 of the challenge set-up workflow, if a user has chosen Assigned Task they should see a question above the Copilot question, which functions as follows:

-Question Label: Assigned Member
-Answer Format: [Responsive Text Entry Field]
-Answer responses should return member handle values as the user types.

![image](https://user-images.githubusercontent.com/42398485/92269903-af3bbc00-eeaa-11ea-97ae-a4c5e48748e8.png)

![image](https://user-images.githubusercontent.com/42398485/92269739-62f07c00-eeaa-11ea-958b-268cd9fc0c71.png)

**Comment by maxceem** [comment]
> could you please describe in summary and link what are the issues faced from api endpoint for this feature?

@vikasrohit there should be no crucial limitations, it should work good.

@codejamtc are you facing any issues with this feature?

**Comment by codejamtc** [comment]
@maxceem Sorry No, I will mark it as `QA Pass`

**Comment by sandhiyakavi** [comment]
Verified on Prod. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/99637524-5383d680-2a88-11eb-9fee-252b7b06d80b.png)
