### ISSUE TITLE
Multiple Challenges are creating 

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#680]
**To Reproduce / Actual Behavior**

1. Login as Ghostar
2. In **Test tass Project Created project**, click button Launch New
3. Choose **QA** Track
4. Choose type **Bug Hunt**
5. Fill challenge Name as **CM Bug hunt**
6. Make multiple click on create challenge button
7. Go to challenge listing page and observer at New tab. There are multiple challenges are created.

**Expected behavior**
There should be one challenge with  **CM Bug hunt1** which is recently created.

**Screenshots**
![image](https://user-images.githubusercontent.com/25297859/83867073-8b03fe00-a748-11ea-9680-6105c03e4c47.png)
https://monosnap.com/file/yEPtXdKhuwbNlBBsifcVHBSfMX70MX

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version : 3.0.4103.61 (Official Build) (64-bit)

**Additional context**
Sometime user unknowingly make double click on button. Generally it is best practice to disable button or enable loader after first click on button. So system will not create duplicate data on server. Developer Note: Write the solution (css class/function) in a way so we can implement it all button of the application. And please verify for all possible scenario/buttons.

**Comment by vikasrohit** [comment]
@drasticdpk  downgrading priority for this issue as it is being release to internal users only and we don't expect them to intentionally make multiple clicks on Create button.  @acshields I have not assigned any milestone for it, please move to appropriate milestone as per needs.

**Comment by vikasrohit** [comment]
@acshields I would suggest to move it to August.

**Comment by maxceem** [comment]
Done via https://github.com/topcoder-platform/challenge-engine-ui/pull/796

**Comment by sandhiyakavi** [comment]
Verified on Prod. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/99638222-41eefe80-2a89-11eb-8652-aea71c996770.png)
