### ISSUE TITLE
Invalid Message on challenge confirmation window

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#695]
**To Reproduce / Actual Behavior**

1. Go to Add/Edit Challenge window.
  User : TonyJ
  Reference : https://challenges.topcoder-dev.com/projects/16541/challenges/a0fb0aa9-eb9c-48f4-9ba7-b2b9dec3a512/edit 
2. Click on 'Launch as Active' button.
3. Observe pop up message.

**Expected behavior**
Message should be "Do you want to launch Challenge "Challenge Name"?"

**Screenshots or Video**
![image](https://user-images.githubusercontent.com/25297859/84751677-8e1aac00-afdc-11ea-91af-1a4389ee4d73.png)

**Comment by vikasrohit** [comment]
@drasticdpk `Challenge` in that message is type of the challenge that is why it seems confusing but I think we can live with it for some time till we have all challenge types settled down.

**Comment by vikasrohit** [comment]
This should no more valid now. @drasticdpk can you please retest?

**Comment by drasticdpk** [comment]
Verified on Dev mode
![image](https://user-images.githubusercontent.com/25297859/95051760-8149d180-070d-11eb-8248-670239c70a03.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod.Working as expected.

![image](https://user-images.githubusercontent.com/55895538/99644375-31db1d00-2a91-11eb-939e-4262c76052d8.png)
