### ISSUE TITLE
Update Copy & Answer Format on NDA Question

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#720]
**Current Version**
- Copy States: Require NDA
- Answer Format: Checkbox

**Desired Updates**
- Copy States: Enforce NDA
- Answer Format: Yes/No Toggle Button

**Comment by vikasrohit** [comment]
We do not have any component for toggle button. So, we have to live with radio button only if we don't want checkbox. Are we good with having radio button @acshields?

**Comment by acshields** [comment]
@vikasrohit - The reqs for this question have actually been updated since I initially wrote this feature. Here is the revised behavior for this question:

### Update 1
The Enforce NDA question will be displayed in the 'Advanced Settings' part of the 'Basic Details' section of the set-up flow (reference the designs). This means that this question should have a default answer always selected, which can be modified by opening the advanced settings section. 

### Update 2
The following updates should be made to the "Enforce NDA" question:
- Above the answers, update the question label to read: "Enforce Topcoder Standard Terms"
- Note: the 'Standard Terms' portion of that text will be where we eventually provide a hyperlink, once James completes his work in this issue (https://github.com/topcoder-platform/terms-service/issues/43).
- Answer format: Checkboxes, where the user could select either, or both. Note: the design currently shows radio buttons, but this was incorrect. It should be a checkbox.
- Answer options:
-Topcoder Standard Terms 
-Custom Terms
<img width="1027" alt="Screen Shot 2020-11-18 at 8 22 17 AM" src="https://user-images.githubusercontent.com/41118149/99542721-01539000-2978-11eb-907b-58215a6e4266.png">


### Update 3
The "Topcoder Standard Terms" answer should always be the defaulted answer choice. If the user does not edit this answer, this should be answer applied to the challenge.

**Comment by acshields** [comment]
@vikasrohit - given this information, I am assuming this issue may move out to December, right?

**Comment by vikasrohit** [comment]
Yes @acshields it would move to December, though we would be starting work on it this month only but it can not be concluded in this month because we have to implement the complete form in single take for the new designs.

**Comment by acshields** [comment]
If the work can start this month, than let's do this for tracking purposes:
Keep it in the November project & move it to In Progress when the work starts
Also tag it in the December project & move it to In Progress there when the work starts

Unfortunately, the one thing Git doesn't support (it seems) is synced "status" across projects for the same issue, so we will have to manage this manually. However, it's still helpful for me to know what we are actively working on even if it won't be completed this month. 

I have made the updates to projects as indicated above.

**Comment by vikasrohit** [comment]
@acshields do you think we need this issue when we already have https://github.com/topcoder-platform/work-manager/issues/735#issuecomment-732022970?

**Comment by acshields** [comment]
Meh probably not - This one just refers to the specific NDA Terms question, while the other one covers the entire section's UI & functionality. Up to you on whether you want to keep it, or close it and just use the UI story. However, let me know what you decide @vikasrohit - there are a lot of cases right now where I have the UI by section issues, and then issues created for a specific question within that UI (updating the functionality of the question). I am fine with however you want to manage moving forward, but knowing your preference will help me streamline how I write these issues moving forward.

**Comment by vikasrohit** [comment]
Okay, lets keep it separate in this case. My assumption was that the bigger story where you are describing overall section (#735 (comment) in this particular case), we have all specific requirements as well. But if we have more fine grained requirements for individual questions, it makes sense to keep them in separate issues and link them with the parent one so that we can know what exact details we have to follow when start implementing the section in new UI. The starting point for us for development would the story where we have requirement for section.
