### ISSUE TITLE
Copilot Selection and Fee Conditional Logic

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#721]
**### Scenario 1**
**Pre-Condition: There is only one user with the Copilot role on the project.** 

**Option 1**
**_The user creating the challenge or task is the user with the Copilot role. When this occurs, then:_**
_Copilot Selection_
- The "Copilot" field is displayed under the Advanced Settings "Participants" section
- The "Copilot" field has defaulted to the handle of the user creating the challenge or task
- The user creating the challenge or task can edit the default by clicking on the "Copilot" field dropdown menu and selecting "No Copilot required"
_Copilot Fee_
- The "Copilot Fee" field is displayed under the Advanced Settings "Prizes" section
- The "Copilot Fee" field has defaulted to the standard $40.00 fee value
- If the user creating the challenge or task changed the default to "No Copilot required," then the "Copilot Fee" value should update to $0.00.
- The user creating the challenge or task can edit the default "Copilot Fee" $40.00 value as needed by entering a new numeric value.

**Option 2**
**_The user creating the challenge or task is not the user with the Copilot role. When this occurs, then:_**
_Copilot Selection_
- The "Copilot" field is displayed under the primary set-up "Participants" section
- The "Copilot" field is a dropdown menu with the default text of "Select Copilot" displayed prior to any answer being selected
- The "Copilot" dropdown menu has these answer options:
-[Handle] of the user with the Copilot role
-"No Copilot required"
_Copilot Fee_
- The "Copilot Fee" field is displayed under the primary set-up "Prizes" section
- The "Copilot Fee" field value is empty until the user provides an answer in the "Copilot" selection field in the "Participants" section
- If the user creating the challenge or task selects the Copilot handle, then the Copilot Fee field value will update to the default of $40.00
- The user creating the challenge or task can edit the default "Copilot Fee" value as needed when a Copilot is selected by entering a new numeric value.
- If the user creating the challenge or task selects "No Copilot required", then the Copilot Fee field value should be hidden under the primary "Prizes" section and in the Advanced Settings "Prizes" section the Copilot Fee value should display as $0.00

**### Scenario 2**
**Pre-Condition: There are multiple users with the Copilot role on the project.** 

**Option 1**
**_The user creating the challenge or task is one of the users with the Copilot role. When this occurs, then:_**
_Copilot Selection_
- The "Copilot" field is displayed under the Advanced Settings "Participants" section
- The "Copilot" field has defaulted to the handle of the user creating the challenge or task
- The user creating the challenge or task can edit the default by clicking on the "Copilot" field dropdown menu:
-Select an alternate Copilot's [Handle]
-Select "No Copilot required"
_Copilot Fee_
- The "Copilot Fee" field is displayed under the Advanced Settings "Prizes" section
- The "Copilot Fee" field has defaulted to the standard $40.00 fee value
- If the user creating the challenge or task changes the selected Copilot, then the default "Copilot Fee" value of $40.00 does not change.
- If the user creating the challenge or task changed the default to "No Copilot required," then the "Copilot Fee" value should update to $0.00.
- The user creating the challenge or task can edit the default "Copilot Fee" $40.00 value as needed by entering a new numeric value.

**Option 2**
**_The user creating the challenge or task is not any of the users with the Copilot role. When this occurs, then:_**
_Copilot Selection_
- The "Copilot" field is displayed under the primary set-up "Participants" section
- The "Copilot" field is a dropdown menu with the default text of "Select Copilot" displayed prior to any answer being selected
- The "Copilot" dropdown menu has these answer options:
-[Handles] of users with the Copilot role
-"No Copilot required"
_Copilot Fee_
- The "Copilot Fee" field is displayed under the primary set-up "Prizes" section
- The "Copilot Fee" field value is empty until the user provides an answer in the "Copilot" selection field in the "Participants" section
- If the user creating the challenge or task selects a Copilot handle, then the Copilot Fee field value will update to the default of $40.00
- The user creating the challenge or task can edit the default "Copilot Fee" value as needed when a Copilot is selected by entering a new numeric value.
- If the user creating the challenge or task selects "No Copilot required", then the Copilot Fee field value should be hidden under the primary "Prizes" section and in the Advanced Settings "Prizes" section the Copilot Fee value should display as $0.00

**Comment by vikasrohit** [comment]
> but the user can switch the toggle button to "No" if desired.

@acshields You meant `"No" if not desired` right?

> -If Answer 2 was "No," then hide Answer 2 from the display, even if there are Copilot users on the Connect Project.

You meant `if Answer 1 was "No"` right?

> Answer 2 Format: Responsive Text Field

I do not see anywhere we are using the responsive text field. All we are showing is the clickable components which renders the copilot names as they are right now in the app.

**Comment by acshields** [comment]
@vikasrohit - Noted. In addition, there has been a few changes to this question since the time that I originally wrote it. Please see below.

### Update 1
The "Copilot" question will be a part of the Participants section in the set-up flow. As a note, the entire Participants section will be Advanced Settings only - meaning that all answers will initially default. 

### Update 2
Updating the logic behind the Copilot question:
**Condition 1**
- If there are no users on the Project who have a Copilot role, then the following should be displayed:
- Text that reads: "No Copilots are available"
- Hyperlinked sub-text that reads: "How do I get a Copilot?"
- When that is clicked, a pop-up box should appear that reads: "A Copilot has not joined your Project. To request a Copilot, complete this form." The word 'form' should be hyperlinked to this Google Form: https://docs.google.com/forms/d/e/1FAIpQLSeZ7UXDd4XGOISHLs-zLaZwKliTySlbfso5px71tRTePfRj3Q/viewform

_Note: In this case, the Copilot Fee field should be hidden. The user can still save the challenge/task, and edit at a later time if they have a Copilot added._

**Condition 2**
- If there is only one Copilot on the project, then their handle should be displayed as the selected Copilot by default. 
- The user can unselect the Copilot if desired.

_Note: In this case, the Copilot Fee field should be displayed by default. If the default Copilot is unselected, then the Copilot Fee field should be hidden._

**Condition 3**
- If there are multiple Copilot options on the project, we should implement additional logic for selecting the default Copilot that follows these rules:
-Default Copilot should be selected based upon the track (Design, Dev, QA, DS) selected 
-Default Copilot should be selected based upon users who only have the Copilot role (this will handle the case where 
- Topcoder Managers may also have a Copilot role, but the default should probably be the actual Copilot).
- The defaulted Copilot selection's handle should appear on a 'selected' button
- Additional Copilot options should display on additional unselected buttons
- The user can choose to select a different Copilot than the defaulted choice
- The user can choose to unselect the default and not choose another choice

_Note: In this case, the Copilot Fee field should be displayed by default. If no Copilot is unselected, then the Copilot Fee field should be hidden._

**Comment by acshields** [comment]
@vikasrohit - with these changes to the requirements, I am assuming this one will move out to December, right?

**Comment by vikasrohit** [comment]
@acshields yes, it would move to December, we would start on it right away, but it can not be concluded in November because it can not be worked on standalone and we have to implement other pieces of the form along with. We can not do part of the form with new designs and part with old designs.

> In this case, the Copilot Fee field should be displayed by default. If no Copilot is unselected, then the Copilot Fee field should be hidden.

I guess there is a typo you might want `If no Copilot is  **selected**, then the Copilot Fee field should be hidden.`

**Comment by acshields** [comment]
@vikasrohit - confirmed the above was a typo, I will update my comment for accuracy.

For tracking purposes, let's do the following:
Keep this issue in November, and move it to In Progress as the works starts.
Also add it to December, and move it to In Progress as the works starts, and then we can track in that month too.

**Comment by vikasrohit** [comment]
@acshields it seems like this would be redundant of #736 or do you think it has some other information that is not there.

**Comment by acshields** [comment]
Yeah @vikasrohit there is some information covered here in my post from 5 days ago that is not covered in #736. To help, I've also copy/pasted my comments from 5 days ago into the original reqs at the top, so it doesn't get lost.

**Comment by vikasrohit** [comment]
@maxceem this one has to be worked on along with #736

**Comment by lakshmiathreya** [comment]
@vikasrohit @acshields is this part of December release?

**Comment by vikasrohit** [comment]
No. It is being worked on in December but not part of 15th Dec release.

**Comment by vikasrohit** [comment]
@ajefts closing this and similar for now to clean up things.
