### ISSUE TITLE
Update Group Q&A Format, Functionality & Copy

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#723]
**Current Version:** When Advanced Settings is clicked in the top section of challenge set-up, a sub-section opens and the Group question is displayed with a dropdown menu.

**Desired Updates:**
- Remove the Advanced Settings and display this question before the Copilot question.
- Update Question Description to be: Intended Work Group
- Update Answer Format to be: Toggle Button [Topcoder Public Community/Other Group]
- Answer Logic:
-Default option to Topcoder Public Community, unless the Connect Project dictates otherwise.
-If "Other Group" is selected in the toggle, then a dropdown menu with a list of all groups the user has permission to view populated.
- This question (Intended Work Group) should only display if "Challenge" or "First 2 Finish Task" are selected. If "Assigned Task" is selected, an alternate form of the question will be displayed.

**Comment by vikasrohit** [comment]
No toggle button component until we have new designs implemented. So, if we are okay with radio button we can go ahead with this one.

**Comment by acshields** [comment]
@vikasrohit - another issue where the requirements have been modified since the time I originally wrote this. Please see below for the revised requirements.

### Update 1
The "Intended Work Group" question will be a part of the Participants section in the set-up flow. As a note, the entire Participants section will be Advanced Settings only - meaning that all answers will initially default. 

### Update 2
The "Intended Work Group" question should have these changes applied:
- Field question label should remain "Intended Work Group"
- Answer format: Checklist, where the user can select one or multiple options.
- Answer options: 
-'Topcoder Public Community' should display as the defaulted checked answer option. (Noted that this isn't a 'group,' but we need to have a way of communicating that if an alternate choice isn't selected then this challenge will be published to the total Community's Challenge listings.
-All other checklist answer options should populate based upon the groups that the user has permissions too.

**Comment by acshields** [comment]
@vikasrohit - with these changes, does this issue stay in November or move out to December?

**Comment by vikasrohit** [comment]
@acshields thanks for the update. The new requirements have one problem.
> All other checklist answer options should populate based upon the groups that the user has permissions too.

We can not show checklist for groups because for admins there can be 1000s of groups and a checklist would not be a good UX.

**Comment by acshields** [comment]
@vikasrohit - could we do a responsive list then, where the user can start typing and see all groups that have text-match to the character-entry?

**Comment by vikasrohit** [comment]
I think we are not dependent on https://github.com/topcoder-platform/work-manager/issues/899, we have to wait for api to get updated. However, what we can do is that we can change the UI component to be auto suggest box, but we would that suggestion search on local machine i.e. we would fetch the full list of groups from the server and then will filter on local usr machine. And when we have the api changes done, we can replace the local search with api search.

**Comment by vikasrohit** [comment]
@maxceem please see https://github.com/topcoder-platform/work-manager/issues/723#issuecomment-731038974 for implementing the group list in challenge form

**Comment by lakshmiathreya** [comment]
@vikasrohit @acshields pls mention the milestone for this Issue.
