### ISSUE TITLE
Pre-Populate & Display Connect Project Billing Account Name

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#724]
**Current Version:** The Connect Project's Billing Account is not displayed in the Work Manager app.

**Desired Updates:** 
- Pre-populate the Billing Account Name that is associated with the Connect Project onto the challenge
- Display the Billing Account Name underneath the Connect Project Name, as follows:
-Field Title: Billing Account
-Pre-Populated Answer: [Billing Account Name]

**Comment by vikasrohit** [comment]
@acshields we might not need to pre populate the billing account as of now because at the time of activation legacy challenge processor looks for the billing account from direct project (legacy project) and sets that to the challenge.

**Comment by vikasrohit** [comment]
@acshields please let me know your thoughts about https://github.com/topcoder-platform/work-manager/issues/724#issuecomment-698887985 and another question would be, do we have designs showing this change?

**Comment by acshields** [comment]
@vikasrohit - Let's plan to talk this one over tomorrow so we can all get on the same page. Here's my initial thought: I think we do need to carry over the billing account applied to Connect Project into Work Manager, and display it as pre-populated field in the "Basic Details" section under Advanced Settings. Mess is eager to get the company off of Direct as swiftly as possible and the billing account workflow is one of the last hurdles for us get through (i.e. the user should not have to select the billing account in Direct at all, and the workflow should operate exclusively through Projects App/Work Manager).

However, there may be a component of this topic that I am not fully grasping.
