### ISSUE TITLE
Move Challenge Status Display Location in Set-Up Workflow

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#730]
**Current Version:** Challenge status is displayed within the set-up workflow on Screen 2.
<img width="765" alt="Screen Shot 2020-07-17 at 8 56 11 AM" src="https://user-images.githubusercontent.com/41118149/87795591-e7f5d800-c80d-11ea-915b-491f36f0132d.png">

**Desired Update:** Move the challenge status to be displayed underneath the header on Screen 2.

**Comment by vikasrohit** [comment]
@acshields by header you mean, `Edit Challenge` in the screenshot?

**Comment by vikasrohit** [comment]
@acshields please let us know what do you think about https://github.com/topcoder-platform/work-manager/issues/730#issuecomment-662416677?

**Comment by acshields** [comment]
@vikasrohit - I was referring to the "Status: New" that is currently displayed within the set-up section. In the new designs, I have the current status displayed in the header and not in a section. Should we move this story to December, where more of the design UI will be implemented?

**Comment by vikasrohit** [comment]
Yes, if you want it to be implemented with new designs. If you are okay with moving it in current designs, we can implement that in this month.
However, I am still not 100% clear what do you mean by header. Is it the `Edit Challenge` heading?

**Comment by acshields** [comment]
@vikasrohit - Ah, gotcha. What I mean by "header" is the space on the screen above the first "section" (white background with grouped questions).

**Comment by acshields** [comment]
@vikasrohit - I will move this to December, to coincide with the bulk of the design work.

**Comment by vikasrohit** [comment]
@maxceem this one is for December work, not for November.

**Comment by acshields** [comment]
- closing this, as it is addressed in the new UI we will implement.
