### ISSUE TITLE
Reinstate Timeline Template Selection & Minimum Capabilities

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#731]
**Environment:** In the dev environment, I no longer see anything for timeline on the challenge (template selection, etc.). https://challenges.topcoder-dev.com

**Desired Updates:** Prior to introducing new users (Expert Services, Copilots to this app) we need to reinstate timeline visibility to the set-up workflow. At a bare minimum, timeline presentation and capabilities in Work Manager need to match what is currently available in Direct during set-up, including:
- Timeline template option(s) that are filtered to the selected track and type.
Example 1: In Work Manager, we've simplified types down to challenge/F2F/assigned task. That means when Design track and Challenge type are selected, there would be at least two timeline template options: Application Front End Design, and RUX.
Example 2: A Dev track and F2F type would have one timeline template, so instead of display this in a dropdown menu it should be displayed as a pre-populated option.
- Enter the start date and time for phases, where the user could do the same in Direct (Ex. User can set the start date/time for each phase of an Application Front End Design challenge in Direct)
<img width="629" alt="Screen Shot 2020-07-17 at 9 36 33 AM" src="https://user-images.githubusercontent.com/41118149/87798995-4a50d780-c812-11ea-83f9-987d4aee140c.png">
- View the timeline as a Gantt chart (this is not in Direct, but was a feature created in Work Manager already).

**Comment by vikasrohit** [comment]
@acshields definitely we need to move it out from July and it might take much longer time to reenable the timeline template selection.

**Comment by vikasrohit** [comment]
@acshields I think we can close this one as it does not makes sense now after new designs and we are already tracking timeline edit section #738

**Comment by acshields** [comment]
@vikasrohit - agreed. I closed it.
