### ISSUE TITLE
Enable Scheduling of Challenges in the Future

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#733]
**Current Version:** Work Manager does not have a capability for a user to create and schedule a challenge/F2F/assigned task to be launched at some date and time in the future.

**Desired Updates:** Identify a solution where a user can create a challenge/F2F/assigned task and schedule it to be launched at some date in the future for all timeline template types.

**Comment by sandhiyakavi** [comment]
Verified on Prod.

![image](https://user-images.githubusercontent.com/55895538/99761585-cef19080-2b39-11eb-9e93-a3187ca6efd6.png)
