### ISSUE TITLE
Primary Set-Up UI: "Basic Details" Section

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#735]
### Designs
[Desktop](https://marvelapp.com/prototype/5j0f3f7/screen/75850927) I [Mobile](https://marvelapp.com/prototype/fh8dhd1)

**Header of Section**
- Section Title: "Basic Details"

_Field 1 is a required question/answer._
_Field 1:_ "Type"
_Field 1 Answers [Buttons]:_
-Design
-Development
-Quality Assurance
-Data Science

_Field 2 is a required question/answer._
_Field 2:_ "Format"
_Field 2 Answers [Dropdown Menu]:_
-Challenge
-First2Finish
-Task

_Field 3 is a required question/answer._
_Field 3:_ "Title"
_Field 3 Answer:_ [Free Text Field]

**Comment by maxceem** [comment]
1. Should we hardcode the list of possible terms to choose or use some API endpoint to get such a list?

    ![image](https://user-images.githubusercontent.com/146016/99941478-c1751a00-2d76-11eb-94e5-ae83d86252fd.png)

**Comment by vikasrohit** [comment]
I am not sure about it. I guess @rootelement can guide us here. @rootelement last time when I tried to fetch all available terms, it required me to be an administrator. So, I am not sure if we have the endpoint for fetching the publicly available terms.

**Comment by vikasrohit** [comment]
@acshields we need your input as well.

**Comment by vikasrohit** [comment]
@ajefts closing this and similar for now to clean up things.
