### ISSUE TITLE
Add "Provide Application Feedback" Capability to Work Manager App

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#746]
### Update 1
On the 'all projects dashboard' of challenges.topcoder.com, add a button in the left sidebar with these details:
- Label the button: "Give Application Feedback"
- This button should clickable, but it will not trigger any additional application actions. Instead, this button will serve as an anchor and trigger for a Chameleon survey where the user can provide and submit application feedback.
- This button should be viewable to all application users.

### Update 2
On the 'all projects dashboard' of challenges.topcoder.com, underneath the "Give Application Feedback" button in the left sidebar, include the following:
- Text that reads: "Have an urgent issue?"
- Text that reads: "E: support@topcoder.com"
- This should be viewable to all application users.

### Update 3
In challenge/task set-up screens, add the following in the left sidebar:
- Add a button
- Label the button: "Give Application Feedback"
- This button should clickable, but it will not trigger any additional application actions. Instead, this button will serve as an anchor and trigger for a Chameleon survey where the user can provide and submit application feedback.
- This button should be viewable to all application users.

### Update 4
In challenge/task set-up screens, underneath the "Give Application Feedback" button in the left sidebar, include the following:
- Text that reads: "Have an urgent issue?"
- Text that reads: "E: support@topcoder.com"
- This should be viewable to all application users.

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/94169646-ab210f80-fe54-11ea-8b82-0742c0b2837c.png)

![image](https://user-images.githubusercontent.com/42398485/94169699-bb38ef00-fe54-11ea-8c69-a66b8e6e8f2c.png)

**Comment by vikasrohit** [comment]
> Hope the action is going to be implemented later

Yep, it is externally plugged into the button.

**Comment by acshields** [comment]
@vikasrohit Per my Slack message, I just discovered that Chameleon is not going to be able to support the required survey experience.

In order to support the goal of collecting App Feedback from users, I have now created a Google Form (https://forms.gle/CsaVawSDkdR5E92B8) that I would like hyperlinked to this "App Feedback" button. Please update this button functionality so that once clicked, it opens the hyperlinked Google Form.

**Comment by vikasrohit** [comment]
Done. Deployed to dev, will move to prod with next prod push.

**Comment by sandhiyakavi** [comment]
Verified on Prod. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/99650216-7b7b3600-2a98-11eb-9276-f878f051a820.png)

[issue#746.zip](https://github.com/topcoder-platform/work-manager/files/5565901/issue.746.zip)
