### ISSUE TITLE
Update "Launch Confirmation" Copy

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#747]
Please update the copy in on the "Launch Confirmation" pop-up window to read: 
Header: "Confirm Launch"
Sub-Text: "Do you want to launch [Title of Challenge/Task]?"

<img width="954" alt="Screen Shot 2020-08-11 at 12 29 29 PM" src="https://user-images.githubusercontent.com/41118149/89929268-a3701900-dbce-11ea-9ffa-c09313c7f8bb.png">

**Comment by vikasrohit** [comment]
@acshields do you want the challenge title to be in quotes or something?

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/92645677-cfa0b780-f2aa-11ea-8a98-06988a1a20ba.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod.working as expected.

![image](https://user-images.githubusercontent.com/55895538/99650608-f80e1480-2a98-11eb-9c6e-0e7d3776a30f.png)
