### ISSUE TITLE
Quick links for Direct and OR in Challenge View

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#757]
As of now we have the link to Direct and OR only on the challenge listing page. Though it is useful, but after the release of v5 to production, people might need a way to locate legacy challenge for a v5 challenge through Challenge Manager. So, it might be a good idea to add these two quick links in the read only view of the challenge to allow users to just hit the deep link with v5 challenge id and go to the direct or OR as needed.

thanks @RiteshTC for the suggestion.

**Comment by vikasrohit** [comment]
Yes, @codejamtc. I have intentionally did that as I found it useful from edit screen as well, though it caused them to be rendered on the challenge creation screen as reported by #775 which we would handle separately.

**Comment by sandhiyakavi** [comment]
Verified on Prod .Working as expected.

[issue#757.zip](https://github.com/topcoder-platform/work-manager/files/5565981/issue.757.zip)
