### ISSUE TITLE
Empty list of challenges

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/work-manager#760]
**Describe the bug**
All the list of challenges are empty even though I've created several challenges in the project. 

**To Reproduce / Actual Behavior**
1. Login at DEV env https://challenges.topcoder-dev.com/ via `pshah_manager` user.
2. Choose any project, for example, this one https://challenges.topcoder-dev.com/projects/16598/challenges
3. Launch a new challenge in this project `Draft` or even `Active`
4. Come back to the challenge list page, and observe that all lists of challenges are empty in all statuses, even though a new challenge has been created. For example, here is a couple challenges I've created in this project but they are not listed for me: https://challenges.topcoder-dev.com/projects/16598/challenges/f75f17f8-644f-4260-9311-a8802fe63d18/view and https://challenges.topcoder-dev.com/projects/16598/challenges/404cdeb1-e976-4517-88f8-0215bd2110be/view

**Expected behavior**
All the challenges should be listed.

**Screenshots**
List of draft challenges is empty:

![image](https://user-images.githubusercontent.com/146016/90632139-97b6cf00-e22c-11ea-9973-131aa3d820d1.png)

But there is an existent draft challenge:

![image](https://user-images.githubusercontent.com/146016/90631955-47d80800-e22c-11ea-8dae-132a92b3d2c9.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by maxceem** [comment]
The same when I'm using a copilot user `pshah_copilot`:
- Cannot see challenges listed in the project https://challenges.topcoder-dev.com/projects/16599/challenges
- But there is a `Draft` challenge https://challenges.topcoder-dev.com/projects/16599/challenges/6cb0c1e6-cf5f-4160-84c5-7485718a5981/view

**Comment by vikasrohit** [comment]
@maxceem we can close this one, right? (with known limits for tasks not being returned if they are assigned to other users)

**Comment by maxceem** [comment]
Yes, @vikasrohit. Now I can see challenges by a non-admin user.

**Comment by drasticdpk** [comment]
Verified on Dev env.
@vikasrohit  I am having same issue on prod, it is yet to deploy on prod ? Please confirm.

**Comment by vikasrohit** [comment]
@maxceem I saw some changes pushed to challenge api today which includes fixes to the search query for tasks which in turn seems to fix the other part of the problem where we were not able to see the tasks for the user `pshah_manager`. Please verify if that is fixed as per our expectation.

**Comment by vikasrohit** [comment]
> Verified on Dev env.
> @vikasrohit I am having same issue on prod env, is it yet to deploy on prod env ? Please confirm.

I think with today's push for challenge api to production, it should be fixed on production now as well.

**Comment by maxceem** [comment]
@vikasrohit the part for the assigned tasks is not fixed for me.

The next URL returns only 1 task **Task 2**
https://api.topcoder-dev.com/v5/challenges?sortBy=updated&sortOrder=desc&projectId=7977&status=Draft&page=1&perPage=50

But there is also one more task **Task 3 (assigned)** and it is not returned because it has `task.isAssigned` flag set together with `task.memberId`.

**Comment by vikasrohit** [comment]
> @vikasrohit the part for the assigned tasks is not fixed for me.
> 
> The next URL returns only 1 task **Task 2**
> https://api.topcoder-dev.com/v5/challenges?sortBy=updated&sortOrder=desc&projectId=7977&status=Draft&page=1&perPage=50
> 
> But there is also one more task **Task 3 (assigned)** and it is not returned because it has `task.isAssigned` flag set together with `task.memberId`.

@rootelement @ThomasKranitsas fyi, it seems the latest fix for tasks query, does not fix the part 2 of the problem raised in this issue.

**Comment by sandhiyakavi** [comment]
Verified on Prod.Working as expected.
