### ISSUE TITLE
Markdown Preview 

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#765]
Enable a user to preview the public and private specifications in markdown, by clicking a "Preview" button by each specification field.

**Comment by vikasrohit** [comment]
@acshields there is already a Preview button in the editor which shows the markdown preview and in fact in non preview mode, it shows the actual formatting of the text as per markdown command e.g. just try to enter `#` and you would notice that it made the text a page heading, trying `##` would make second to page heading and so on. Do you need any thing else here?

**Comment by vikasrohit** [comment]
@acshields https://github.com/topcoder-platform/work-manager/issues/765#issuecomment-688656799

**Comment by acshields** [comment]
@vikasrohit - Nope, we are good for now. We can close this one and remove it from the project.
