### ISSUE TITLE
Enable Private Specification

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#766]
Enable the Private Specification markdown field.

- This field should be displayed in the "Work Specifications Section" underneath the Public Specification.
- Private Specification should only be viewable to users who have registered for the challenge/task.

**Comment by vikasrohit** [comment]
@acshields I don't get the condition for displaying private specs. I mean I get this condition (only registered members for the challenge/task) can see the private specs on the community site but in Challenge Manager, I don't we should be allowing registered members to even view a challenge, only copilot of the challenge/task and admins should be able to view challenge. And that is automatically taken care by projects api authorization system as members registered for a challenge are never added to the Connect project and one can not view challenge in Challenge Manager without being part of the project.
However, important thing to note is that right now this validation is not enforced at every page of the app which makes it vulnerable to show a challenge to a participant of the challenge by directly opening a deep link.

**Comment by vikasrohit** [comment]
@acshields please let us know what do you think about display condition https://github.com/topcoder-platform/work-manager/issues/766#issuecomment-682398070

**Comment by acshields** [comment]
@vikasrohit - my apologies for the lack of clarity around the second requirement. I don't think that this is something we need to worry about in the front-end of Work Manager. 

What I meant was that in the Challenge Listings, the private specification will only be viewable to users after they have registered for the challenge. I believe James already has this condition set-up, so nothing for you worry about (I had written this spec months ago before James had that work completed, so I was just documenting that requirement here). 

For the Work Manager front-end, you can reference the designs on placement. Essentially, how this would operate:
In the "Specification" section of Work Manager, the "Public Specification" would initially be displayed. Underneath this field, there is a "Private Specification" button with support text describing the difference in this spec. When that button is clicked, a second field for Private Specification will appear.

**Comment by lakshmiathreya** [comment]
Private Specification is now enabled in setup page.
![Uploading Screenshot 2020-12-07 at 8.37.50 PM.png…]()
