### ISSUE TITLE
Information is not visually updated after clicking "Save" button.

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/work-manager#767]
ChallengeEditor component to reflect the updated information of the challenge after `Save` operation. As of now it does not update the UI and you have to refresh the page. That is happening because it is not using the redux state correctly. It was using unmount/unlisten event handlers earlier which I removed to avoid non standard practices.

**Comment by maxceem** [comment]
@vikasrohit done via PR https://github.com/topcoder-platform/challenge-engine-ui/pull/768

**Comment by sandhiyakavi** [comment]
Verified on Prod.Working as expected.

![image](https://user-images.githubusercontent.com/55895538/99656814-b7b29480-2aa0-11eb-84cc-eaf1e0907edb.png)
