### ISSUE TITLE
No space between the buttons (Direct/Online Review) and (Edit/Back)

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#772]
![image](https://user-images.githubusercontent.com/42398485/91760810-988b2180-eb99-11ea-942a-619965e2e20b.png)

### Steps to reproduce the problem

- Open https://challenges.topcoder-dev.com/ and login as Admin
- Select a project from the list 'Test v5 {codejam} - 0001'
- Go to the Draft Tab
- Select a Task, Challenge or F2F of the QA Track
- Check the buttons (Direct/Online Review) and (Edit/Back)

### Actual behavior
- No space between the buttons (Direct/Online Review) and (Edit/Back)

### Expected behavior
- Should have a small space between the buttons (Direct/Online Review) and (Edit/Back)

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Admin
**- Account used:**  `TonyJ`

**Comment by vikasrohit** [comment]
I think we won't fix it because we have to implement a new better designs anyway. But still keeping it in next release to keep track of it.

**Comment by acshields** [comment]
@vikasrohit - I agree with logging this in October project for tracking purposes, and our new UI/UX should resolve this.

**Comment by maxceem** [comment]
Done by https://github.com/topcoder-platform/work-manager/pull/919

![image](https://user-images.githubusercontent.com/146016/100453676-07f2ad80-30c4-11eb-85e8-4d217294e476.png)

**Comment by lakshmiathreya** [comment]
Verified in Prod.
<img width="1680" alt="Screenshot 2020-12-07 at 8 45 53 PM" src="https://user-images.githubusercontent.com/51733042/101368504-3bf07e80-38cd-11eb-992b-6b613bc9a291.png">
