### ISSUE TITLE
Challenge name is not updated on the table after editing it

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#774]
[3.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5152566/3.zip)

### Steps to reproduce the problem

- Open https://challenges.topcoder-dev.com/ and login as Admin
- Select a project from the list 'Test v5 {codejam} - 0001'
- Go to Draft Tab and click on a challenge
- Click 'Edit'
- Change the challenge name and click Save Draft
- Click 'View Challenge' from the popup
- Click 'Back' 
- Check the name on the table

### Actual behavior
- Challenge name is not updated on the table after editing it

### Expected behavior
- Should update the name on the table

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Admin
**- Account used:**  `TonyJ`

**Comment by vikasrohit** [comment]
@maxceem I think it is related to the fix we made for stale UI reported in https://github.com/topcoder-platform/challenge-engine-ui/issues/767. I think it should be quick fix, if it takes more time because it requires lot of refactoring, then I would move it to the next release.

**Comment by codejamtc** [comment]
@maxceem @vikasrohit Is the fix https://github.com/topcoder-platform/challenge-engine-ui/issues/767 already deployed to the `development` environment?

**Comment by vikasrohit** [comment]
yes

**Comment by codejamtc** [comment]
@vikasrohit After editing I still can't see the edited data on the details page

**Comment by vikasrohit** [comment]
It might be a temporary glitch while I was trying another build to be deployed in dev which does not have those changes. But as of now it seems to be working fine for me. Can you please try again?

**Comment by maxceem** [comment]
@vikasrohit there is another related issue which causes functionality implemented in this issue to break https://github.com/topcoder-platform/challenge-engine-ui/issues/798. Would like me to also fix the issue during creating?

**Comment by vikasrohit** [comment]
Yes, please. Thanks for identifying the bug.

**Comment by sandhiyakavi** [comment]
Verified on Prod.Working as expected.

[issue#774.zip](https://github.com/topcoder-platform/work-manager/files/5572163/issue.774.zip)
