### ISSUE TITLE
Should remove 'Direct/Online Review' from the Create New Work page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#775]
![image](https://user-images.githubusercontent.com/42398485/91774856-5ff64280-ebaf-11ea-8b4f-68a4e545f88a.png)

### Steps to reproduce the problem

- Open https://challenges.topcoder-dev.com/ and login as Admin
- Select a project from the list 'Test v5 {codejam} - 0001'
- Click 'Launch New'
- Click 'Direct/Online Review'

### Actual behavior
- No use of 'Direct/Online Review' links on the Create New Work page

### Expected behavior
- Should remove 'Direct/Online Review' from the Create New Work page

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Admin
**- Account used:**  `TonyJ`

**Comment by acshields** [comment]
@vikasrohit - agreed that these buttons should be removed at this stage of set-up.

**Comment by vikasrohit** [comment]
@maxceem can we wrap this one for November release?

**Comment by maxceem** [comment]
Done by https://github.com/topcoder-platform/work-manager/pull/918

**Comment by lakshmiathreya** [comment]
Verified removal of Direct/OR buttons in New Work flow.
<img width="1680" alt="Screenshot 2020-12-07 at 8 41 01 PM" src="https://user-images.githubusercontent.com/51733042/101367962-9806d300-38cc-11eb-887e-bd9a05aa9751.png">
