### ISSUE TITLE
"Please fix the errors before saving" is displayed when user tries to activate the challenge but can't figure out the field that has the error

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#776]
![image](https://user-images.githubusercontent.com/42398485/91776183-781b9100-ebb2-11ea-8465-e4efb5a9a196.png)

[5.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5152980/5.zip)

### Steps to reproduce the problem

- Open https://challenges.topcoder-dev.com/ and login as Admin
- Select a project from the list 'Test v5 {codejam} - 0001'
- Go to Draft and select a QA Task 
- Click 'Edit' https://challenges.topcoder-dev.com/projects/16604/challenges/f6741d0c-94e8-41fd-9037-91614aa2e4a3/edit
- Click 'Launch as Active'

### Actual behavior
- "Please fix the errors before saving" is displayed when user tries to activate the challenge but can't figure out the field that has the error

### Expected behavior
- Should highlight or should mention the field that has the error

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Admin
**- Account used:**  `TonyJ`

**Comment by vikasrohit** [comment]
@codejamtc @drasticdpk this can be tested in dev now as there is a fix applied in dev for migration script which was messing with the `timelineTemplateId`.

**Comment by codejamtc** [comment]
This specific issue is fixed on `dev`

**Comment by sandhiyakavi** [comment]
Verified on Prod. Not getting this error now.
