### ISSUE TITLE
"Prize amounts should be from 0 to 1000000" is not display near the Prize field

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#777]
![image](https://user-images.githubusercontent.com/42398485/91776366-e2343600-ebb2-11ea-8416-70d6f5ca26bc.png)

### Steps to reproduce the problem

- Open https://challenges.topcoder-dev.com/ and login as Admin
- Select a project from the list 'Test v5 {codejam} - 0001'
- Go to Draft and select a QA Task 
- Click 'Edit' https://challenges.topcoder-dev.com/projects/16604/challenges/f6741d0c-94e8-41fd-9037-91614aa2e4a3/edit
- Remove the Prize field data
- Click 'Launch as Active'

### Actual behavior
- "Prize amounts should be from 0 to 1000000" is not display near the Prize field

### Expected behavior
- Should display near the field as other messages

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Admin
**- Account used:**  `TonyJ`

**Comment by codejamtc** [comment]
"Prize amounts should be from 0 to 1000000" validation message is removed now only the "Prize amount is required field" displayed near the field  🆗

**Comment by sandhiyakavi** [comment]
Verified on Prod. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/99658257-9357b780-2aa2-11eb-96dd-7c7b20d79a16.png)
