### ISSUE TITLE
Sometimes user can save a draft without a Public specification

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#778]
![image](https://user-images.githubusercontent.com/42398485/91776760-b6fe1680-ebb3-11ea-94fa-340cfd3e0f2f.png)

[6.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5153006/6.zip)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Admin
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Go to Draft and select a QA Task 
4. Click 'Edit' https://challenges.topcoder-dev.com/projects/16604/challenges/f6741d0c-94e8-41fd-9037-91614aa2e4a3/edit
5. Remove the Public specification data
6. Click 'Save Draft' (Validation: Public Specification is required)
7. Remove the Public specification data
8. Click 'Back'
9. Select the same task in Step 03
10. Check the Public specification data

### Actual behavior
- Sometimes user can save a draft without a Public specification

### Expected behavior
- Should display the old specification in this case

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Admin
**- Account used:**  `TonyJ`

**Comment by maxceem** [comment]
This wouldn't happen now because API doesn't allow empty `description` anymore. But there is still incorrect behavior of the UI too. So this might also happen for other fields.

There are 2 issues:
- When we change the description **autosave** works and it saves the challenge without validation. 
- When we click **Save Draft** the request is sent to the server even though the form is invalid.

See demo video https://monosnap.com/file/8aY31JrKdH6amj65t0fWmJXt3gRw2E

@vikasrohit what do you think we should do with autosave when the user cleans the description?
1. Should we silently skip autosaving if the form is invalid?
2. Should we show validation errors immediately when the user edits the form and autosave works?

**Comment by vikasrohit** [comment]
@maxceem I think we can show validation error on edit in challenge description to prevent this situation because we are already showing other validation errors immediately after the form is dirty.

**Comment by vikasrohit** [comment]
@codejamtc fyi, we are not able to reproduce the original issue and we are working on missing validation case for auto saving. If you are still able to reproduce original issue, please let us know.

**Comment by vikasrohit** [comment]
@drasticdpk @lakshmiathreya Can we try to reproduce it with original steps? We are not able to reproduce it but we have identified one missing validation error situation which might confuse users, so we would fix that if the original one is not reproducible.

**Comment by vikasrohit** [comment]
@maxceem can you please add validation error for the patch call as well?

**Comment by maxceem** [comment]
> can you please add validation error for the patch call as well?

Do you mean add validation to `PATCH` request server side?

Or do you mean show validation error when `auto-save` is triggered?

**Comment by vikasrohit** [comment]
I mean show validation error when auto-save is triggered.

**Comment by drasticdpk** [comment]
@vikasrohit  yes I can replicated with given steps. 
Findings : Auto save , updated as empty text then there is required validation.
In video, we can see there is no text in public specification while editing the challenge.  

![image](https://user-images.githubusercontent.com/25297859/101493102-b41e7900-398d-11eb-86bd-25c742d14a1b.png)

In prod: 

https://challenges.topcoder.com/projects/24943/challenges/27251d7f-bfa1-4761-be13-e011125a441b/view
![image](https://user-images.githubusercontent.com/25297859/101493188-d0bab100-398d-11eb-8406-cc7cc9a5701a.png)

**Comment by vikasrohit** [comment]
Thanks @drasticdpk. @maxceem I think you said that challenge api does not allow empty description, so how can patch set the empty description? Or are we missing the validation for PATCH but have it for POST/PUT?

**Comment by maxceem** [comment]
@vikasrohit hmm, I've checked it again and `description` is not required in Challenge API, though I remember getting validation errors from API.

Anyway, we would add client-side validation for auto-save, and it this issue should got fixed.

**Comment by maxceem** [comment]
@vikasrohit one question.

After adding validation, I can see that our validation allows spaces `    ` it treats it as non-empty value. This is a common issue, not only for autosaving. 
Should we treat spaces as a value entered or no?

**Comment by maxceem** [comment]
Validation for autosave is added by https://github.com/topcoder-platform/work-manager/pull/952

**Comment by drasticdpk** [comment]
1. System is taking space char.

**Reference** 

![image](https://user-images.githubusercontent.com/25297859/101867593-9dea0600-3ba3-11eb-801a-b9de515875dc.png)

**Comment by vikasrohit** [comment]
@maxceem can we trim the content for validation?

**Comment by maxceem** [comment]
> can we trim the content for validation?

@vikasrohit create a new PR for that https://github.com/topcoder-platform/work-manager/pull/982

**Comment by lakshmiathreya** [comment]
Verified on Prod. WM validates Public Spec field at Save time...
<img width="1680" alt="Screenshot 2020-12-16 at 5 12 59 PM" src="https://user-images.githubusercontent.com/51733042/102344558-17c62900-3fc2-11eb-98f0-83306029c30b.png">
