### ISSUE TITLE
No basic validation displayed for mandatory fields such as Prize, Tag and Public specification

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#779]
[7.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5153088/7.zip)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Admin
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Click 'Launch New'
4. Select Work Type=Design; Format=Challenge; Name=Test
5. Click 'Continue Set-Up'
6. Click 'Save Draft'

### Actual behavior
- No basic validation displayed for mandatory fields such as Prize and Public specification while creating a challenge

### Expected behavior
- Should display validations, When editing you will see validations

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Admin
**- Account used:**  `TonyJ`

**Comment by vikasrohit** [comment]
<img width="715" alt="Screen Shot 2020-09-08 at 12 16 53 PM" src="https://user-images.githubusercontent.com/2417632/92442262-318aef80-f1cd-11ea-8c28-f0e873a51fd5.png">
@maxceem it seems the validation is always visible no matter if user has altered the field or not. We don't have this behaviour for any other field.

**Comment by maxceem** [comment]
@vikasrohit yeah, validation inside this component was implemented like this, I've just added one more rule so it's now revealed its behavior. I can fix it to behave like other components.

**Comment by maxceem** [comment]
@vikasrohit this https://github.com/topcoder-platform/challenge-engine-ui/issues/779#issuecomment-688655529 is fixed via https://github.com/topcoder-platform/challenge-engine-ui/pull/797

**Comment by sandhiyakavi** [comment]
Verified on Prod.
![image](https://user-images.githubusercontent.com/55895538/99777288-6c0df280-2b55-11eb-82d9-624f1c760630.png)
![image](https://user-images.githubusercontent.com/55895538/99777376-86e06700-2b55-11eb-85cc-5d5993050b06.png)

This issue  https://github.com/topcoder-platform/work-manager/issues/779#issuecomment-688655529 exists

**Comment by sandhiyakavi** [comment]
This issue #779 (comment)  tracked separately in https://github.com/topcoder-platform/work-manager/issues/910
