### ISSUE TITLE
Can add duplicates to the Final Deliverables 

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#781]
![image](https://user-images.githubusercontent.com/42398485/91886091-73a4b600-ec4e-11ea-82fb-5f326b86607d.png)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Admin
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Click 'Launch New'
4. Select Work Type=Design; Format=Challenge; Name=Test
5. Click 'Continue Set-Up'
6. Go to 'Final Deliverables'
7. Enter "JPG' and click 'Add File Type' button
8. Enter "JPG' and click 'Add File Type' button
9. Try to select 'JPG'

### Actual behavior
- Can add duplicates to the Final Deliverables. Even after adding the deliverable, only one can be selected

### Expected behavior
- Should not allow duplicates on Final Deliverables

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Admin
**- Account used:**  `TonyJ`

**Comment by vikasrohit** [comment]
It has been fixed with https://github.com/topcoder-platform/challenge-engine-ui/issues/782#issuecomment-698446188.

**Comment by vikasrohit** [comment]
fyi, it is still case insensitive i.e. it would allow `jpg` and `JPG` both.

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/94324318-ee67a500-ff5e-11ea-94e7-4f4349adf7d3.png)

**Comment by maxceem** [comment]
Fixed via https://github.com/topcoder-platform/challenge-engine-ui/pull/841

**Comment by vikasrohit** [comment]
@codejamtc can you please do a quick test if things are working as expected after this fix? Changes are in dev now.

**Comment by sandhiyakavi** [comment]
Verified on Prod. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/99778768-77621d80-2b57-11eb-9c1e-1c67fc8f8c3b.png)
