### ISSUE TITLE
Final Deliverables are not getting saved

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#782]
[8.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5158325/8.zip)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Admin
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Click 'Launch New'
4. Select Work Type=Design; Format=Challenge; Name=Test
5. Click 'Continue Set-Up'
6. Go to 'Final Deliverables'
7. Enter "JPG' and click 'Add File Type' button
8. Enter "BMP' and click 'Add File Type' button
9. Click 'Save Draft'
10. Click 'View Challenge'
11. Click 'Back'
12. Open the same challenge 

### Actual behavior
- Final Deliverables are not getting saved

### Expected behavior
- Should have the Final Deliverables added by the user

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Admin
**- Account used:**  `TonyJ`

**Comment by maxceem** [comment]
@vikasrohit this data is not being saved yet to API. As per swagger, there is no special place for final deliverables or file types.
Should we put it to `metadata`? Can we name as we want, or is there any specification for this?

**Comment by vikasrohit** [comment]
Yes, I think we need to use `metadata` for that, but I am not sure if there is a defined key for that. If that information is not in swagger, we need help from @rootelement for this.

**Comment by rootelement** [comment]
Please see here:
https://github.com/topcoder-platform/challenge-engine-ui/issues/783#issuecomment-696231835

**Comment by maxceem** [comment]
@vikasrohit using the comment from above I found an example of challenge with such data in PROD:

![image](https://user-images.githubusercontent.com/146016/93870963-9cace980-fcd6-11ea-9849-5ebbc83ea34e.png)

The only thing the current UI seems like doesn't suit well to what we need:

![image](https://user-images.githubusercontent.com/146016/93871150-dd0c6780-fcd6-11ea-8da1-bb33244ffa2e.png)

We have to be able to **add** and **remove** file types. At the moment when we add a file type it's added with a checkbox, which seems like doesn't bring any value.
I suggest removing the checkboxes, and add `-` or `x` button instead for each item, which would remove the file type.

**Comment by vikasrohit** [comment]
@maxceem are we setting `fileTypes` in the metadata?

> We have to be able to add and remove file types. At the moment when we add a file type it's added with a checkbox, which seems like doesn't bring any value.

Does checking and then unchecking the checkbox not delete the file type?

> I suggest removing the checkboxes, and add - or x button instead for each item, which would remove the file type.

If checkbox is doing its purpose, we can use this way for no.

**Comment by maxceem** [comment]
@vikasrohit 

> are we setting fileTypes in the metadata?

Not yet, this has to be fixed.

> Does checking and then unchecking the checkbox not delete the file type?

No, it doesn't.

> If checkbox is doing its purpose, we can use this way for no.

It feels that using checkboxes is misleading here. In the metadata, we can only store the list of data types, we don't have a way to store if type is checked or no, only if it present or no.

**Comment by vikasrohit** [comment]
Ok, go with the suggested approach.

**Comment by maxceem** [comment]
@vikasrohit this is done via PR https://github.com/topcoder-platform/challenge-engine-ui/pull/831

- Now data is being saved to the API:

    ![image](https://user-images.githubusercontent.com/146016/94171786-5acca080-fe9a-11ea-9302-e6bfce1a7e09.png)

- Edit mode looks similar to tags:

   ![image](https://user-images.githubusercontent.com/146016/94171611-21943080-fe9a-11ea-81e6-34411e47a017.png)

   - Don't allow to add empty values.
   - Don't allow to add duplicates.

- View mode has a simple output:

   ![image](https://user-images.githubusercontent.com/146016/94171820-66b86280-fe9a-11ea-896b-debdc2cae8f8.png)

**Comment by vikasrohit** [comment]
Thanks @maxceem that is perfect. Only small thing, it is still case insensitive i.e. it is allowing jpg and JPG both.

**Comment by maxceem** [comment]
Fixed via https://github.com/topcoder-platform/challenge-engine-ui/pull/841

**Comment by sandhiyakavi** [comment]
Verified on Prod. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/99779206-138c2480-2b58-11eb-8136-8aad42c9eadc.png)
