### ISSUE TITLE
Can enter decimals into 'Maximum Number of Submissions' 

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#784]
![image](https://user-images.githubusercontent.com/42398485/91899297-8b863500-ec62-11ea-8c0f-8f500ddb2e00.png)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Admin
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Click 'Launch New'
4. Select Work Type=Design; Format=Challenge; Name=Test
5. Click 'Continue Set-Up'
6. Set Maximum Number of Submissions : 50.5
7. Click Save Draft

### Actual behavior
- Can enter decimals into 'Maximum Number of Submissions' 

### Expected behavior
- Should restrict decimals

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Admin
**- Account used:**  `TonyJ`

**Comment by maxceem** [comment]
Also can enter any text:

![image](https://user-images.githubusercontent.com/146016/100596419-d0267880-3304-11eb-87b9-2c97caaa58d0.png)

![image](https://user-images.githubusercontent.com/146016/100596381-c866d400-3304-11eb-8dfe-509c3eaad4d6.png)

**Comment by maxceem** [comment]
Done via https://github.com/topcoder-platform/work-manager/pull/921/files

- Only allow entering numbers during the challenge editing.

**Comment by lakshmiathreya** [comment]
Field validation verified in Prod - only numbers allowed now.
