### ISSUE TITLE
Click on the edit button will update the 'Last Saved' Date and time

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#785]
[9.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5158577/9.zip)

![image](https://user-images.githubusercontent.com/42398485/91901579-0dc42880-ec66-11ea-9f9d-c128bcdb95fc.png)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Admin
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Click on a very old challenge
4. Click Edit
5. Check the 'Last Saved' Date and time 

### Actual behavior
- Click on edit button will update the 'Last Saved' Date and time

### Expected behavior
- Should update after creating the Save Draft or Launch as Active button; until then should display the old date

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Admin
**- Account used:**  `TonyJ`

**Comment by vikasrohit** [comment]
@codejamtc I think search is working as expected. It searches for anything with the text. I can random text in the description of project `qq` and that random text has `ok` multiple times.

**Comment by codejamtc** [comment]
@vikasrohit Your comment is related https://github.com/topcoder-platform/challenge-engine-ui/issues/787?

**Comment by sandhiyakavi** [comment]
Verified on Prod. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/99756349-48848100-2b30-11eb-8b67-2aaa1f757d0b.png)
