### ISSUE TITLE
Can enter '$0' as the Challenge Prizes even though the validation is displayed as "Prize amount must be more than zero"

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#786]
[10.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5158614/10.zip)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Admin
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Create a Design challenge
4. Enter Prize 1=100; > Click 'Add New Prize' > Enter Prize 2=50 > Click 'Add New Prize'
5. Change the Prize 03=$0 (You can see the validation "Prize amount must be more than zero")
6. Click 'Save Draft'

### Actual behavior
- Can enter '$0' as the Challenge Prizes even though the validation is displayed as "Prize amount must be more than zero"

### Expected behavior
- Sometimes we need to set $0 for the challenges so this may be required but there is a validation shown "Prize amount must be more than zero" If this is allowed we should remove the validation

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Admin
**- Account used:**  `TonyJ`

**Comment by vikasrohit** [comment]
@codejamtc I didn't understand the issue fully. Are you suggesting that we should support setting 0 as prize money OR are you saying that you are able to set 0 as prize money despite the validation error being shown?

**Comment by codejamtc** [comment]
@vikasrohit Able to set 0 as prize money despite the validation error being shown

**Comment by vikasrohit** [comment]
@maxceem I moved this one from October to September release just because you already some validation fixes for the same field in #777 and assuming that it might be quick fix which we can wrap early.

**Comment by maxceem** [comment]
@vikasrohit yes, I've already fixed this issue as a part of #777. So I'm marking it as Ready for QA.

**Comment by sandhiyakavi** [comment]
Verified on Prod. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/99756845-5daddf80-2b31-11eb-88ed-4136307aa676.png)
