### ISSUE TITLE
Challenge is not added to the list after creating

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/work-manager#798]
Related to https://github.com/topcoder-platform/challenge-engine-ui/issues/774

### Steps to reproduce the problem

- Open https://challenges.topcoder-dev.com/ and login as Admin
- Select a project from the list 'Test v5 {codejam} - 0001'
- Go to **New Tab**
- Click **Launch New**
- Fille Challenge Type, Format and Name (any values)
- Click **Continue Set-Up**
- Now click **Back** button to go back to the list
- Observe that new challenge is not added to the list and we have to reload the page first to see it (or click another tab and then come back to the New Tab again to force reloading)

### Actual behavior
- Challenge is not added to the list after creating

### Expected behavior
- Challenge is added to the list after creating immediately

Demo video [screencast 2020-09-09 11-06-06.mp4.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5193593/screencast.2020-09-09.11-06-06.mp4.zip)

**Comment by vikasrohit** [comment]
Good catch @maxceem

**Comment by maxceem** [comment]
@vikasrohit done via PR https://github.com/topcoder-platform/challenge-engine-ui/pull/799

I've noticed more situations to take care of when we are updating the challenge: during updating the challenge, the challenge might change its status, so we might have to remove it from the challenge list or add it to the challenge list depends on the new status and tab filter. It's also included in the PR.

### Here are the test scenarios:

1. If we are on the `New` tab, and we create a new challenge, and we click `Back` **without** saving the draft, we should see a new challenge on the list.
2. If we are on the `New` tab, and we create a new challenge, and we are saving the challenge as `Draft`, and we click `Back`, we should NOT see the challenge on the list.
3. If we are on the `Draft` tab, and we create a new challenge, and we click `Back` **without** saving the draft, we should NOT see a new challenge on the list.
4. If we are on the `Draft` tab, and we create a new challenge, and we are saving the challenge as `Draft`, and we click `Back`, we should see the challenge on the list.

**Comment by vikasrohit** [comment]
Thanks @maxceem for that. However, if we would have the capacity to rewrite the code, I think we didn't need to handle these specific cases on adhoc basis, right? I mean if everything was handled via redux states, landing on the listing page would have refreshed the list automatically. I  don't remember we doing the similar adhoc handling in Connect.

**Comment by maxceem** [comment]
Yes, @vikasrohit all the various situations are already handled in the PR.

**Comment by vikasrohit** [comment]
> Yes, @vikasrohit all the various situations are already handled in the PR.

I just meant that the PR is not handling the various situations via adhoc code and instead it would require more changes to refactor the direct api calls to redux action so that all the situations are automatically taken care. And I found that the PR is doing as expected, so we are good.

**Comment by codejamtc** [comment]
[2.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5211336/2.zip)

**Comment by sandhiyakavi** [comment]
Verified on Prod. Working as expected.

[issue#798.zip](https://github.com/topcoder-platform/work-manager/files/5571255/issue.798.zip)
