### ISSUE TITLE
"Launch Challenge Confirmation" popup is not closed when user tries to activate a challenge/task or F2f from the listview

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#801]
[3.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5202060/3.zip)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Admin
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Click 'Activate' from the challenge
4. Click 'Confirm'

### Actual behavior
- "Launch Challenge Confirmation" popup is not closed when the user tries to activate a challenge/task or F2f from the listview

### Expected behavior
- Should clear the popup after successful activation

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Admin
**- Account used:**  `TonyJ`

**Comment by vikasrohit** [comment]
@codejamtc can you please share the console logs as well? I don't see them in the video.

**Comment by codejamtc** [comment]
@vikasrohit No console log entries while we are clicking on the submit button; log attached
[challenges.topcoder-dev.com-1599827157235.txt](https://github.com/topcoder-platform/challenge-engine-ui/files/5208907/challenges.topcoder-dev.com-1599827157235.txt)

**Comment by coderhacker** [comment]
This is passed production 

https://user-images.githubusercontent.com/62358241/119337426-6fbd3600-bcac-11eb-98d1-2b2339830303.mp4
