### ISSUE TITLE
Challenge phase is not updated in listing page

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#802]
Even though the Active challenge has a current active phase, the listing page always shows the challenge as stalled in the phase column.

<img width="923" alt="Screen Shot 2020-09-11 at 12 03 51 PM" src="https://user-images.githubusercontent.com/2417632/92875795-013e8d80-f427-11ea-9bc6-95b9a48a7953.png">

**Comment by vikasrohit** [comment]
fyi @acshields @lakshmiathreya as per our discussion in yesterday's call.

**Comment by vikasrohit** [comment]
@lakshmiathreya @drasticdpk @codejamtc Implemented showing basic phase details with current data model. The existing code was assuming very old data model that is why it was not showing correct phase details. It still might not be showing correct details for different phases and it has to be fixed as case are identified.

fyi @acshields

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/93600843-e4a1d880-f985-11ea-9476-626e23f45ca5.png)

**Comment by vikasrohit** [comment]
Closing as it is already verified on prod
