### ISSUE TITLE
'Work Type is required field' validation is not removed once the user selected a type from the list

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#810]
![image](https://user-images.githubusercontent.com/42398485/93114460-3bef3280-f680-11ea-8107-2783648236d0.png)

### Steps to reproduce the problem

1. Open https://challenges.topcoder.com/ and login as codejam
2. Select a project from the list 'Q2: Customer Experience Prod/Dev Delivery (Connect Projects)'
3. Click 'Launch New'
4. Click 'Continue Set-Up'
5. Fill the Type, Format, and Name and observe

### Actual behavior
- 'Work Type is required field' validation is not removed once the user selected a type from the list

### Expected behavior
- Should remove the validation

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `codejam`

**Comment by vikasrohit** [comment]
Applied fix in dev env.

**Comment by vikasrohit** [comment]
Closing as it is already verified on prod.
