### ISSUE TITLE
When user register and submit to a public challenge it is not updated on the WM challenge listing page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#813]
![image](https://user-images.githubusercontent.com/42398485/93238834-93a4a100-f747-11ea-88ad-ed937e28f979.png)

### Steps to reproduce the problem

1. Open https://challenges.topcoder.com/ and login as codejam
2. Select a project from the list 'Q2: Customer Experience Prod/Dev Delivery (Connect Projects)'
3. Create a draft challenge and Activate it
4. Go to Challenge specification and Register to it
5. Submit to the challenge
6. Go to WM and check the challenge register and submit count
 

### Actual behavior
- When user register and submit to a public challenge it is not updated on the WM challenge listing page

### Expected behavior
- Should update the Submission and Registration count

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `codejam`

**Comment by lakshmiathreya** [comment]
@vikasrohit @acshields - is this also out of scope for this month's release - as is Phase updates? pls clarify.

**Comment by vikasrohit** [comment]
yes, in my opinion. @acshields has final call. It would be a nice to have fix. I would try to apply a fix if it is quick one.

**Comment by vikasrohit** [comment]
Should be fixed now, I have applied a patch in dev but not have any challenge with the registrant and submissions data.

**Comment by vikasrohit** [comment]
Closing as it is already verified on prod
