### ISSUE TITLE
[Prod]Copilot Role is missing on Newly created challenge.

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#820]
**Steps**
1. Create new challenge from WM and launch it. 
2. Go to OR and observe the Role.

**Reference**
 
![image](https://user-images.githubusercontent.com/25297859/93447023-a4911600-f8f1-11ea-9ac9-0e5b1f6a3485.png)

**Finding**
1. Due to this issue, I am unable to update/edit challenge.
2. Forums is not updated/ Unable to open.

**Comment by drasticdpk** [comment]
Reference issue : 
https://github.com/topcoder-platform/challenge-engine-ui/issues/700
https://github.com/topcoder-platform/challenge-engine-ui/issues/689

**Comment by vikasrohit** [comment]
@drasticdpk which challenge is it? I am seeing copilots added as Copilots for https://challenges.topcoder.com/projects/24943/challenges/24a44f28-f28e-4679-afd9-984564f57789/view.

**Comment by vikasrohit** [comment]
fyi @lakshmiathreya @drasticdpk I have logged another issue https://github.com/topcoder-platform/legacy-challenge-resource-processor/issues/13 which might be causing the problems in dev env. But I didn't find the same problem happening in production.

**Comment by drasticdpk** [comment]
@vikasrohit,
I have selected my acc (drasticdpk) as copilot while  creating the challenge. Which is not reflected on OR.
https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30142424

**Comment by drasticdpk** [comment]
I have created new challenge but respective users (Copilot, Observer Manager etc)  are not reflected on OR. 
Challenge : https://challenges.topcoder.com/projects/24182/challenges/e8fafaa1-dc9a-4c7b-9c09-58bbfa0b3aa8/view

Reference :
![image](https://user-images.githubusercontent.com/25297859/93963288-79d51080-fd7c-11ea-8e81-00a1b713e262.png)
cc @lakshmiathreya @codejamtc

**Comment by vikasrohit** [comment]
@drasticdpk nothing has been fixed on production for copilot addition to the challenge. Please test it in dev. On production, we fixed the copilot addition in the project not in the challenge.

**Comment by vikasrohit** [comment]
@lakshmiathreya @codejamtc marking ready for QA because the underlying issue with legacy-challenge-resource-processor is supposed to be fixed now.

**Comment by drasticdpk** [comment]
Verified on Dev Env
![image](https://user-images.githubusercontent.com/25297859/94389122-b636b100-016e-11eb-84ee-f8b429ac86c1.png)

**Comment by drasticdpk** [comment]
Verified on Prod

![image](https://user-images.githubusercontent.com/25297859/101890879-69894080-3bc9-11eb-93f5-e00b9880c44d.png)
