### ISSUE TITLE
Copilot is not able to view a task after assigning to someone else

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#822]
Carried forward from https://github.com/topcoder-platform/challenge-engine-ui/issues/760#issuecomment-692525762 and https://github.com/topcoder-platform/challenge-engine-ui/issues/816#issuecomment-693995943. Affected users are copilots who can not view a task they created as soon as they assign it to someone else.

**Comment by vikasrohit** [comment]
fyi @rootelement @acshields

**Comment by ThomasKranitsas** [comment]
This issue has been fixed and now, a member who has access to a challenge with any role should be able to view the challenge.

With that being said, a resource for that member must exist. So, for a member to actually be the copilot of the challenge, you need to create a resource with the `roleId` `cfe12b3f-2a24-4639-9d8b-ec86726f76bd`.

Even if the `chalenge.createdBy` field has a value (eg the username of the copilot), that is not used in the search query as the access on challenges is managed using resources.

cc @rootelement

**Comment by vikasrohit** [comment]
@maxceem can you please check if it is now working for you?

**Comment by maxceem** [comment]
@vikasrohit I cannot assign any user to the task at the moment as I'm getting an error `The user has not yet agreed to the following terms: [Terms & Conditions of Use at TopCoder]` for any user.

I'm not sure how can we sign this terms for user in DEV. I wanted to register for some challenge, but page with challenges doesn't work on DEV now https://www.topcoder-dev.com/challenges - it gives an empty screen.

**Comment by vikasrohit** [comment]
@maxceem where you are seeing that error? I mean which API is sending that error back?

**Comment by ThomasKranitsas** [comment]
Yeah, I was also having the same issue yesterday but haven't tested today. This is happening when you call the Resources API to create a Submitter resource for a challenge.

**Comment by rootelement** [comment]
Strange. The regular challenges in dev:
https://qa-community-app.topcoder-dev.com/challenges/70dd4d6c-adca-4fb0-b0dc-617dc64b2148

Show the terms as:
`Standard Terms for TopCoder Competitions v2.2`

I was able to register for that challenge as jcori.

@vikasrohit what terms are you adding by default in dev? It should be:
`b11da5cd-713f-478d-90f4-f679ef53ee95`

**Comment by rootelement** [comment]
For posterity, challenge should be created with these term IDs from WM:
Standard Terms: `9ef9dec4-dddb-48c9-9cce-659db68bc5ac`
NDA: `876e9802-eb2c-4779-a2a8-8dd8e7fb783d`
For dev:
Standard Terms: `b11da5cd-713f-478d-90f4-f679ef53ee95`
NDA: `77f558c1-56fb-427c-b974-61ea0a060ca7`

**Comment by vikasrohit** [comment]
Okay @rootelement. Got it fixed for both env.

**Comment by vikasrohit** [comment]
@maxceem can you please now test it again?

**Comment by drasticdpk** [comment]
Unfortunately, challenge is not listed once it is assign to someone.

Reference:
Challenge: https://challenges.topcoder-dev.com/projects/9074/challenges/951ce398-5fae-43dc-8c50-da0ea9fd71d6/view
Copilot : topcoderconnect+copilot@gmail.com
Task assign To:  codejam
![image](https://user-images.githubusercontent.com/25297859/94408028-f52b2d80-0193-11eb-9dee-72dc59a419dc.png)

**Comment by vikasrohit** [comment]
@ThomasKranitsas @rootelement this one is still failing.

**Comment by ThomasKranitsas** [comment]
This has been fixed a couple of minutes ago. Can you please re-test?
For example:
https://challenges.topcoder-dev.com/projects/16531/challenges/3bdd2462-2471-4672-a45c-5f8e0c0f1ac9/view

can be seen in the listings:
<img width="1409" alt="Screenshot 2020-09-28 at 7 20 00 PM" src="https://user-images.githubusercontent.com/4612921/94459161-9e3b4d80-01bf-11eb-9cf3-fe8933b74180.png">

**Comment by vikasrohit** [comment]
@drasticdpk @codejamtc  Ready for QA

**Comment by drasticdpk** [comment]
Verified on Dev mode.
Reference:
![image](https://user-images.githubusercontent.com/25297859/94505675-5520e300-022b-11eb-82a5-9894f4138b14.png)
![image](https://user-images.githubusercontent.com/25297859/94505696-61a53b80-022b-11eb-9769-7d2489dcafe0.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod.Working as expected.
Challenge url: https://challenges.topcoder.com/projects/24943/challenges/276a292d-b16a-44dd-97f8-8b99315d8a94

![image](https://user-images.githubusercontent.com/55895538/99798671-bf436d80-2b74-11eb-801a-89a0e9a497b1.png)
![image](https://user-images.githubusercontent.com/55895538/99798735-da15e200-2b74-11eb-8954-ec3e6d03345b.png)
