### ISSUE TITLE
 "Member 23278999 is not a submitter resource of challenge 1b9b10a6-4771-4d53-a2bb-84c1695e4c3d" displayed when user tries to create a Task

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#828]
[3.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5268742/3.zip)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Admin
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Create a Dev Task challenge with all the details and save as draft

### Actual behavior
-  "Member 23278999 is not a submitter resource of challenge 1b9b10a6-4771-4d53-a2bb-84c1695e4c3d" displayed when user tries to create a Task

### Expected behavior
- Should not display such an error

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `copilot_codejam`

**Comment by vikasrohit** [comment]
@lakshmiathreya @codejamtc marking ready for QA because the underlying issue with legacy-challenge-resource-processor is supposed to be fixed now.

**Comment by drasticdpk** [comment]
verified on dev env.
![image](https://user-images.githubusercontent.com/25297859/94410693-5dc7d980-0197-11eb-9a12-fcec68ee9812.png)

**Comment by sandhiyakavi** [comment]
@vikasrohit Getting the error " **The user has not yet agreed to the following terms: [Standard Terms for Topcoder Competitions v3]"** and not able to save as Draft

![image](https://user-images.githubusercontent.com/55895538/99794271-412f9880-2b6d-11eb-913d-c0f6201ff8af.png)

**Comment by sandhiyakavi** [comment]
@vikasrohit This Standard terms errors is happening for some Assigned members. Is this error expected one?
Able to save the task as draft without error.

![image](https://user-images.githubusercontent.com/55895538/99796560-0f203580-2b71-11eb-9fdd-bc089422d66e.png)
[issue#828.zip](https://github.com/topcoder-platform/work-manager/files/5573267/issue.828.zip)

**Comment by vikasrohit** [comment]
Yes, @sandhiyakavi, there is update to the terms on production recently and all users have to accept the new terms. So, this error would appear for users who haven't accepted the new terms yet. We can close the task once, we are able to verify it for any one of the users who has accepted the v3 terms. To make it more validated, we can verify it for 2 users.

**Comment by sandhiyakavi** [comment]
@vikasrohit Could you please let me know how to accept v3 terms ? Because In  Community's challenge details page I am able to see only version 2.2
![image](https://user-images.githubusercontent.com/55895538/100070908-d12b5600-2e7d-11eb-8853-7854daae5cc4.png)

**Comment by vikasrohit** [comment]
@sandhiyakavi here it is https://www.topcoder.com/challenges/terms/detail/564a981e-6840-4a5c-894e-d5ad22e9cd6f

**Comment by sandhiyakavi** [comment]
@vikasrohit Verified by accepting the terms for two users SandhiyaA and TCConnCopilot. Not getting the error now.

![image](https://user-images.githubusercontent.com/55895538/100072972-3e3feb00-2e80-11eb-9c4c-a415e0abe21c.png)

[standard_term_check.zip](https://github.com/topcoder-platform/work-manager/files/5588671/standard_term_check.zip)
