### ISSUE TITLE
Support direct link for a challenge without having project id known

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#829]
As of now one has to be aware of project id along with challenge id to access the challenge in WM which slows down the debugging process or slows down process when people want to have quick look over challenge because they have to first find out the project of the challenge which is not straightforward for many of the cases.
So, as a solution, if we can automatically redirect the user to the full URL even if the project detail is not included in the URL. I don't see any security issue with it as long as the there is a validation on final URL. We can further add validation by determining if the project is accessible to the logged in user when identifying the project of the challenge.

Expected link to work for redirection is: https://challenges.topcoder-dev.com/challenges/7a80d15c-8d23-414a-8737-8069d5d821fb

**Comment by vikasrohit** [comment]
fyi @lakshmiathreya @acshields @mtwomey

**Comment by acshields** [comment]
@vikasrohit - I think this is a good point, but I want to bounce this against some other ideas I am having on the "all" view of Work Manager to see how we can bring this idea and some of mine together.

**Comment by vikasrohit** [comment]
Ok. But I think @acshields we need this quick link before we release to users because they might not be knowing the project ids for the specific challenge because now ids are UUIDs which are very very very difficult to remember. And specially this would help us and Support team in debugging things faster. I am trying to get it done today, if possible.

**Comment by vikasrohit** [comment]
@acshields implemented in dev.

**Comment by drasticdpk** [comment]
Here I am unable to open the challenge. cc @vikasrohit 
Reference : 
https://www.topcoder-dev.com/challenges/5be728f5-0f71-46bd-8579-38b4c3a89d97
![image](https://user-images.githubusercontent.com/25297859/94506293-beedbc80-022c-11eb-916d-866f0e86aa25.png)

**Comment by vikasrohit** [comment]
Why do you need to open the challenge for verifying this issue?

**Comment by drasticdpk** [comment]
Sorry for my Inconvenience. Can you please assist me how to verify this issue? Thank you @vikasrohit

**Comment by vikasrohit** [comment]
@drasticdpk you just need to prepare URL `https://challenges.topcoder-dev.com/challenges/{challengeId}` for any of your challenges, and that should properly redirect you to the full URL which includes the project id in the URL.

**Comment by drasticdpk** [comment]
Verified  on dev env
Challenge Link : https://challenges.topcoder-dev.com/challenges/f06c8670-5530-4ff2-88c7-30e672c1bf8f
Redirect link : https://challenges.topcoder-dev.com/projects/9074/challenges/f06c8670-5530-4ff2-88c7-30e672c1bf8f/view

**Comment by sandhiyakavi** [comment]
Verified on Prod.Working as expected.

[issue#829.zip](https://github.com/topcoder-platform/work-manager/files/5572690/issue.829.zip)
