### ISSUE TITLE
Save fails after changing assigned user for a task more than once

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#833]
Steps:

- Create task
- Assign member `maxceem-dev-2`
- Click `Save Draft`
- Close the success modal (if that is not blocked because any bug), using x button of the modal (do not use the View Challenge or Close button)
- Again change assign member to `maxceem-dev-3`
- Hit `Save Draft`
- Observe the console and network tabs, it would have errors in updating the challenge resources
<img width="1228" alt="Screen Shot 2020-09-25 at 4 09 53 PM" src="https://user-images.githubusercontent.com/2417632/94257851-8fe3fc00-ff49-11ea-90cb-91bf1e2707f7.png">

**Comment by drasticdpk** [comment]
Verified on Dev env
![image](https://user-images.githubusercontent.com/25297859/94399540-4680f000-0187-11eb-94cd-c3ced949a940.png)

**Comment by vikasrohit** [comment]
Just curious @drasticdpk, if you were able to reproduce the issue before the fix? I mean in prod or even in dev before I noticed the issue?

**Comment by drasticdpk** [comment]
No @vikasrohit , I have not noticed it before. 
Definitely I will log this type of issue if I found during the testing.

**Comment by sandhiyakavi** [comment]
Verified on Prod. Working as expected.

[issue#833.zip](https://github.com/topcoder-platform/work-manager/files/5573223/issue.833.zip)
