### ISSUE TITLE
v5 Challenge API showing unexpected behavior : Sometime Challenge Title is missing

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#837]
Reference : 

https://challenges.topcoder-dev.com/projects/9074/challenges

![image](https://user-images.githubusercontent.com/25297859/94402377-b1342a80-018b-11eb-9c5f-76d70770bc84.png)

![image](https://user-images.githubusercontent.com/25297859/94402450-cc9f3580-018b-11eb-857f-2cc511f16456.png)

**Comment by vikasrohit** [comment]
As per latest updates from the API team, it should be fixed now in dev @drasticdpk.

**Comment by drasticdpk** [comment]
Verified on dev
![image](https://user-images.githubusercontent.com/25297859/94568493-428ac600-028c-11eb-835b-53092da6d07b.png)

**Comment by vikasrohit** [comment]
Thanks @drasticdpk However, I think you highlighted wrong field in the api response, it should be the `name` field instead.

**Comment by drasticdpk** [comment]
Agreed.

**Comment by sandhiyakavi** [comment]
Verified on Prod. Working as expected.
