### ISSUE TITLE
Loading edit URL for a challenge directly does not load copilot information

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#839]
Steps to reproduce:

- Go to the challenge listing page
- Click on any challenge (which has copilot set) from the list to view its details
- Notice that in read only view, copilot details is visible
- Now Click on the Edit button
- Observe that Copilot is shown as selected from the available members
- Now refresh the page
- Observe that Copilot selection is gone now

Please note that it might not happen every time but these steps are giving high probability of reproducing the bug, though the bug should be there whenever we load the edit page directly. Seems like some timing issue, if it is able to load the challenge details before rendering the page, it shows the copilot selected otherwise not.

**Comment by vikasrohit** [comment]
@codejamtc @drasticdpk it should be fixed now, I have forced the resource details to be available before challenge details are loaded. It might slow down the page load a bit, but it would keep the information consistent.

**Comment by drasticdpk** [comment]
Verified on dev mode. 
![image](https://user-images.githubusercontent.com/25297859/94567807-93e68580-028b-11eb-9566-c71cd4561a33.png)

Note : I verified it is working in new tab too. 
https://challenges.topcoder-dev.com/projects/9074/challenges/3808d50b-c1b4-4fc7-ac7c-c4ddedb9ac50/edit

**Comment by sandhiyakavi** [comment]
Verified on Prod. Working as expected.

[issue#839.zip](https://github.com/topcoder-platform/work-manager/files/5573090/issue.839.zip)
