### ISSUE TITLE
Clicking Back button from Edit Challenge screen shows empty list of challenges

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#840]
Steps:

- Ensure, the Active tab has at least one challenge listed for the project you are using for testing
- Now open any challenge (from any status tab)
- Click on Edit button
- Click Back
- Observe that Challenge Listing page is opened with Active tab selected and no challenge is shown in the list

**Comment by vikasrohit** [comment]
fyi @drasticdpk @codejamtc

**Comment by drasticdpk** [comment]
Verified on Dev mode. 
![image](https://user-images.githubusercontent.com/25297859/94570021-16704480-028e-11eb-9cb5-2eddde00a87e.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod. New tab displayed after clicking back button from the Edit view of Challenge in New status.

![image](https://user-images.githubusercontent.com/55895538/99792778-eb59f100-2b6a-11eb-8d1a-18c2115ec58b.png)
