### ISSUE TITLE
Unable to add prizes for a challenge in New status

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#843]

**Comment by vikasrohit** [comment]
@jmgasper would you mind adding more details to the issue which you have?

**Comment by drasticdpk** [comment]
Verified on Dev mode.
![image](https://user-images.githubusercontent.com/25297859/94570815-f9884100-028e-11eb-8fb3-24ae950aab8a.png)
Note : For work type : task we will not have `Add new Prize` button.
![image](https://user-images.githubusercontent.com/25297859/94571217-74e9f280-028f-11eb-9d13-b734cdc212da.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod. Able to add Prizes for a challenge in New status.

![image](https://user-images.githubusercontent.com/55895538/99791673-4985d480-2b69-11eb-80eb-ebfaa23ec678.png)
