### ISSUE TITLE
Fix Prizes to be Consistent

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/work-manager#847]
The prize object should look like this:
```json
{
   "prizeSets":[
      {
         "type":"placement",
         "description":"Challenge Prizes",
         "prizes":[
            {
               "value":100,
               "type":"USD"
            },
            {
               "value":50,
               "type":"USD"
            }
         ]
      },
      {
         "prizes":[
            {
               "type":"USD",
               "value":10
            }
         ],
         "type":"copilot"
      }
   ]
}
```

I believe this has to change:
https://github.com/topcoder-platform/challenge-engine-ui/blob/develop/src/config/constants.js#L138

And this has to be updated:
https://github.com/topcoder-platform/challenge-engine-ui/blob/develop/src/components/ChallengeEditor/CopilotFee-Field/index.js#L12
Specifically this line:
`{ type, prizes: [{ type, value: 0 }] }`
type is ambiguous. It should be something like:
`{ type, prizes: [{ CHALLENGE_PRIZE_TYPE.MONEY, value: 0 }] }`
Not sure on the rest of the changes throughout the system.

**Comment by maxceem** [comment]
@vikasrohit done via PR https://github.com/topcoder-platform/challenge-engine-ui/pull/858

**Comment by vikasrohit** [comment]
@rootelement changes are deployed to dev env.
