### ISSUE TITLE
Error message displayed while activating the challenge but it won't reflect the actual situation of the error

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#849]
![image](https://user-images.githubusercontent.com/42398485/95039462-70d62e80-06ee-11eb-9f33-588943600675.png)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Copilot
2. Select a project from the list 'Connect Project 01 - codejam' **(No Billing account)**
3. Create a Design challenge 
4. Click Edit
5. Click Launch as Active > Confirm

### Actual behavior
-  Error message displayed while activating the challenge but it won't reflect the actual situation of the error

### Expected behavior
- Should display "Cannot Activate this project, it has no active billing accounts."

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `TCConnCopilot`

**Comment by vikasrohit** [comment]
@codejamtc how do you know that error is because of billing accounts? Did you see that in console logs?

**Comment by codejamtc** [comment]
@vikasrohit 
[Uploading 1.zip…]()

**Comment by vikasrohit** [comment]
fixed and deployed to dev.

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/95047567-eef10000-0703-11eb-988a-0bfe1eabb3e7.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod.Working as expected.

![image](https://user-images.githubusercontent.com/55895538/99792259-2f002b00-2b6a-11eb-9c70-e44539979ee8.png)
