### ISSUE TITLE
After activating the challenge created person changes 'tcwebservice'

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#851]
![image](https://user-images.githubusercontent.com/42398485/95044239-8fdbbd00-06fc-11eb-8bde-55f8fde2ee7a.png)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Copilot
2. Select a project from the list 'Connect Project 01 - codejam'
3. Create a Design challenge (Add NDA, Reviewer=Community; tag=Google)
4. Click Edit
5. Click Launch as Active > Confirm
6. Wait few mins for sync
7. Go to Active tab and check the member `Created by tcwebservice at 05/10/2020`

### Actual behavior
- After activating the challenge created person changes 'tcwebservice'

### Expected behavior
- Should display the correct member name

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `TCConnCopilot`

**Comment by ThomasKranitsas** [comment]
Fixed in https://github.com/topcoder-platform/legacy-challenge-migration-script/commit/c993874ed313c187b243b916d8531935f275aadc

@rootelement please redeploy

**Comment by rootelement** [comment]
That was merged in and deployed in dev. Does this fix the issue @codejamtc ?

**Comment by acshields** [comment]
@vikasrohit - seems like work is being done here via thomas/james. I am going to move this one from req clarification to in progress.

**Comment by vikasrohit** [comment]
@lakshmiathreya @codejamtc @sandhiyakavi  it is ready for qa.

**Comment by lakshmiathreya** [comment]
Verified in Prod.
<img width="1680" alt="Screenshot 2020-12-09 at 2 19 28 PM" src="https://user-images.githubusercontent.com/51733042/101606734-b6361580-3a29-11eb-8c4a-cb1d2cf0876d.png">
