### ISSUE TITLE
User can draft a challenge without a 'tag'

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#854]
![image](https://user-images.githubusercontent.com/42398485/95048754-07fab080-0706-11eb-946c-f2371b8e68c0.png)

[5.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5325765/5.zip)

### Steps to reproduce the problem

URL: https://challenges.topcoder-dev.com/projects/16604/challenges/168164bd-7976-4035-ae99-fba65d9c4775/view

1. Open https://challenges.topcoder-dev.com/ and login as Copilot
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Create a Dev challenge
4. Fill all the mandatory details but don't add a tag, click Save as draft

### Actual behavior
- User can draft a challenge without a 'tag'

### Expected behavior
- Should validate and display a message `Select at least one tag`

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `TCConnCopilot`

**Comment by vikasrohit** [comment]
@acshields @rootelement do we want the tags to be a mandatory field?

**Comment by acshields** [comment]
@vikasrohit - yes, I believe they should be.

**Comment by vikasrohit** [comment]
@maxceem please make it mandatory on the front end.

**Comment by maxceem** [comment]
@vikasrohit done via https://github.com/topcoder-platform/work-manager/pull/932

**Comment by lakshmiathreya** [comment]
Tag is now validated - verified in Prod.
<img width="1680" alt="Screenshot 2020-12-07 at 8 43 33 PM" src="https://user-images.githubusercontent.com/51733042/101368292-fa5fd380-38cc-11eb-91db-4f1ba1d3afec.png">

**Comment by drasticdpk** [comment]
verified.
