### ISSUE TITLE
[Specific Case] "The prop `onUpdatePhase` is marked as required in `a`, but its value is `undefined`.' displayed when user opens a challenge

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#857]
![image](https://user-images.githubusercontent.com/42398485/95050427-27470d00-0709-11eb-939f-0a6acbeaa560.png)

[8.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5325803/8.zip)

### Steps to reproduce the problem

URL: https://challenges.topcoder-dev.com/projects/16604/challenges/7f4daa1a-83d6-4833-bdaf-1fd3e24d845e/view

**This is not reproducible always**

1. Open https://challenges.topcoder-dev.com/ and login as Copilot
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Open the Dev challenge 'Dev3333' - https://challenges.topcoder-dev.com/projects/16604/challenges/7f4daa1a-83d6-4833-bdaf-1fd3e24d845e/view
4. Click Edit
5. Click Back
6. Check the console log

### Actual behavior
- "The prop `onUpdatePhase` is marked as required in `a`, but its value is `undefined`.' displayed when user opens a challenge

```
checkPropTypes.js:21 Warning: Failed prop type: The prop `onUpdatePhase` is marked as required in `a`, but its value is `undefined`.
    in a (at ChallengeView/index.js:137)
    in qi (created by t)
    in t (created by withRouter(qi))
    in withRouter(qi) (at ChallengeEditor/index.js:203)
    in t (at ChallengeEditor/index.js:199)
    in div (at ChallengeEditor/index.js:147)
    in a (created by Context.Consumer)
    in Connect(a) (created by t)
    in t (created by withRouter(Connect(a)))
    in withRouter(Connect(a)) (at routes.js:118)
    in div (at TwoColsLayout/index.js:33)
    in Unknown (at App/index.js:13)
    in div (at TwoColsLayout/index.js:15)
    in D (at App/index.js:9)
    in t (at routes.js:115)
    in t (at routes.js:100)
    in a (created by Context.Consumer)
    in Connect(a) (created by t)
    in t (created by withRouter(Connect(a)))
    in withRouter(Connect(a)) (at App.js:14)
    in t (created by t)
    in t (at App.js:13)
    in t (at App.js:12)
    in ac (at src/index.js:11)
```

### Expected behavior
- Should not display a console log

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `TCConnCopilot`

**Comment by coderhacker** [comment]
This is working fine on Production
https://user-images.githubusercontent.com/62358241/119333600-aa709f80-bca7-11eb-95a6-a3043eefd995.mp4
