### ISSUE TITLE
NDA Not Stored on Challenge

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/work-manager#859]
I created this challenge:
https://challenges.topcoder-dev.com/projects/16640/challenges/f7dcc162-e36f-4b0b-aae6-07dd3361bb3f/view

I checked the NDA box. But the only thing I see on the challenge object returned is standard challenge terms for the submitter roleId:
![Screen Shot 2020-10-05 at 11 36 45 AM](https://user-images.githubusercontent.com/5400156/95100420-11cce580-06ff-11eb-9cd8-7e8c4d13ef89.png)

I should see two entries in that array.

**Comment by rootelement** [comment]
I'm not sure how, but when I view the challenge in challenge manager, the NDA box is checked. Not sure where it's getting that information from. `b11da5cd` is the UUID of the `Standard Terms for TopCoder Competitions v2.2`, not the NDA UUID.

**Comment by vikasrohit** [comment]
Yes, I noticed that @rootelement as well, however, I did try to reproduce it but when I set NDA checkbox it is properly setting the terms id and on page refresh I can see the correct terms ID for NDA as well.

**Comment by maxceem** [comment]
I also cannot reproduce this issue though I've tried several times. The NDA stays checked and I can see 2 terms added to the list.

**Comment by vikasrohit** [comment]
That might mean sync/migration script is doing it as well.

**Comment by vikasrohit** [comment]
@rootelement I think it is migration or sync script as the [challenge](http://local.topcoder-dev.com:3000/projects/16573/challenges/6d897de8-c1f3-4abf-a9cd-64416b70c4a2/view) I created for testing this, got the NDA term removed automatically after some time I activated the challenge. I am 100% sure that I didn't do any other operation on that challenge after activation and I was able to see the correct terms immediately after the activation and an immediate page refresh after that.

**Comment by drasticdpk** [comment]
This is verified NDA has not implement correctly 
Reference :
![image](https://user-images.githubusercontent.com/25297859/95948686-c0b0a600-0e10-11eb-89db-873b77068cf2.png)

In Direct app, NDA is not reflected.
![image](https://user-images.githubusercontent.com/25297859/95948891-34eb4980-0e11-11eb-9ee0-e5071d2cf776.png)
cc @vikasrohit @codejamtc

**Comment by rootelement** [comment]
Thomas and I are going to test this in dev by shutting off sync and creating a bunch of challenges. Will report back shortly.

**Comment by codejamtc** [comment]
Here is my observation: @rootelement @vikasrohit 

[1.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5421014/1.zip)

1. [QA][Challenges][10222020] Prod Test 01 - Activated (NDA, Copilot and Copilot fee - Displayed); it moves to the Active tab and then after few mins it moves to Draft again. I activated it again and now I can see it on the Active tab. [Note: I added a Group]

- NDA is missing

 2. [QA][Challenges][10222020] Prod Test 02 - Activated (NDA, Copilot and Copilot fee - Displayed); it moves to the Active tab and then after few mins it moves to Draft again. [Note: I didn't add a Group]

- NDA is displayed

3. [QA][Challenges][10222020] Prod Test 03 - Activated (NDA, Copilot and Copilot fee - Displayed); it moves to the Active tab and then after few mins it moves to Draft again. [Note: I added a Group]

- NDA is missing

**Comment by rootelement** [comment]
Please test this again @maxceem . I believe this is fixed in dev and prod.

**Comment by maxceem** [comment]
@rootelement I've tested it on DEV and it works good for me.

**Comment by lakshmiathreya** [comment]
NDA not synced correctly in Prod.
<img width="1680" alt="Screenshot 2020-12-07 at 8 18 10 PM" src="https://user-images.githubusercontent.com/51733042/101365160-71936880-38c9-11eb-997b-da64ef8bc6bb.png">
<img width="1680" alt="Screenshot 2020-12-07 at 8 17 54 PM" src="https://user-images.githubusercontent.com/51733042/101365121-65a7a680-38c9-11eb-8b07-ee1d07174eb1.png">

**Comment by rootelement** [comment]
This should be fixed in prod now. The property _was_ changed on the v4 object, but there was an entry missing from `project_info` that direct looks for which is now being added.

**Comment by drasticdpk** [comment]
Verified.

![image](https://user-images.githubusercontent.com/25297859/101445156-1012de80-3949-11eb-86ff-f09b78fbf17f.png)
