### ISSUE TITLE
Error message not displayed when updating challenge

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#860]
Error message is not displayed if there is any error during challenge update. This issue happens when there is no modal is already rendered before performing the update action i.e. cases like `Launch as Active` are not affected with this and they are showing the error message in the action. However, when there is no modal shown before the actual update action, there is no UI yet to show the error.

**Comment by vikasrohit** [comment]
fyi @codejamtc @drasticdpk you might already have this issue open, please link it here if it already exists. However, please keep in mind in that it is different from error not shown for `Launch as Active` action because of the above mentioned reason.

**Comment by codejamtc** [comment]
@vikasrohit Please check the below scenario, Thanks

1. Open https://challenges.topcoder-dev.com/ and login as Copilot
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Create a Dev challenge (Set Copilot = Currently logged in user) (Info popup displayed)
4. Click Edit
5. Change the Copilot to a different user and Save as draft (Info popup displayed)
6. Wait a few seconds
7. Click Edit (You will see the Copilot selected from Step 5 is not visible)
8. Select the same Copilot and click Save as Draft

There is an error but it is not displayed on the frontend 
`message: "User vikasrohit already has resource with roleId: cfe12b3f-2a24-4639-9d8b-ec86726f76bd in challenge: 39a151fb-6add-4a58-837f-c8c7e6d8ed8d"`

[1.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5337765/1.zip)

**Comment by vikasrohit** [comment]
That is ignored intentionally I guess because the operation is successful as the error just suggests that selected copilot is already a copilot. However, we do need to show error when the application is not able to add the copilot as copilot resource when it is not already associated. Let me know if that is the case.

**Comment by codejamtc** [comment]
@vikasrohit Yes, you are correct

**Comment by sandhiyakavi** [comment]
Verified on Prod.Working as expected.
