### ISSUE TITLE
F2F Challenges let you set multiple prizes, but only the first one is actually used

### ISSUE THREAD

**Issue by mtwomey** [topcoder-platform/work-manager#865]
Should limit the user to only 1 prize on F2F challenges.

**Comment by vikasrohit** [comment]
We do restrict the number of prizes for Tasks, if we need to restrict it for F2F, we can do that as well. fyi @acshields

**Comment by acshields** [comment]
@vikasrohit - adding this to the December backlog.

**Comment by vikasrohit** [comment]
Ok @acshields but from requirement standpoint, we do want to let only 1 prize for the F2F, right?

**Comment by acshields** [comment]
Yes @vikasrohit - confirmed that there should be 1 prize for F2F.

**Comment by vikasrohit** [comment]
@acshields moving it to current release to clear number of small issues from the list.

**Comment by maxceem** [comment]
Done via https://github.com/topcoder-platform/work-manager/pull/920

**Comment by drasticdpk** [comment]
Verified. 
![image](https://user-images.githubusercontent.com/25297859/101446159-d0e58d00-394a-11eb-84f1-50bad7df2e0c.png)
