### ISSUE TITLE
Error initially after activating a challenge

### ISSUE THREAD

**Issue by mtwomey** [topcoder-platform/work-manager#870]
Video showing the issue

https://youtu.be/rC8I0tq2nT4

**Comment by drasticdpk** [comment]
Here, while clicking the **view challenge** link it is opening the WM challenge details page. 
@mtwomey is this your expectation or you want to open community app's challenge details page, please confirm.  
![image](https://user-images.githubusercontent.com/25297859/98256833-24a93300-1fa7-11eb-83ba-d6347960514e.png)

**Comment by vikasrohit** [comment]
@drasticdpk the original issue is about the permission error user was seeing on clicking the `View Challenge` button after activating the challenge from the listing page. That has been fixed. We have not touched where the `View challenge` button should go.

**Comment by lakshmiathreya** [comment]
View Challenge is working fine - verified.
