### ISSUE TITLE
After activating the challenge; after few seconds it will go to the draft and then again after few seconds it will go to active tab again

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#872]
### Steps to reproduce the problem

1. Open https://challenges.topcoder.com/ and login as Copilot
2. Select a project from the list 'Q2: Customer Experience Prod/Dev Delivery (Connect Projects)'
3. Create a Dev challenge
4. Fill all the mandatory details and Click Save as draft
5. Click Edit > Activate it
6. Check the active tab
7. Wait few mins and check the active tab (Challenge is not there)
8. Go to Draft tab (Challenge is there)
9. Wait few mins
10. Now the challenge is in the active tab

### Actual behavior
- After activating the challenge; after few seconds it will go to the draft and then again after few seconds it will go to active tab again

### Expected behavior
- Should not switch between tabs after activating

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `TCConnCopilot`

**Comment by rootelement** [comment]
This will need to be retested after we release the Terms/Copilot Payment update to prod. It should be fixed today.

**Comment by codejamtc** [comment]
@rootelement @vikasrohit **Update**: I checked again today, but still after activating the challenge goes to draft. After that, it won't come again to the `Active` tab.

**Comment by acshields** [comment]
@vikasrohit @rootelement - I am adding this to our December project for us to check back in on after the next release.
