### ISSUE TITLE
Challenge Delete Functionality in WM App

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#873]
Scenario : 
While creating the challenge, mistakenly if user has selected wrong **Work Type**  or **Work Format** either it will stay in new/draft tab  or user has to activate it and delete it form OR.

Possible solution : 
1. We can add edit functionality for **Work Type**  or **Work Format** 
2. we can add deleted functionality for **New/Drat** status.

**Comment by vikasrohit** [comment]
@acshields fyi

**Comment by acshields** [comment]
@vikasrohit - Here's my thoughts:

1. I think users should have a way to change the type/track after initial set-up while the item is in New or Draft status. Is this possible today?
2. I think the delete capability can also exist for an item that is still in New or Draft status. Do we have any limitations around this for legacy stuff?

**Comment by vikasrohit** [comment]
@rootelement can throw better light on this.

**Comment by ThomasKranitsas** [comment]
@acshields @vikasrohit 
1. We have blocked the ability to change the type/track as that's not possible on legacy. We could possibly allow changing those value if the challenge is still in `New` state, meaning it hasn't yet been created on legacy. Let me know if that's required and I'll work on that.
2. We recently added the ability to delete `New` challenges. We cannot delete challenges with any other status because of legacy limitation

**Comment by acshields** [comment]
@vikasrohit @ThomasKranitsas -

1. I think that providing the ability to change type and track in New status will be important. Please add this to the plate for backend work. However, just a note that in my opinion I don't think this should priority over more pressing issues (that prevent a user on getting through a basic workflow) or features. So, if there is anything more urgent on the plate, this can come at a later time.
2. Noted - the limitation is understood and is alright.

**Comment by vikasrohit** [comment]
@acshields can we close this one and create new one(s) as per final solution that we want to implement i.e. having the delete capability for New challenges or both if we want both solution?

**Comment by acshields** [comment]
@vikasrohit - we can close it, and then open an new one for just the deletion of items in "New" status.
