### ISSUE TITLE
User with any Role can access the Application.

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#875]
**Actual** : user with any Role can access the Application. (eg Topcoder User)
**Expected**:
User with Only selected Role (Copilot, Copilot Manager)  should access the application.

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/95978975-91ae2a80-0e38-11eb-8f36-318c1f40804b.png)

```
The above error occurred in the <a> component:
    in a (created by Context.Consumer)
    in Connect(a) (created by t)
    in t (created by withRouter(Connect(a)))
    in withRouter(Connect(a)) (at App.js:14)
    in t (created by t)
    in t (at App.js:13)
    in t (at App.js:12)
    in nc (at src/index.js:11)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```


[Log.txt](https://github.com/topcoder-platform/challenge-engine-ui/files/5377550/Log.txt)

**Comment by acshields** [comment]
Correction to the expected behavior above. All Topcoder users (Copilot, Topcoder Manager, Admin, Program Manager, Project Manager, etc.) should be able to access Work Manager, except clients for now. The only condition is that only users who are on a project can see the challenges/tasks and create challenges/tasks for that project.

In the future, Clients will be able to access this app as well.

**Comment by vikasrohit** [comment]
> The only condition is that only users who are on a project can see the challenges/tasks and create challenges/tasks for that project.

That is already implemented. I think clients would be able to see the application but they can not edit the challenge. Do you want it to explicitly throw error for users who have only `Topcoder User` role?

**Comment by acshields** [comment]
@vikasrohit - no, I don't think that's necessary for now. If we are all good with the other users, we can close this issue.
