### ISSUE TITLE
Save button for saving challenge in New status

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#876]

**Comment by codejamtc** [comment]
`Save` button is displayed in the Draft tab as well; intended? @vikasrohit 

![image](https://user-images.githubusercontent.com/42398485/96842093-3f898c80-146a-11eb-8141-dfcb6f9e6bfb.png)

**Comment by vikasrohit** [comment]
Yes, it should also be visible for Active challenge as well. However, I think we can avoid showing the `Save Draft` button once the challenge is in Draft status because `Save` button would also do the same work.

**Comment by sandhiyakavi** [comment]
Verified on Prod. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/99786825-4f2bec00-2b62-11eb-88ea-28518561e407.png)
