### ISSUE TITLE
Default Timeline Templates

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/work-manager#881]
This line:
https://github.com/topcoder-platform/challenge-engine-ui/blob/develop/src/services/challenges.js#L77
should be changed to this:
`const response = await axiosInstance.get(`${CHALLENGE_TIMELINES_URL}?isDefault=true&page=1&perPage=100`)`

There's now a default flag in dev. It will be in prod before the start of your day.

**Comment by vikasrohit** [comment]
Done in dev.
