### ISSUE TITLE
Unable to close task

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#882]
Steps : 
1. https://challenges.topcoder-dev.com/projects/16640/challenges/4ae6018d-748e-4c5d-a230-af36a2f87f51/edit
2. Try to close the task 
User:  topcoderconnect+copilot@gmail.com/appirio123

Reference:
![image](https://user-images.githubusercontent.com/25297859/96684835-f539da00-139b-11eb-8bc6-1efc1cc1b2ab.png)

**Comment by lakshmiathreya** [comment]
Task closure working fine in Prod.
