### ISSUE TITLE
"Only M2M, admin or user with full access role can perform this action" displayed when user tries to save as draft

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#884]
[6.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5421902/6.zip)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/
2. Open a Project and create a challenge
3. Click Save as draft

### Actual behavior
- "Only M2M, admin or user with full access role can perform this action" displayed when user tries to save as draft

### Expected behavior
- Should be able to save as draft a challenge

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121

**Comment by vikasrohit** [comment]
Should be fixed now @codejamtc. Just as background, it was happening because the challenge creator was not being added as resource to the challenge. @rootelement has patched the API to create a Manager resource for the challenge creator to resolve the issue.

**Comment by rootelement** [comment]
We're working through this issue now.
https://github.com/topcoder-platform/resources-api/issues/42#issuecomment-717963663

Fixing this should clean up some ambiguity. A manager of a challenge should be able to manage a challenge. Will report back as soon as it's fixed.

**Comment by sandhiyakavi** [comment]
Verified on Prod.Working as expected.
