### ISSUE TITLE
Remove copilot and copilot fee validation for a task close

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#896]
As of now, it requires copilot and copilot fee set for the task to allow close task operation. In practical, for tasks we might want to skip copilot selection e.g. cases where we direct make payments without including copilot or if the payment is for the copilot itself.

**Comment by vikasrohit** [comment]
@drasticdpk @codejamtc @lakshmiathreya as QA guideline, earlier it was validating the copilot and copilot fee as well to let user close the task. However, I found that over validation after discussing with the team, so, I have remove the validation now. So, now you can close a task without assigning a copilot or adding copilot fee.

**Comment by lakshmiathreya** [comment]
Verified that Task closure is happening with no copilot selected and Copilot fee set to zero.
