### ISSUE TITLE
V5 GET challenges API - Topgear team 

### ISSUE THREAD

**Issue by nkumar-topcoder** [topcoder-platform/work-manager#898]
Topgear team reported V5 get challenges has issues 
V5 GET challenges API
12:01
curl -X GET \
  'https://api.topcoder.com/v5/challenges?directProjectId=projectid&page=1&perPage=100' \
  -H 'Authorization: Bearer ' \
  -H 'cache-control: no-cache'

**Response is**
{
    "message": "Not found Group of id 053eb23f-......................"
}

**Comment by rootelement** [comment]
@ThomasKranitsas this is an api issue. Not sure what the error means. It doesn't look like they're querying on group

**Comment by rootelement** [comment]
This was released last night. I sent a note to Surendra to try again.

**Comment by vikasrohit** [comment]
Closing this one as it  belongs to the API https://github.com/topcoder-platform/challenge-api/issues/364. fyi @nkumar-topcoder
