### ISSUE TITLE
Not all groups are available in UI

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/work-manager#899]
**Describe the bug**
When setting up a challenge in work manager, I'm not able to see all my groups.  After some digging into the API calls, it appears to be because the API call to get my groups has a default page size that is LESS than my # of groups.  I tried increasing the pagesize on the API call to 2000 and then i saw my groups.

**To Reproduce / Actual Behavior**
1. Go to work manager
2. Start to create a challenge
3. Try to set a group
4. If the user has a lot of groups (probably > 1000) you won't see the recently created groups.

For TonyJ in prod, I can't see any groups that start with TCO20.

**Comment by ajefts** [comment]
fyi @acshields @vikasrohit

**Comment by vikasrohit** [comment]
@ajefts we are making call to https://api.topcoder.com/v5/groups?membershipType=user&memberId=<loggedInUserId> to fetch the list of groups of the user. So, I guess, it requires the logged in user to be part of the group to see that in the list.

**Comment by cwdcwd** [comment]
you need to check the x-headers on the call to the API and see how many pages of data are available and then make subsequent calls to fetch more pages

**Comment by vikasrohit** [comment]
@acshields let me know when you want to handle this one?

**Comment by maxceem** [comment]
`perPage` param in Groups API doesn't have the maximum value https://github.com/topcoder-platform/groups-api/blob/592e6d00ddc6abe8adb356fc11b4cc4134cc2c40/app-bootstrap.js#L10, so I guess we can set it as `1000000` to make sure we get all the groups.

**Comment by vikasrohit** [comment]
We can. However, @maxceem does the group api supports searching groups? I mean if we show all groups directly, it might be a long list of groups. And further,  can we set pageSize to be bigger so that we don't have to make 100 calls to get all groups?

**Comment by maxceem** [comment]
Yes, @vikasrohit we can filter groups by the `memberId` https://github.com/topcoder-platform/groups-api/blob/develop/src/services/GroupService.js#L156.

Also, we can set `perPage` to `1000000` or more to retrieve all the groups as there is no limit in the API https://github.com/topcoder-platform/groups-api/blob/592e6d00ddc6abe8adb356fc11b4cc4134cc2c40/app-bootstrap.js#L10.

**Comment by vikasrohit** [comment]
> Yes, @vikasrohit we can filter groups by the memberId https://github.com/topcoder-platform/groups-api/blob/develop/src/services/GroupService.js#L156.

I meant searching by name of the group e.g. as user starts typing `top` it should bring all groups which contains or startsWith `top` keyword.

**Comment by maxceem** [comment]
Got it. At the moment Groups API seems to not support searching by the substring. Btw, in the new design, we also use a regular dropdown at the moment.

![image](https://user-images.githubusercontent.com/146016/99670737-a7d38a00-2a79-11eb-9d14-38b7e5ec42de.png)

**Comment by vikasrohit** [comment]
Yep, I have asked product manager to revisit it as having long list of groups for admins, would not be a good UX.

**Comment by acshields** [comment]
@vikasrohit - followed up on the other issue (https://github.com/topcoder-platform/work-manager/issues/723) with change to how the group selection could work.

**Comment by rootelement** [comment]
Yeah, it looks like there are two problems:
1. The swagger is out of date, because it doesn't show you can filter on name at all
2. The filter on name in the service is exact match only: https://github.com/topcoder-platform/groups-api/blob/develop/src/services/GroupService.js#L47

I will cross-link this to the groups api and ask mithun to queue up fixes

**Comment by acshields** [comment]
@vikasrohit - do you still have open questions on this, or can this issue be moved to Backlog or Ready for Dev in November or December?

**Comment by vikasrohit** [comment]
Nope, only thing is that groups api don't support the searching by partial text, so we have to implement filtering on local.

**Comment by vikasrohit** [comment]
@maxceem we need to wrap this in November before the designs changes. Do you see any issue with that?

**Comment by maxceem** [comment]
Done via https://github.com/topcoder-platform/work-manager/pull/911

- I've increased the limit of loading groups to `1000000`
- By default, all the groups are shown. I've tried to show no groups by default and only show groups when we start filtering, but that doesn't feel nice to me, as it's more comfortable to select groups from the list even without filtering. Because not always it's easy to remember how the groups are named or spelled. I guess the majority of users wouldn't have too many groups. But this behavior may be changed if you like.
- The filtering already works:

    ![Nov-24-2020 13-50-30](https://user-images.githubusercontent.com/146016/100090789-674e8480-2e5c-11eb-9c56-bddddd7ab9b8.gif)

**Comment by acshields** [comment]
@maxceem - I like the behavior you implemented for the Intended Work Groups answer. Looks good to me.

**Comment by vikasrohit** [comment]
@lakshmiathreya fyi, it is ready for qa

**Comment by lakshmiathreya** [comment]
Groups are visible. @drasticdpk pls review and update test report.

**Comment by drasticdpk** [comment]
With reference to above communication, I am closing this issue. 
However, My Role with copilot , In both WM and Direct same group are reflecting. 
![image](https://user-images.githubusercontent.com/25297859/101441698-cc68a680-3941-11eb-8ff5-700fcc892dcd.png)
