### ISSUE TITLE
Add link to direct

### ISSUE THREAD

**Issue by dmessing** [topcoder-platform/work-manager#900]
Can we add a link to direct from here: https://challenges.topcoder.com/projects/26114/challenges

It will make it easy to find and add resources like billing accounts or copilots

**Comment by dmessing** [comment]
![Screen Shot 2020-11-17 at 11 49 35 AM](https://user-images.githubusercontent.com/664840/99420317-14f4ed00-28cb-11eb-841c-d2ceac461d8b.png)

**Comment by dmessing** [comment]
@acshields FYI something to think about

**Comment by maxceem** [comment]
Done by https://github.com/topcoder-platform/work-manager/pull/909

![image](https://user-images.githubusercontent.com/146016/100071916-42e6ae00-2e44-11eb-8229-019b071697d3.png)
