### ISSUE TITLE
No timezone indication when setting / viewing challenge start time

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#905]
There's no timezone indication when setting / viewing the challenge start time.  It defaults to my local time, but I had to go into OR to confirm the *actual* start date because the timezone was indeterminate.

![Screen Shot 2020-11-21 at 16 25 27](https://user-images.githubusercontent.com/21790/99868417-704e1480-2c16-11eb-987d-904adf06729f.png)

**Comment by acshields** [comment]
This will be fixed with the new UI design.
