### ISSUE TITLE
Legacy ID not displayed in Work Manager

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#906]
We still need the Legacy ID for setup, and other things, like web hook filter setup.  I think we should display both the UUID *and* the legacy ID on the challenge detail page somewhere.

![Screen Shot 2020-11-23 at 11 38 00 am](https://user-images.githubusercontent.com/21790/99921748-8b3c9800-2d80-11eb-9356-86439d372e30.png)

**Comment by acshields** [comment]
- closing this, as it will be fixed with the new UI.
