### ISSUE TITLE
Receive Timeline Change Notifications not on by default

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/work-manager#908]
I just ran a challenge and didn't get notified via email of the end of the challenge because the `Receive Timeline Change Notifications` option wasn't checked by default when launching a challenge via WM.

![Screen_Shot_2020-11-24_at_7_39_23_pm](https://user-images.githubusercontent.com/21790/100069501-f378a000-2e8c-11eb-98d7-22a21da6e97c.png)

**Comment by rootelement** [comment]
@ThomasKranitsas This property should be stored on the ProjectInfo table:
`id: 11 - Timeline Notification`
Can you see if this can get enabled by default using informix update to the challenge?

**Comment by drasticdpk** [comment]
Yes we are able to replicate the issue on prod mode.

**Reference** 

![image](https://user-images.githubusercontent.com/25297859/101479852-ef637c80-397a-11eb-8d2f-ea35a0338845.png)

**Comment by vikasrohit** [comment]
@rootelement can we test it now in dev?

**Comment by drasticdpk** [comment]
Still we are having same issue on Dev .

**Reference** 
![image](https://user-images.githubusercontent.com/25297859/101489423-0741fd00-3989-11eb-895b-4e2adcd12b59.png)

https://software.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30057645

**Comment by rootelement** [comment]
This is confirmed fixed in dev. Will be going live tonight

**Comment by vikasrohit** [comment]
@drasticdpk can we verify it on production now?
