### ISSUE TITLE
Validation for the Prize field is visible eventhough user has not altered it.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/work-manager#910]
Description:
Refer https://github.com/topcoder-platform/work-manager/issues/779#issuecomment-688655529

**Comment by vikasrohit** [comment]
@sandhiyakavi Thanks for logging this. However, this is right now happening for all validation fields. As soon as user updates any field in the form, all other validations are triggered. We are not sure if we want to keep this or consider it as bug. However, with new designs coming soon, we can take care of this behaviour with designs changes.

fyi @acshields @maxceem

**Comment by acshields** [comment]
@vikasrohit - noted that this should be resolved with the new designs. Should we close this issue, or do you want to keep it for reference?

**Comment by vikasrohit** [comment]
Nopes, I would like to shorten my list of issues.

**Comment by acshields** [comment]
sounds good @vikasrohit
