### ISSUE TITLE
Grey out Direct and Online Review buttons or hide them

### ISSUE THREAD

**Issue by mtwomey** [topcoder-platform/work-manager#912]
These should be greyed out or hidden when not applicable:

![image](https://user-images.githubusercontent.com/7715262/100128859-6d396b00-2e46-11eb-8135-9a77bcc2b052.png)

**Comment by acshields** [comment]
Scenarios where buttons are not applicable:
- When the user is setting up a new challenge/task.
- When the new challenge/task has not been synced to legacy yet (is in New vs. Draft).

**Comment by maxceem** [comment]
Done via https://github.com/topcoder-platform/work-manager/pull/916

**Comment by vikasrohit** [comment]
@maxceem I think it is better to show the buttons but with disabled state. And in tooltip of those buttons, we can show a message that legacy is not yet created.

**Comment by maxceem** [comment]
@vikasrohit would you like to have custom nice-looking tooltips or use standard browser tooltips here?

**Comment by vikasrohit** [comment]
nopes, I am good with standard browser tooltip for now as we don't yet have those nice tooltip components which we have in Projects app.

**Comment by maxceem** [comment]
Too late, already implemented custom ones 😬. The standard ones were showing too slowly and hardly noticeable.

![image](https://user-images.githubusercontent.com/146016/100451775-a41ab580-30c0-11eb-86f1-be685ef0e7fe.png)

Updated PR https://github.com/topcoder-platform/work-manager/pull/916
