### ISSUE TITLE
Save the unsaved form changes on close task operation

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/work-manager#913]
Description: 

Refer https://github.com/topcoder-platform/work-manager/issues/800#issuecomment-732016812

**Comment by vikasrohit** [comment]
@maxceem we have to keep the buttons like `Close Task` and `Launch as Active` disabled if the form is dirty and let the user first save the form using `Save` or `Save Draft` button.

**Comment by maxceem** [comment]
From Vikas:
> this one looks important to me as people are tending to fall into this use case pretty often.
> They are assigning the task to a member and then marking it closed
> the other easy option for tackling this could be to save the form changes along with close task operation as well
> what do you think?

I guess saving before closing makes sense:
- it feels like natural behavior
- I guess technically it would be easier to implement

**Comment by vikasrohit** [comment]
Go ahead with this. fyi @acshields

**Comment by vikasrohit** [comment]
@sandhiyakavi fyi, I have updated the title of the issue to reflect the new solution instead of disabling the button because disabling the button is more tricky and error prone and we found the other way to be more natural way as well as suggested by @maxceem

**Comment by maxceem** [comment]
@vikasrohit do you know any project on DEV with a billing account attached? We need it to test `Close Task` workflow.

**Comment by maxceem** [comment]
@vikasrohit at the moment assigning member doesn't work for me at all even following "safe" steps:
1. Create a new task in DEV
2. Fill the required fields and **save as draft**
3. Wait until Legacy Project is created
4. Choose any member to assign (for example `maxceem`) and  click **save as draft** again
5. Reload the page and see that there is no assigned member

This looks like a processor. I can see that we send a request to create a new resource (assigned user). But it doesn't trigger filling the `task.memberId` field in the challenge object.

As I remember we don't set `task.memberId` field manually. We just create a resource and `task.memberId` is filled automatically by the API.

**Comment by vikasrohit** [comment]
@maxceem I think the reason for not having member assigned to a task in dev is that there are multiple entries for `Submitter` resource role being returned by api and that is causing one random roleId from those multiple entries to be sent as roleId when creating the resource which does not match with the UUID of the `Submitter` role which we have set for our application. Hence, it does not see it as task assigned.

**Comment by maxceem** [comment]
@vikasrohit this is fixed via https://github.com/topcoder-platform/work-manager/pull/936 together with the fix for the submitter role.

**Comment by drasticdpk** [comment]
@vikasrohit , 
I verified user can create and close the task. Pease re-open for any cases.
**Reference :**

![image](https://user-images.githubusercontent.com/25297859/101447012-78af8a80-394c-11eb-9ef6-ba4fb54fca7d.png) 

https://challenges.topcoder.com/projects/24943/challenges/d0bcefed-e298-4315-9e88-9c8b8b96c65e/view
