### ISSUE TITLE
Assignee on Task doesn't persist

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/work-manager#914]
**Describe the bug**
For some users (seems like a lot) there is an issue that happens when you assign the user to a task.  NOTE:  This also happens in Direct and I believe the root cause has something to do with some profile data (f2f rating) that legacy tries to lookup when assigning the user.

**To Reproduce / Actual Behavior**
1. Start creating a new task
2. Assign 'winterflame' (I know his user breaks)
3. Save the task as a draft (or any action that will sync to legacy)
4. Note that there is no error on the page
5. Refresh so you pull the latest data for the task.  Note that the assignee is gone (might need to wait for sync to see this happen??)
6. Go to the challenge in Direct/OR and notice the assignee has not been set.
7.  Now, from Direct edit the challenge and try to set the assignee.  When you save, you will see the error.  Check the Direct log at the same time for the specific error.

**Expected behavior**
Assignee should be saved on task or a useful error/validation message should be presented.

**Comment by ajefts** [comment]
fyi @acshields @vikasrohit

**Comment by acshields** [comment]
@vikasrohit - what req's do you need clarified?

**Comment by vikasrohit** [comment]
@acshields it is backend issue, and I have tagged the issue with `API/Backend Question` which means we need @rootelement's expert advice or help.

**Comment by maxceem** [comment]
@vikasrohit done via https://github.com/topcoder-platform/work-manager/pull/936

As was discussed on Slack. Instead of getting the submitter role by name, we use role UUID defined in config. Because at the moment DEV data has multiple role with `Submitter` name, so we cannot rely on that at the moment.

IMO. If the `ResourceRole.name` suppose to be the source truth, maybe we can make `name` field `unique` in the `ResourceRole` model?

**Comment by vikasrohit** [comment]
@maxceem I think this issue is happening for only particular user. I thought it was happening because of the same reason we saw in dev but this issue is already happening on prod where the roles data is correct. But none the less we got it fixed in dev.

**Comment by lakshmiathreya** [comment]
@drasticdpk Assignee is persisting in my test. Pls re-verify in Prod and update the Test report.
<img width="1680" alt="Screenshot 2020-12-07 at 7 36 05 PM" src="https://user-images.githubusercontent.com/51733042/101360354-8c62de80-38c3-11eb-9845-173bc9882a04.png">

**Comment by vikasrohit** [comment]
@lakshmiathreya the main issue here is assign task is not working for some of the users and one of the example is shared in the original description by Tony. We haven't fixed that yet.

**Comment by drasticdpk** [comment]
For now it is working as expected. 
**Reference :**

![image](https://user-images.githubusercontent.com/25297859/101443485-9d543400-3945-11eb-8267-355eaf0f05f8.png)

https://challenges.topcoder.com/projects/24943/challenges/d0bcefed-e298-4315-9e88-9c8b8b96c65e/view


However few cases not working for me. I will monitor this challenge and open/create new tickets if needed.

**Comment by vikasrohit** [comment]
@ajefts fyi, it seems we are able to assign task to `winterflame`
