### ISSUE TITLE
Default Timeline Not Selected for Design Challenge

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/work-manager#923]
I see Work Manager making this call to get the timeline templates:
I’ve confirmed that this call:
http://api.topcoder.com/v5/challenge-timelines?isDefault=true&page=1&perPage=100

And I see the default timeline templates coming back. If I make this API call (track = design, type = challenge):
http://api.topcoder.com/v5/challenge-timelines?trackId=5fa04185-041f-49a6-bfd1-fe82533cd6c8&typeId=927abff4-7af9-4145-8ba1-577c16e64e2e&isDefault=true

I get this this object:
[
{
"timelineTemplateId": "d4201ca4-8437-4d63-9957-3f7708184b07",
"isDefault": true,
"typeId": "927abff4-7af9-4145-8ba1-577c16e64e2e",
"id": "edd528d7-b2d6-48e4-80ab-cfccc3cfb6cb",
"trackId": "5fa04185-041f-49a6-bfd1-fe82533cd6c8"
}
]

That timelineTemplateId is the design with checkpoints:
![Screen Shot 2020-12-02 at 12 36 30 PM](https://user-images.githubusercontent.com/5400156/100911169-e1a28880-349c-11eb-91f8-86fdfdc235e1.png)

But when I create a design challenge out of work manager, I see this as the POST:
```
{
created: "2020-12-02T17:50:31.375Z"
createdBy: "jcori"
currentPhaseNames: []
description: ""
descriptionFormat: "markdown"
discussions: [{name: "Test Design Again Discussion", type: "challenge", provider: "vanilla",…}]
endDate: "2020-12-13T17:50:30.000Z"
groups: []
id: "d4524778-bee6-4098-8f18-9d3d0745edf1"
legacy: {reviewType: "community", confidentialityType: "public"}
name: "Test Design Again"
numOfRegistrants: 0
numOfSubmissions: 0
phases: [{duration: 259200, phaseId: "a93544bc-c165-4af4-b55e-18f3593b457a",…},…]
projectId: 16640
registrationEndDate: "2020-12-06T17:50:30.000Z"
registrationStartDate: "2020-12-03T17:50:30.000Z"
startDate: "2020-12-03T17:50:30.000Z"
status: "New"
submissionEndDate: "2020-12-09T17:50:30.000Z"
submissionStartDate: "2020-12-06T17:50:30.000Z"
terms: [{id: "64d6e249-d7a5-4591-8ff5-e872f8a051f9", roleId: "732339e7-8e30-49d7-9198-cccf9451e221"}]
timelineTemplateId: "7ebf1c69-f62f-4d3a-bdfb-fe9ddb56861c"
track: "Design"
trackId: "5fa04185-041f-49a6-bfd1-fe82533cd6c8"
type: "Challenge"
typeId: "927abff4-7af9-4145-8ba1-577c16e64e2e"
updated: "2020-12-02T17:50:31.375Z"
updatedBy: "jcori"
}
```
Where `7ebf1c69-f62f-4d3a-bdfb-fe9ddb56861c` is the:
```json
{
    "id": "7ebf1c69-f62f-4d3a-bdfb-fe9ddb56861c",
    "name": "Default Challenge",
    "description": "Standard Default Challenge Timeline",
   "isActive": true,
}
```

**Comment by vikasrohit** [comment]
@rootelement it seems we have multiple entries for the same `typeId` but for different `trackId`. Until now we were only filtering based on `typeId` when mapping between `ChallengeTimelineTemplate` and `TimelineTemplate` table. I am updating the logic to now filter using `trackId` and `typeId` both now to determine which timeline template we want to use. Do you see any problem with that logic?

**Comment by vikasrohit** [comment]
@lakshmiathreya @codejamtc can we get it verified in dev? As heads up, we might need to do regression (only for challenge creation part) for all track and type combination to make sure it didn't break any of the existing timeline mapping.

fyi @acshields @rootelement @mtwomey

**Comment by vikasrohit** [comment]
@rootelement we are getting checkpoints in the timeline when the review type is `Community` but there are not checkpoints when the review types is Internal. Do we need different timeline template id mapped for such cases?

**Comment by drasticdpk** [comment]
@vikasrohit  can  you please guide me, how can I test it from frontend or any other ways ?
Thanks.

**Comment by vikasrohit** [comment]
@drasticdpk create two design challenges, one with community review and another with internal review type. And once they are in legacy, observe that one with community review has checkpoints in the OR while the internal one don't.
