### ISSUE TITLE
Unable to create a task

### ISSUE THREAD

**Issue by ketzjs09** [topcoder-platform/work-manager#924]
I tried creating a task for https://challenges.topcoder.com/projects/26286/challenges

but I'm unable to do so, it returns this error, and I can't find the challenge saved in the draft as well
https://drive.google.com/file/d/1f8TtsxSnp-AoLcQIaXbQgossiZ6h858u/view?usp=sharing

**Comment by vikasrohit** [comment]
@ketzjs09 can you please retest it, seems like it was intermittent issue because of API unavailability.

**Comment by vikasrohit** [comment]
@ketzjs09 we are closing the issue for now as it seems to be an intermittent issue and we are able to create tasks as of now. Please feel free to reopen it, in case you are still facing the issue.
