### ISSUE TITLE
Legacy challenge is not created if we click "Save" the first time

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/work-manager#925]
### Steps to reproduce

1. Click **Launch New**
2. Choose **Work Type**: `Development`, **Work Format**: `Challenge`, **Work Name**: `any`
3. Click **Continue Set-Up**
4. Fill all the required fields and click **Save** (NOT **Save Draft**)
5. Now wait 30 seconds and reload the page. Links to legacy projects would be still disabled as Legacy Project would not be created. And it doesn't matter how long we wait and how many times we reload, there would be no `legacyId` in the challenge.

    ![image](https://user-images.githubusercontent.com/146016/100926420-1689fc00-34ec-11eb-9194-1aaff04952a8.png)

    No `legacyId`

    ![image](https://user-images.githubusercontent.com/146016/100926453-27d30880-34ec-11eb-8b99-dedbb009d350.png)

**Note**. If we click **Save Draft** at any point of time then a legacy challenge would be created after several seconds.

FYI @vikasrohit

**Comment by vikasrohit** [comment]
@maxceem that is legit confusion. Actually, `Save` button saves the challenge in whatever status it is already. So it won't move a challenge to legacy if the challenge is in `New` state.
