### ISSUE TITLE
Cannot create challenge when only one project

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/work-manager#926]
I cannot seem to create a challenge in a fresh project. 

# STR: 
- login as `jcori30` on dev 
- goto https://challenges.topcoder-dev.com/ 
- no project is present despite `jcori30` having 1 active project in projects API (see [here](https://connect.topcoder-dev.com/projects/16717/) )
- search for `test`
- project listing shows
- click project
- redirect to empty project list as at the start 

![image](https://user-images.githubusercontent.com/1504607/100951503-ab84f900-34dc-11eb-888a-80155ef6787e.png)
![image](https://user-images.githubusercontent.com/1504607/100951527-b5a6f780-34dc-11eb-8e45-dc238a5415ad.png)

**Comment by vikasrohit** [comment]
@cwdcwd it is coming for me when I logged in as `jcori30`. It might be the api failed because of network issue and didn't show you the projects. Did you see any error in console logs when you didn't see the projects?

**Comment by vikasrohit** [comment]
Closing as I am not able to reproduce it even with impersonation. It seems to be intermittent API issue.
