### ISSUE TITLE
Remove "Save" button from set-up flow

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#929]
Remove the "Save" button from the set-up flow, so that the only option displayed is "Save Draft"

Notes
- If the user does not click "Save Draft" and navigates away, the challenge will still be saved as "New" and can display in the "New" tab in the "all work" view.
- The "Save Draft" button will work as is (no changes).

**Comment by lakshmiathreya** [comment]
Verified Save button removed from setup flow.
