### ISSUE TITLE
Let them user, how many minutes (times) need to wait after activating challenge. 

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#942]
Reference 
![image](https://user-images.githubusercontent.com/25297859/101476091-57af5f80-3975-11eb-95ac-c35112344115.png)

**Comment by vikasrohit** [comment]
@acshields do we have finalized how and where to show this information?

**Comment by acshields** [comment]
@vikasrohit - I seem to remember seeing an issue or a discussion somewhere that James had found a way to cut down on the legacy-loading time. I can't remember what the solution was, or if it is complete. Let's chat on the call today to see if what I remember was real, and whether this is still needed.

If it is needed:
- We can display the wait time under the "Activate" buttons with the text: "Legacy Sync Time: X"
- We will need to determine what the average wait time is.
