### ISSUE TITLE
Disable buttons and show tooltip when legacy challenge is not yet created on the challenge listing page

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/work-manager#943]
Follow up from https://github.com/topcoder-platform/work-manager/issues/933

See details https://github.com/topcoder-platform/work-manager/issues/933#issuecomment-740599485

![image](https://user-images.githubusercontent.com/146016/101493101-44e55c80-396e-11eb-9380-bb81101046c6.png)

- Direct, OR links and `Activate` button should be disabled if legacy challenge is not created yet. We also should show tooltip when hovering them saying "Legacy project is not yet created".
- For the NEW challenges don't show these links and `Activate` button at all.

**Comment by maxceem** [comment]
Done via https://github.com/topcoder-platform/work-manager/pull/945

- For the DRAFT projects it got disabled without legacy challenge

   ![image](https://user-images.githubusercontent.com/146016/101503708-0e620e80-397b-11eb-8c91-7a98e4d6af2b.png)

- And for the NEW challenges it is not shown anymore

    ![image](https://user-images.githubusercontent.com/146016/101503851-394c6280-397b-11eb-95d5-76e344872b18.png)

**Comment by vikasrohit** [comment]
@drasticdpk @lakshmiathreya ready for testing on production.

**Comment by lakshmiathreya** [comment]
Activate button is enabled - legacy seems to be created - yet this is the error - 
<img width="1680" alt="Screenshot 2020-12-09 at 2 29 11 PM" src="https://user-images.githubusercontent.com/51733042/101607799-fea20300-3a2a-11eb-9e9d-f509773ab18f.png">

<img width="1680" alt="Screenshot 2020-12-09 at 2 28 30 PM" src="https://user-images.githubusercontent.com/51733042/101607794-fcd83f80-3a2a-11eb-869d-51e09d64e030.png">
<img width="1680" alt="Screenshot 2020-12-09 at 2 28 06 PM" src="https://user-images.githubusercontent.com/51733042/101607775-f77af500-3a2a-11eb-9667-499e4b679bd2.png">

**Comment by lakshmiathreya** [comment]
Here is a case where it is working as expected:
<img width="1680" alt="Screenshot 2020-12-09 at 2 32 47 PM" src="https://user-images.githubusercontent.com/51733042/101608296-8b4cc100-3a2b-11eb-9509-0706d0169883.png">
<img width="1680" alt="Screenshot 2020-12-09 at 2 33 13 PM" src="https://user-images.githubusercontent.com/51733042/101608306-90117500-3a2b-11eb-8ff9-5211667edbb9.png">

**Comment by lakshmiathreya** [comment]
@maxceem @vikasrohit - pls clarify. It seems to be working as expected in one case. However, in the other - the Activate button is enabled - yet the message shown up after Activate is misleading. Should I log another Issue for that?

**Comment by lakshmiathreya** [comment]
cc @drasticdpk

**Comment by maxceem** [comment]
Yes, @lakshmiathreya, please, log another issue for this case. The issue you see is on the backend - legacy is created, but we cannot activate it. In the UI we just don't allow activate when a legacy is not created.

**Comment by lakshmiathreya** [comment]
sure - @maxceem will log a different issue for the case where legacy is created.

**Comment by vikasrohit** [comment]
Referencing the issue which was observed above https://github.com/topcoder-platform/work-manager/issues/950
