### ISSUE TITLE
Copilot Role Mis-Match WM over OR

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#946]
**Steps** 
1. Create a challenge by assigning the copilot other than yourself
2. Observe the role on OR app.

**Reference** : 

![image](https://user-images.githubusercontent.com/25297859/101505418-6eb57800-399c-11eb-9849-973cf0766df4.png)

https://challenges.topcoder.com/projects/24943/challenges/636366bf-40db-4ee9-89fd-38eb85f7c952/view

**Comment by vikasrohit** [comment]
@drasticdpk Copilot is also added as Observer because every one on the team is added to the challenge as Observer. However, it is more likely that copilot addition to v5, was not able to sync it properly to the legacy.

**Comment by vikasrohit** [comment]
@acshields it should have been fixed with backend updates which fixed the copilot resource addition problem. fyi @rootelement

**Comment by vikasrohit** [comment]
@drasticdpk @lakshmiathreya marking it ready for qa just to keep the updated status of the issue. In my understanding it should be fixed with recent changes in legacy processors.

**Comment by drasticdpk** [comment]
Verified.
![image](https://user-images.githubusercontent.com/25297859/105022121-7a06c380-5a71-11eb-8b2b-2feb9a23eaeb.png)
