### ISSUE TITLE
Unable to unassign copilot once it is assign

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#948]
**Steps**
1. Open draft challenge which has assigned copilot.
2. Try to unassign the copilot.

**Reference** 
![image](https://user-images.githubusercontent.com/25297859/101608633-0e6f1680-3a2e-11eb-805d-76be3740e57e.png)

https://challenges.topcoder.com/projects/24943/challenges/f2827023-f799-4491-a6d2-a3686dcf9f65/edit

**Comment by lakshmiathreya** [comment]
cc @mtwomey

**Comment by drasticdpk** [comment]
QA Verified. 

**Before**
![image](https://user-images.githubusercontent.com/25297859/101865443-63319f00-3b9e-11eb-9bef-f1346610174e.png)

**After** 
![image](https://user-images.githubusercontent.com/25297859/101865489-83615e00-3b9e-11eb-8c2a-6f75779d6985.png)


![image](https://user-images.githubusercontent.com/25297859/101865798-5e211f80-3b9f-11eb-8783-de998f580e2d.png)
cc @vikasrohit

**Comment by vikasrohit** [comment]
@drasticdpk new designs are due soon, so hopefully it won't be rendered like this in new designs.
