### ISSUE TITLE
Add  Standard Terms for Topcoder Competitions link with validation message. 

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#949]
**Steps** 
1. Create a task and assign the task to user who has not accepted Standard Terms for Topcoder Competitions  ( eg **makarThapa**)
2. And save it. You will get the validation error as shown below.

**Action item** 

Add the below link  with validation  message, so copilot can send the information to respective user in a second. 

https://www.topcoder.com/challenges/terms/detail/564a981e-6840-4a5c-894e-d5ad22e9cd6f

**Reference :** 

![screencapture-challenges-topcoder-projects-24943-challenges-f2827023-f799-4491-a6d2-a3686dcf9f65-edit-2020-12-09-15_23_19](https://user-images.githubusercontent.com/25297859/101613790-4711ee80-3a34-11eb-968c-cb9e2db91e78.png)

**Comment by drasticdpk** [comment]
cc @lakshmiathreya @mtwomey

**Comment by maxceem** [comment]
Done by https://github.com/topcoder-platform/work-manager/pull/967

Multiples terms (select `NDA` to have the 2nd term unsigned):

![image](https://user-images.githubusercontent.com/146016/101812735-6daf5280-3b24-11eb-8431-520fd5fd92b2.png)

One term:

![image](https://user-images.githubusercontent.com/146016/101812887-a818ef80-3b24-11eb-996a-ce6df8260216.png)

**Comment by vikasrohit** [comment]
@drasticdpk @lakshmiathreya @mtwomey it would be deployed to prod in 15 min

**Comment by drasticdpk** [comment]
@vikasrohit having console error, please check.
Showing **Saving....** for long time.
![image](https://user-images.githubusercontent.com/25297859/101896853-b709ab80-3bd1-11eb-811b-0d4e682b98c4.png)

**Comment by maxceem** [comment]
> @vikasrohit having console error, please check.
> Showing Saving.... for long time.

@vikasrohit hotfix for this issue https://github.com/topcoder-platform/work-manager/pull/984

**Comment by vikasrohit** [comment]
@drasticdpk it is ready for QA after fixing the issue found.
