### ISSUE TITLE
Update "Give Application Feedback" Hyperlink

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#954]
For now, when a user clicks "Give Application Feedback" in Work Manager, they should be redirected to this Github repo: https://github.com/topcoder-platform/work-manager/issues/new

Please disable the Google Forms hyperlink and have it redirect to this new one.

**Comment by drasticdpk** [comment]
QA Verified.

 
![image](https://user-images.githubusercontent.com/25297859/101866032-f15a5500-3b9f-11eb-8ebd-f8c502b602e8.png)
