### ISSUE TITLE
Show progress of Save operation for Save Draft button

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#956]
Earlier the `Save` button used to give a hint of progress by changing the text to `Saving` while the API calls are in progress, however, `Save Draft` button don't show such progress. It would be nice to have it change to `Saving` to give a hint that something is in progress.

**Comment by drasticdpk** [comment]
QA verified.

![image](https://user-images.githubusercontent.com/25297859/101873843-ce37a180-3baf-11eb-931a-23c4afd5f49a.png)
