### ISSUE TITLE
Unable to un-assign task owner once assigned

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#957]
Similar to https://github.com/topcoder-platform/work-manager/issues/948 we are not able to un-assign the task owner once task is assigned.

**Comment by vikasrohit** [comment]
fyi @lakshmiathreya @drasticdpk @mtwomey @acshields

**Comment by drasticdpk** [comment]
QA Verified.

![image](https://user-images.githubusercontent.com/25297859/101875937-a0ecf280-3bb3-11eb-9120-8098de65007f.png)
