### ISSUE TITLE
Public specification validation message shown below Add private specification button.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/work-manager#958]
Description:

Public specification validation message is shown below Add private specification button.

Expected:
It should be shown below the Public specification textbox.

![image (15)](https://user-images.githubusercontent.com/55895538/101765096-32148880-3b24-11eb-839e-8452ad61677f.png)

**Comment by maxceem** [comment]
Done via https://github.com/topcoder-platform/work-manager/pull/963

![image](https://user-images.githubusercontent.com/146016/101769681-024b8d80-3af0-11eb-8565-c6e678ef8891.png)

**Comment by drasticdpk** [comment]
QA verified.

![image](https://user-images.githubusercontent.com/25297859/101866561-3468f800-3ba1-11eb-8fb9-0f31bf4f49bd.png)
