### ISSUE TITLE
Wrong position of validating message for Public Specification.

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#959]
**Steps**
 1. Save draft challenge without filling required fields. 

**Reference**

![image](https://user-images.githubusercontent.com/25297859/101765499-7d6d6d80-3b09-11eb-9047-fdec4dda06c7.png)

**Comment by drasticdpk** [comment]
cc @lakshmiathreya

**Comment by vikasrohit** [comment]
Duplicate of #958
