### ISSUE TITLE
Error when updating challenge - After terms error and without refreshing page choosing the assignee who has accepted the terms

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#960]
@lakshmiathreya can you please get more details to this one? I have tried to encapsulate the details in title.

**Comment by drasticdpk** [comment]
Based on issue description, It is verified and now it is working as expected.
If needed we can re-open it. cc @lakshmiathreya 

**Reference** :

https://monosnap.com/file/Q6EVZ4TkfGqS9CiG1gM5C0D06s3HPH
