### ISSUE TITLE
Could not find private specification 

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#961]
**Steps** 

1. Add private specification at WM APP. and launch it.
2. Register the challenge and observe it .

**Reference** 
![image](https://user-images.githubusercontent.com/25297859/101766874-84957b00-3b0b-11eb-9a92-9bc545054310.png)

https://challenges.topcoder.com/projects/24943/challenges/1cf7a68c-27fb-4b24-8e81-5e55ebb88110/view

**Comment by SathyaJayabal** [comment]
@drasticdpk , the change  to display the  private spec is in staging in comm app. please check on staging.
