### ISSUE TITLE
Cannot get paid more than $40 as copilot

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/work-manager#965]
**Describe the bug**
I had to pay myself out - so I created a task using Work Manager. It was copilot payment task. And I set the amount to more than $40.

Yet, I now see in my PACTs that the payment I have received is $40

**To Reproduce / Actual Behavior**
Create copilot payment task, with the copilot payment set to more than $40. Close the task out. Check PACTs after a while - the payment received in $40.

**Expected behavior**
It should pay out to the amount set against the copilot payment and not $40

**Comment by maxceem** [comment]
Just sharing my experience on this.

On 5th December 2020 I created a task with a copilot fee of more than $40 and it worked well for me https://challenges.topcoder.com/projects/25300/challenges/069b2237-a72a-4547-b504-1286b233cdde/view.

Maybe it some intermittent issue with legacy sync.

**Comment by vikasrohit** [comment]
@callmekatootie can you please confirm as well if you are not seeing the issue now? We can close it after your confirmation.

**Comment by maxceem** [comment]
@vikasrohit I could reproduce this today. I've made a task payment and set the copilot fee higher than `$40`, but in the payment, I got `$40`.

So I guess this is something with legacy sync, as this issue happens not 100% times.

**Comment by vikasrohit** [comment]
okay, I guess we need to keep it open.

**Comment by rootelement** [comment]
This should've been fixed as of Feb 10th. Please confim and close.

**Comment by vikasrohit** [comment]
@maxceem could you please check it one more time?

**Comment by callmekatootie** [comment]
Just verified - I received more than $40 as set in the task. Resolved :+1:
