### ISSUE TITLE
Button hover style not consistent

### ISSUE THREAD

**Issue by dedywahyudi** [topcoder-platform/work-manager#971]
**Describe the bug**
Button hover style not consistent

**To Reproduce / Actual Behavior**
1. Create new challenge 
2. Check all buttons for hover style
2. Some using underline, some are not

**Expected behavior**
Need use consistent hover style. Or remove all those underline when hover

**Screenshots or Video**
![Screen Shot 2020-12-11 at 12 37 00](https://user-images.githubusercontent.com/4476442/101867399-a1828a80-3bad-11eb-8b70-542b77785309.png)
![Screen Shot 2020-12-11 at 12 37 10](https://user-images.githubusercontent.com/4476442/101867401-a2b3b780-3bad-11eb-920b-3faf93bd8dbf.png)

**Comment by acshields** [comment]
This will be fixed with our new UI design.
