### ISSUE TITLE
Project Page Design & Layout Improvements

### ISSUE THREAD

**Issue by dedywahyudi** [topcoder-platform/work-manager#972]
**Describe the bug**
Project Page Design & Layout Improvements

**To Reproduce / Actual Behavior**
1. Go to https://challenges.topcoder.com/
2. Click any project
3. You'll see Project page

**Expected behavior**
- Project title need move up so not aligned with those buttons
- Text inside the buttons need use 1 line
- Tab need showing All by default, this will contains all challenges with different status. Right now we need to click each tab if we just have Draft challenge since the Active tab always show up at the first load. 

**Screenshots or Video**
![Screen Shot 2020-12-11 at 12 39 35](https://user-images.githubusercontent.com/4476442/101867549-ff16d700-3bad-11eb-8d32-c7a75da14dfd.png)

**Comment by acshields** [comment]
This will be fixed with our new UI designs.
