### ISSUE TITLE
Start Date field need consistent bottom margin 

### ISSUE THREAD

**Issue by dedywahyudi** [topcoder-platform/work-manager#975]
**Describe the bug**
Start Date field need consistent bottom margin 

**To Reproduce / Actual Behavior**
1. Create new Design Challenge
2. Start Date field too close with the box

**Expected behavior**
Start Date field need consistent bottom margin 

**Screenshots or Video**
![Screen Shot 2020-12-11 at 12 56 34](https://user-images.githubusercontent.com/4476442/101868622-54ec7e80-3bb0-11eb-8e25-788fec49089c.png)

**Comment by acshields** [comment]
This will be fixed with the new UI designs.
