### ISSUE TITLE
Save Draft button's tooltip is displayed on hovering over Launch as Active button.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/work-manager#976]
Description:
Save Draft's tooltip is displayed on hovering over Launch as Active button.

Expected result:
Tooltip mentioning about Save draft button should not be displayed on hovering over Launch as Active button.

![image](https://user-images.githubusercontent.com/55895538/101870232-8b33f900-3bc4-11eb-9a65-83d9a6dc9a20.png)

**Comment by maxceem** [comment]
@vikasrohit this tooltip is handled by Chameleon, so I cannot control it.

As now we have a reusable component for tooltips, I suggest disable all Chamelon tooltips, list all the places for them (I guess there are more of them) and implement them in code. So they would be also shown in DEV env, as Chameleon doesn't show them on DEV.

**Comment by vikasrohit** [comment]
Got it. I would get them fixed in chameleon. For now it is difficult to get Chameleon enabled in dev and hard coding in code, makes it difficult to dynamically update it for Product manager.

**Comment by vikasrohit** [comment]
@acshields you have to update it in Chameleon.

**Comment by acshields** [comment]
@maxceem @vikasrohit - thanks for alerting me. I will get it corrected!
