### ISSUE TITLE
Design Challenge with 2 Rounds not displayed correct date in Challenge Page

### ISSUE THREAD

**Issue by dedywahyudi** [topcoder-platform/work-manager#977]
**Describe the bug**
Design Challenge with 2 Rounds not displayed correct date in Challenge Page

**To Reproduce / Actual Behavior**
1. Create New Design Challenge 
2. Launch the Challenge
3. Because there's no Round 1 & Round 2 section in Work Manager, we need go to Direct to add that
4. After add the Round 1 & Round 2 date and information
5. Then, go to Challenge page, Checkpoint Submissions and other dates not synchronize. 

**Expected behavior**
- Challenge page need clearly showing the Checkpoint & Final Round Deadline 

**Screenshots**
![Screen Shot 2020-12-11 at 14 46 37](https://user-images.githubusercontent.com/4476442/101876987-e9aaa880-3bbf-11eb-928b-767088be5d99.png)
![Screen Shot 2020-12-11 at 14 46 44](https://user-images.githubusercontent.com/4476442/101876993-eadbd580-3bbf-11eb-823d-9568e84946ff.png)
![Screen Shot 2020-12-11 at 14 46 49](https://user-images.githubusercontent.com/4476442/101876994-eb746c00-3bbf-11eb-803e-1576ceed58ad.png)
![Screen Shot 2020-12-11 at 14 47 02](https://user-images.githubusercontent.com/4476442/101876996-ec0d0280-3bbf-11eb-8d1e-bdabc151b6ea.png)

**Comment by vikasrohit** [comment]
I don't know what to do here @acshields

**Comment by acshields** [comment]
@vikasrohit - noted.
@rootelement - is this a backend change or one exclusively for Community App front-end?

**Comment by acshields** [comment]
closing because this is a Community App fix and can't be fixed by WM. Have passed along this issue to Oanh.
