### ISSUE TITLE
Recently Created challenge not showing

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#978]
Challenge  **[Dev][Challenge][Active button** is not listed on Active tab.

**Reference** 

![image](https://user-images.githubusercontent.com/25297859/101877654-72244b80-3bb6-11eb-88fa-b51c010bbc64.png)

https://www.topcoder.com/direct/contest/detail.action?projectId=30156496
https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30156496

**Comment by vikasrohit** [comment]
This is weird. Did you update any thing in legacy apps for this challenge?

**Comment by vikasrohit** [comment]
@rootelement @mtwomey it seems to be a P0 issue.

**Comment by vikasrohit** [comment]
@drasticdpk did you create this challenge yourself? It seems like it belongs to a group which you might not be part of.

**Comment by drasticdpk** [comment]
@vikasrohit ,
1. Yes  I have created this challenge. 
2. I am not sure which group i have added, can you please  remove it from group. I will check.
3. For me other challenges are also not showing. 
![image](https://user-images.githubusercontent.com/25297859/101907556-d2c97d80-3be2-11eb-833d-2588f7eea9a6.png)

**Comment by vikasrohit** [comment]
ok, I think we recently added few challenges which were not in group to a private group so that they are not visible on public challenge listing page. @lakshmiathreya can you please help @drasticdpk to add him to appropriate group?

**Comment by lakshmiathreya** [comment]
I checked the group - Its 'Hide Challenges' and @drasticdpk is in that Group.
<img width="1680" alt="Screenshot 2020-12-11 at 6 45 58 PM" src="https://user-images.githubusercontent.com/51733042/101907910-394d9c00-3be1-11eb-9d86-0bf60e6ce549.png">

**Comment by lakshmiathreya** [comment]
<img width="1680" alt="Screenshot 2020-12-11 at 6 47 50 PM" src="https://user-images.githubusercontent.com/51733042/101908032-7154df00-3be1-11eb-9101-8b01d6cfba05.png">

**Comment by vikasrohit** [comment]
I updated the group for the particular challenge to be `Hide challenges` earlier it was some different group. @drasticdpk can you please check if you can see that challenge now?

**Comment by lakshmiathreya** [comment]
@vikasrohit @rootelement - pls see my challenge - I have activated it multiple times and it goes back to Draft - showing up multiple times. I have verified my Group membership to Hide Challenges.
<img width="1680" alt="Screenshot 2020-12-11 at 7 26 26 PM" src="https://user-images.githubusercontent.com/51733042/101911872-f8f11c80-3be6-11eb-9df5-3b8c6affc6d1.png">
<img width="1680" alt="Screenshot 2020-12-11 at 7 26 44 PM" src="https://user-images.githubusercontent.com/51733042/101911886-fe4e6700-3be6-11eb-9fd5-d48dfb67e55d.png">
<img width="1680" alt="Screenshot 2020-12-11 at 7 27 34 PM" src="https://user-images.githubusercontent.com/51733042/101911894-01e1ee00-3be7-11eb-93d2-7f3e3db578a3.png">

**Comment by drasticdpk** [comment]
Now requested challenge has been listed.  cc @vikasrohit @lakshmiathreya 

**Reference** 
![image](https://user-images.githubusercontent.com/25297859/101924122-60639800-3bf8-11eb-8e03-b636062e525c.png)
