### ISSUE TITLE
Review type changed to Community after few minutes of activating the challenge

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/work-manager#979]
Description:
Review type changed to Community after few minutes of activating the challenge

Steps to Reproduce:
1. Create a QA challenge
2. Set the Reviewer type as internal and assign a member.
3. Enter other mandatory fields and click save draft.
4. Launch the challenge .
5. View the challenge after few minutes of creating it.

Actual result:
Review type changed from Internal to Community.

<img width="960" alt="QA_challenge" src="https://user-images.githubusercontent.com/55895538/101883249-5632a100-3bda-11eb-87f3-17219fa5ef07.png">
<img width="959" alt="QA_chall_review type" src="https://user-images.githubusercontent.com/55895538/101883273-5c288200-3bda-11eb-86d6-23e9636a9abe.png">

**Comment by vikasrohit** [comment]
Solution to the issue is done as fix for https://github.com/topcoder-platform/work-manager/issues/995

**Comment by lakshmiathreya** [comment]
Community Review selection is disabled. Design challenges have only 1 review type which is saved correctly. Verified in Prod.<img width="1680" alt="Screenshot 2020-12-16 at 2 58 14 PM" src="https://user-images.githubusercontent.com/51733042/102330131-31aa4080-3faf-11eb-90e7-1d97c6b91f71.png">

**Comment by lakshmiathreya** [comment]
<img width="1680" alt="Screenshot 2020-12-16 at 3 09 29 PM" src="https://user-images.githubusercontent.com/51733042/102331550-ff014780-3fb0-11eb-884e-25af764b8cec.png">

**Comment by lakshmiathreya** [comment]
@vikasrohit For QA Challenges - as a parallel - do the Business rules mandate Community Review only? Is that why it switches from Internal to Community for QA challenges?
The problem reported above is continuing to happen for QA challenges. Pls clarify. Should we disable Internal review selection for QA challenges via UI ?

**Comment by lakshmiathreya** [comment]
<img width="1680" alt="Screenshot 2020-12-16 at 3 28 17 PM" src="https://user-images.githubusercontent.com/51733042/102333675-c151ee00-3fb3-11eb-8375-868d188b545c.png">
<img width="1680" alt="Screenshot 2020-12-16 at 3 28 42 PM" src="https://user-images.githubusercontent.com/51733042/102333692-c6af3880-3fb3-11eb-81d9-0242fc8ea64d.png">
<img width="1680" alt="Screenshot 2020-12-16 at 3 29 28 PM" src="https://user-images.githubusercontent.com/51733042/102333699-c7e06580-3fb3-11eb-86e6-ddade18ad1a7.png">
<img width="1680" alt="Screenshot 2020-12-16 at 3 29 36 PM" src="https://user-images.githubusercontent.com/51733042/102333705-ca42bf80-3fb3-11eb-8601-1445e17c6866.png">
<img width="1680" alt="Screenshot 2020-12-16 at 3 30 36 PM" src="https://user-images.githubusercontent.com/51733042/102333713-cb73ec80-3fb3-11eb-865c-2780438899cd.png">

**Comment by vikasrohit** [comment]
@lakshmiathreya disabled the internal review option for QA challenge under the issue https://github.com/topcoder-platform/work-manager/issues/1001
