### ISSUE TITLE
Challenge activation issues

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/work-manager#993]
1. If some error happens (for example billing account is not attached) during challenge activation from the **details view page**, the popup is closed without showing an error, see demo video https://monosnap.com/file/JRDUbei6SjypqxBdbcBDTclQl1JX2q (this works good from the **list** page https://monosnap.com/file/GYSIqMRmDocJq9qmbXpUj6XvGABCFJ)

2. If the challenge is activated successfully from the **details view page** it is not moved to the active tab immediately and is still shown on the Draft tab https://monosnap.com/file/hhFa8Yx0IgBvaXkAQDqIqicsnaSPKO

3. The challenge is not going to **Active** tab, when activating form the **Draft** tab **list** https://monosnap.com/file/NMOtQvHxdCu1zxifMkfstU2S8Qmymi

**Comment by maxceem** [comment]
@vikasrohit Fixed by https://github.com/topcoder-platform/work-manager/pull/994. Verifications videos:

1. https://monosnap.com/file/5voZpuyEhcknJwTTLTeFWyeVokXtyo

2. https://monosnap.com/file/NEhKmoSMrtWpAFwKUXz8NQm6hFFZak

3. https://monosnap.com/file/u9FzEuoAsyIb572CZ9slJXRN3bVR2Q

**Comment by vikasrohit** [comment]
Thanks @maxceem

**Comment by lakshmiathreya** [comment]
Verified Activation via Listing and View Challenge in Prod.
