### ISSUE TITLE
Disable selection of Community Review type for Design challenges

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#995]
### Expected behavior
WM should not allow editing the review type for design challenges

### Actual behavior
As of now it allows user to edit the review type for a design challenge which gets overridden once the legacy challenge is created because of a business rule which does not allow review type to be community for a design challenge.

### Steps to reproduce the problem
- Create a design challenge
- Choose Community as review type
- Save as Draft and then Activate it
- Wait for 3-5 minutes to sync to settle down
- Now, edit the activated challenge and observe that Review type is set to Internal now.

### Screenshot/screencast
<img width="913" alt="Screen Shot 2020-12-16 at 9 36 24 AM" src="https://user-images.githubusercontent.com/2417632/102303880-2c82cc80-3f82-11eb-8eef-3c2b2459baae.png">

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Copilot/Manager
- Account used: N/A

**Comment by vikasrohit** [comment]
Linking https://github.com/topcoder-platform/work-manager/issues/979 for setting context of what was the actual issue for which we are going to apply this approach.

**Comment by lakshmiathreya** [comment]
Verified in Prod.
<img width="1680" alt="Screenshot 2020-12-16 at 1 22 50 PM" src="https://user-images.githubusercontent.com/51733042/102329805-d4ae8a80-3fae-11eb-99a5-dffdd7daaabc.png">
