### ISSUE TITLE
Submission Limit not matching with Challenge Page

### ISSUE THREAD

**Issue by dedywahyudi** [topcoder-platform/work-manager#998]
### Expected behavior
Submission Limit not matching with Challenge Page if user select Limited or Unlimited under Maximum Number of Submissions.

### Actual behavior
Submission Limit not matching with Challenge Page

### Steps to reproduce the problem
- Create new Design Challenge
- Select Limit under Maximum Number of Submissions, filled with any number. 

### Screenshot/screencast

![Screen Shot 2020-12-16 at 14 20 14](https://user-images.githubusercontent.com/4476442/102317339-f48f7f80-3fa9-11eb-9271-1638492543eb.png)
![Screen Shot 2020-12-16 at 14 20 19](https://user-images.githubusercontent.com/4476442/102317341-f5281600-3fa9-11eb-996a-135df51d8bc5.png)

**Comment by acshields** [comment]
@rootelement - similar issue to the other design meta data ones that are logged.
